### ISSUE TITLE
Convert null values to NSNull using the array transformer

### ISSUE THREAD

**Issue by jspahrsummers** [Mantle/Mantle#107]
Originally mentioned in #106.

When using `mtl_JSONArrayTransformerWithModelClass:`, this array:

``` objc
[
    {"test_id":"test_id_1"}, 
    null, 
    {"test_id":"test_id_3"}, 
    {"test_id":"test_id_4"}
]
```

… should turn into an `NSArray` of `[Model, NSNull, Model, Model]`. Right now, it asserts because the `null` was unexpected.

**Comment by wlisac** [comment]
Is there a recommended way to opt out of this behavior?

**Comment by robb** [comment]
That seems like a sensible approach to me :+1:
