### ISSUE TITLE
MTLValidateAndSetValue crashes on nil value

### ISSUE THREAD

**Issue by atmoio** [Mantle/Mantle#121]
I'm trying to create a model from a JSON dictionary, and some values contain NULL. 

```
Location *location = [MTLJSONAdapter modelOfClass:[Location class] fromJSONDictionary:locationDic error:nil];
```

```
locationDic:
{
    address = "<null>";
    city = "<null>";
    created = "<null>";
    description = "<null>";
    "foursquare_id" = "<null>";
    id = "<null>";
    lat = "<null>";
    lng = "<null>";
    modified = "<null>";
    name = "<null>";
    phone = "<null>";
    state = "<null>";
    zip = "<null>";
}
```

I get a crash on line 47 in MTLModel.m on

```
if (forceUpdate || value != validatedValue) {
                [obj setValue:validatedValue forKey:key];
        }
```

```
*** Caught exception setting key "lat" : [<Location 0x85a20e0> setNilValueForKey]: could not set nil as the value for the key lat.
```

Is this intended functionality? Should it not just skip null values?

**Comment by rodericj** [comment]
Late to the game, but I ran into this issue today. We have a service that was returning a NULL when we were expecting a number for a time duration. The proper behavior on the client would be to interpret this as a 0. The solution was to implement `-validate<Key>:error:`. Said implementation is now responsible for correcting the value. My solution is to add this to my class:

```
- (void)validateDuration:(NSNumber **)duration error:(NSError **)error {
    // Very basic validation. If we get a nil, change it to @0
    if (*duration == nil) {
        *duration = @0;
    }
}
```

I'd love to know if either of you think that this is a crazy solution to the problem. cc @robb @mobitar

**Comment by rodericj** [comment]
I should note that this seems to be what the documentation for NSKeyValueCoding suggested in the second paragraph here.

```
/* Given a pointer to a value pointer, a key that identifies an attribute or to-one relationship, 
and a pointer to an NSError pointer, return a value that is suitable for use in
 subsequent -setValue:forKey: messages sent to the same receiver. If no validation is 
necessary, return YES without altering *ioValue or *outError. If validation is necessary 
and possible, return YES after setting *ioValue to an object that is the validated version
 of the original value, but without altering *outError. If validation is necessary but not possible, 
return NO after setting *outError to an NSError that encapsulates the reason that 
validation was not possible, but without altering *ioValue. The sender of the message
 is never given responsibility for releasing ioValue or outError.

The default implementation of this method searches the class of the receiver for a 
validator method whose name matches the pattern -validate<Key>:error:. If such a
 method is found it is invoked and the result is returned. If no such method is found, 
YES is returned.
*/
- (BOOL)validateValue:(inout id *)ioValue forKey:(NSString *)inKey error:(out NSError **)outError;
```

**Comment by robb** [comment]
@rodericj I do the same thing in production, seems reasable enough.

Note that your example method should return a `BOOL` though.

**Comment by rodericj** [comment]
@robb are you returning `YES` always or do you return `NO` if you end up changing the `inout` to a valid value?

**Comment by robb** [comment]
> If no validation is necessary, return YES without altering *ioValue or
> *outError. If validation is necessary and possible, return YES after setting
> *ioValue to an object that is the validated version of the original value, but
> without altering *outError. If validation is necessary but not possible,
> return NO after setting *outError to an NSError that encapsulates the reason
> that validation was not possible, but without altering *ioValue.

So `YES` I'd say ;-)

**Comment by rodericj** [comment]
shoulda rtfm that i even posted.
