### ISSUE TITLE
Complete Model Validation

### ISSUE THREAD

**Issue by sqlumee** [Mantle/Mantle#141]
Hi I am trying to Validate if a JSON I receive has some keys I would like to consider mandatories for accepting it.

For example, in this JSON:
{
    "book": {
        "title": "This is my book",
        "description": "This is an example of book to model with Mantle",
        "published_in": "1378937453",
        "num_pages": 200,
        "author": {
            "name": "Pepito Perez",
            "age": 23
        }
    }
}

At the moment I can validate if the title is nil or not. With the function:
# pragma mark - MTLValidationModel
- (BOOL)validateTitle:(NSString *_)value error:(NSError *_)error {
  if (*value != nil) {
      return YES;
  }
  if (error != NULL) {
      *error = [NSError errorWithDomain:BookModelError 
                                   code:BookModelErrorMissingTitle 
                               userInfo:nil];
  }
  
  return NO;
  }

But could I also validate if the JSON has not the "title"  key? 

I found this Pull Request: https://github.com/github/Mantle/pull/104

But I can´t make it works, I already defined the method validateTitle as above but it is never called if I don´t have the "title" key in my json

**Comment by ohwutup** [comment]
Trying to get some validation to work right now using this process and am crashing on model creation.

It seems as though `-validateValue:error:` is getting called upon creation rather than having to call it explicitly like in the above example?

Is this true? What is necessary for a valid `-validateValue:error:` method? Is there any documentation or example of this?

**Comment by jspahrsummers** [comment]
@ohwutup Were all your questions answered successfully in Slack?

**Comment by ohwutup** [comment]
@jspahrsummers, yes definitely. i can summarize in another comment and planned on writing up a short blog post about validation since docs/examples are kind of slim.

**Comment by ohwutup** [comment]
Got some great help on this from some of the people in Slack. To summarize:

`-validateValue:error:` takes in a pointer to the property in question. (This would have been obvious had I dug a bit deeper. Or maybe known a little more about this method in KVC.)

Where the header file explains `-validate:`
> If -validateValue:forKey:error: returns a new value, the property is set to that new value.

It really seems to just mean that at the time that invalidation is realized, the pointer to the object in question can be set to some other value.

Here is an example of defending against an improper type being set:
```
- (BOOL)validateMean:(id*)mean error:(NSError**)error {
    if (![*mean isKindOfClass:NSNumber.class]) {
        *mean = @0;
    }
    return YES;
}
```
It is also worth noting that using `+modelOfClass:fromJSONDictionary:error:` will call all validation methods, where `-initWithDictionary:error:` will not unless overridden to do so.

**Comment by jspahrsummers** [comment]
@ohwutup Thanks for the write-up!
