### ISSUE TITLE
Getting parent model

### ISSUE THREAD

**Issue by dcordero** [Mantle/Mantle#150]
Hi, I have a question. Having a json like this one:

```
{
    "key": "Node1",
    "value": "Value1",
    "children": [
        {
            "key": "Subnode1",
            "value": "SubValue1",
            "children": [
                {
                    "key": "SubSubNode1",
                    "value": "SubSubValue1"
                },
                {
                    "key": "SubSubNode2",
                    "value": "SubSubValue2"
                }
            ]
        }
    ]
}
```

I have a Model with 2 properties to model this json

@property (strong,nonatomic) NSString *key;
@property (strong,nonatomic) NSString *value;

And another property for the children

@property (strong,nonatomic) NSArray *children;

Which I parser using MTLValueTransformer using the subtree from "children" key.

The thing I would to have is a weak pointer in each submodel to the parent model. But I am checking Mantle and it process first the submodels before the models, so we still don´t have the parent object from the Transformer.

In the file/function
// MTLJSONAdapter 
// - (id)initWithJSONDictionary:(NSDictionary _)JSONDictionary modelClass:(Class)modelClass error:(NSError *_)error

the code is like...

```
[...]
[... Process submodels ...]
_model =     [self.modelClass initWithDictionary:dictionaryValue error:error];
```

It could be done creating a method for buiding the model with a dictionary but without the init, something like this:

// MTLJSONAdapter 
// - (id)initWithJSONDictionary:(NSDictionary _)JSONDictionary modelClass:(Class)modelClass error:(NSError *_)error

```
[...]
_model = [[self.modelClass alloc] init];
[... Process submodels sending _model to the transformer...]
[_model buildWithDictionary:dictionaryValue error:error];
[...]
```

But it changes a lot the structure of how Mantle works. What do you think about this problem/fix ?

**Comment by teradyl** [comment]
@jspahrsummers what you say works well, but then I lose the readonly properties on my child models since I'm setting them in the parent model. Is there a way to keep the readonly status of those variables?

**Comment by jspahrsummers** [comment]
Expose a private header that makes them `readwrite`, or use Key-Value Coding to circumvent the interface (generally not recommended, but might be appropriate here if you don't like the first solution).
