### ISSUE TITLE
Hiding Mantle from clients of a model

### ISSUE THREAD

**Issue by brow** [Mantle/Mantle#156]
Say I'm using Mantle to write a set of API bindings, which I distribute as a static library. My library exposes a class `Person` which, since it corresponds directly to an API response, is a subclass of `MTLModel`.

```
#import "Mantle.h"

@interface Person : MTLModel <MTLJSONSerializing>

@property (nonatomic, copy, readonly) NSString *name;

@end
```

But now I'm exposing Mantle to my library's client, which I don't want to do. How can I avoid this?

It seems as though `Person` will need to encapsulate `MTLModel` rather than inherit from it. But can I do that without declaring each property of my model in two different classes?

**Comment by brow** [comment]
:confetti_ball: https://github.com/Mantle/Mantle/pull/219 :us:

**Comment by jspahrsummers** [comment]
lawl
