### ISSUE TITLE
Own adapters

### ISSUE THREAD

**Issue by dcordero** [Mantle/Mantle#203]
I created my own adapter using the new "JSONKeyPathForPropertyKey" way. But I am having some problems since from the reversed transformer I can not know what Adapter was used for the main model. And I am forced to use the MTLJSONAdapter instead of mine, getting a different behaviour for the nested models.

So my proposal is sending the Adapter to the transformers, allowing get the wanted behaviour on demand

```
// MTLJSONAdapter.m
-value = [transformer reverseTransformedValue:value withAdapter:self] ?: NSNull.null;
+value = [transformer reverseTransformedValue:value] ?: NSNull.null;
```

```
// MTLValueTransformer
- - (id)reverseTransformedValue:(id)value {
-	return self.reverseBlock(value);
+ - (id)reverseTransformedValue:(id)value withAdapter:(MTLJSONAdapter *)adapter {
+	return self.reverseBlock(value, adapter);
```
 
```
// MTLValueTransformer.h
-typedef id (^MTLValueTransformerBlock)(id);
+typedef id (^MTLValueTransformerBlock)(id,MTLJSONAdapter *);
```

**Comment by robb** [comment]
Closed by #474
