### ISSUE TITLE
Invalid parameter not satisfying: [modelClass isSubclassOfClass:MTLModel.class]

### ISSUE THREAD

**Issue by l4u** [Mantle/Mantle#217]
I got errors when running my tests with XCTest.
`NSParameterAssert([modelClass isSubclassOfClass:MTLModel.class]);` failed in MTLJSONAdapter.
when I run  

```
[MTLJSONAdapter modelOfClass:[MyModelSubclassedFromMTLModel class] fromJSONDictionary:JSON error:nil];
```

I've checked that the `modelClass` i.e. `MyModelSubclassedFromMTLModel` is a subclass of `MTLModel`.
But strangely the assertion failed.
By removing the assertion, it actually works.

Mantle was installed with CocoaPods.
This might be related to http://stackoverflow.com/questions/19883472/objc-nsobject-issubclassofclass-gives-incorrect-failure

**Comment by tomj** [comment]
Funny, I was just having this issue - removed the pod containing Mantle from my test target, ran a `pod install` then added it back and ran a `pod install` again and everything was ok.

Weird.
