### ISSUE TITLE
MTLManagedObjectAdapter could delete existing object if there is validation error

### ISSUE THREAD

**Issue by kylef** [Mantle/Mantle#223]
Discovered while making #220. If `validateForInsert` returns NO and the object came from a uniquing predicate, then it could be deleted. I think it would be better if it didn't make any changes and shouldn't delete existing objects.

I'm not sure how this could clearly be done, hence why I'm making an issue instead of a pull request. Other than making a child-context and throwing it away on failure.

Here is the basic code-path for this issue, it first gets an object using the `uniquingPredicate`, `validateForInsert` then returns NO and then it deletes the object in `deleteObject`.

```objective-c
    if (uniquingPredicate != nil) {
		managedObject = performInContext(context, ^ id {
                        // ...
			fetchRequest.predicate = uniquingPredicate;
			fetchRequest.returnsObjectsAsFaults = NO;
			fetchRequest.fetchLimit = 1;

			NSArray *results = [context executeFetchRequest:fetchRequest error:&fetchRequestError];

                        // ...
			return results.mtl_firstObject;
		});
    }

    // ...

	if (managedObject != nil && ![managedObject validateForInsert:&tmpError]) {
		managedObject = performInContext(context, ^ id {
			[context deleteObject:managedObject];
			return nil;
		});
	}
```

**Comment by robb** [comment]
Closing this one out for age ✌
