### ISSUE TITLE
Performanceissues with CoreData & Relationships

### ISSUE THREAD

**Issue by dschoeni** [Mantle/Mantle#244]
Hi!

I am facing some rather unpleasant issues after using CoreData, Relationships and all of this in combination with Mantle. Maybe I got something conceptually wrong which you could help me sort out.

I'm building a little "social network" with Posts, Comments and Threads that contain these Posts. My CoreData structure is as follows.

Thread 1:M Post
Post 1:M Comment
Comment 1:1 User
User 1:M Thread

I defined all those relationships with their inverse set as CoreData suggests to do. The whole construct works pretty well, but when using my NSFetchedResultsController things get messy. While preparing the UITableViewCell, I'm fetching the NSManagedObject that the NSFetchedResultsController provides and that gets transformed in a Mantle-Object (via [MTLManagedObjectAdapter modelOfClass:Post.class fromManagedObject:[[self fetchedResultsController] objectAtIndexPath:indexPath] error:nil]) - This takes too long though and therefore the whole thing lags a bit while scrolling through the list.

I wondered whether there is an alternative? I need mantle primarily to serialize the JSON into objects which works really well, it also works quite good with CoreData so far, but these issues are giving me a hard time.

Thanks for reading,

**Comment by jspahrsummers** [comment]
Core Data support has now moved to [a separate repository](https://github.com/Mantle/MTLManagedObjectAdapter). Please reopen this issue against that repo if you believe it's still valid.
