### ISSUE TITLE
Base MTLModel+NSCoding on property storage behavior

### ISSUE THREAD

**Issue by robb** [Mantle/Mantle#276]
As per #210

**Comment by jspahrsummers** [comment]
I've thought about this, and played around with the tests on #406, and I don't know that we should actually do this.

Although they're _very similar_, property storage and encoding behaviors represent conceptually different things, so I think combining them will introduce complexity (both for Mantle and for consumers).

I'd rather keep the distinct concepts separate and give users more flexibility.

**Comment by jspahrsummers** [comment]
To be clear, we can discuss this further if needed. I didn't actually mean to close it out.
