### ISSUE TITLE
Core Data uniquing performance

### ISSUE THREAD

**Issue by nickynick** [Mantle/Mantle#281]
Hey! I've been recently looking into Mantle as a solution for JSON <--> Model <--> Core Data conversion problem. I like how Mantle handles managed object uniquing, but I have a concern about performance. Right now, `MTLManagedObjectAdapter` makes a separate fetch request for each object being transformed. While it is certainly acceptable for simpler cases, it would most definitely become a performance problem when processing large sets of data. I've been dealing with this problem before and generally it requires some sort of a cache for a quicker existing managed object lookup. So, would it make sense to move the whole lookup logic into a separate `MTLManagedObjectAdapter` method or something like that? Adapter subclasses would be able to override the method and maintain some sort of a cache. 

And another rather off-topic question, how usable/stable is the development branch right now? Is it viable for production use?

Cheers!

**Comment by robb** [comment]
Closing this one out for age :v:
