### ISSUE TITLE
Map properties to multiple managed object key paths

### ISSUE THREAD

**Issue by nickynick** [Mantle/Mantle#283]
Do you think it would make sense to have the same thing as #270, but for managed objects? Most often I would store a small child object as several attributes on my managed object, rather than create a fully-fledged relationship. Not only it is better performance-wise, but also avoids mess like cleaning up orphan objects and setting inverse relationships (just imagine a value object used commonly throughout a domain).

In fact, I feel like `MTLJSONAdapter` and `MTLManagedObjectAdapter` should share some code related to property mapping. I think I'm willing to give this a shot if I'm allowed to :)

**Comment by jspahrsummers** [comment]
Core Data support has now moved to [a separate repository](https://github.com/Mantle/MTLManagedObjectAdapter). Please reopen this issue against that repo if you believe it's still valid.
