### ISSUE TITLE
Using Key -Value methods on managed objects incorrectly causes updates

### ISSUE THREAD

**Issue by calvincestari** [Mantle/Mantle#284]
It looks like using ```setValue:forKey``` on a managed object will have that object marked as being updated even if the content is the same.

Because Mantle is using KV methods for attributes/relationships it means that even if the source data didn't change your object will be marked as updated and any associated ```NSFetchedResultsController``` gets told to update itself. I have a fairly large object model where Mantle does all the managed object persistence. Even with uniquing properties the whole object graph is being refreshed when I know the data hasn't changed.

I think this can be solved by having Mantle do an ```isEqual:``` check before updating any attribute/relationship. ```isEqual:``` should filter down to the relevant ```isEqualToValue:```, ```isEqualToNumber:```, ```isEqualToString:``` etc. method. Worst case is that it doesn't resolve to the correct method, the objects get compared (which will fail) and then Mantle calls ```setValue:forKey:``` as normal.

Thoughts?

**Comment by jspahrsummers** [comment]
Core Data support has now moved to [a separate repository](https://github.com/Mantle/MTLManagedObjectAdapter). Please reopen this issue against that repo if you believe it's still valid.
