### ISSUE TITLE
Provide a mtl_JSONSetTransformerWithModelClass function in NSValueTransformer+MTLPredefinedTransformerAdditions.m

### ISSUE THREAD

**Issue by fatuhoku** [Mantle/Mantle#290]
At present, Core Data users who are using standard _unordered_ relationships in their data models will be bitten by #287.

Mantle implicitly encourages users to use  `NSArray` in their `MTLModel`s but Core Data enforces aforementioned relationships with `NSSet`s. The user is then put in a situation where he must also use `NSSet` in Mantle, which has no convenient JSON value transformer for serialisation.

**Comment by zhangxiaolian1991** [comment]
@adamwaite Thanks so much, This solve my question

**Comment by sao101** [comment]
@adamwaite @fatuhoku - Thanks for the input guys. Are you guys still using the suggested approach above? Or did you come across something better? Cheers.

**Comment by medopaw** [comment]
Here's the NSSet version of Mantle's `arrayTransformerWithModelClass:` and `mtl_arrayMappingTransformerWithTransformer:` with minimal modification:

`setTransformerWithModelClass:`

    + (NSValueTransformer <MTLTransformerErrorHandling> *)setTransformerWithModelClass:(Class)modelClass {
        NSValueTransformer<MTLTransformerErrorHandling> *dictionaryTransformer = [self dictionaryTransformerWithModelClass:modelClass];

        return [MTLValueTransformer transformerUsingForwardBlock:^ id (NSArray *dictionaries, BOOL *success, NSError **error) {
            if (dictionaries == nil) return nil;

            if (![dictionaries isKindOfClass:NSArray.class]) {
                if (error != NULL) {
                    NSDictionary *userInfo = @{
                            NSLocalizedDescriptionKey: NSLocalizedString(@"Could not convert JSON array to model set", @""),
                            NSLocalizedFailureReasonErrorKey: [NSString stringWithFormat:NSLocalizedString(@"Expected an NSArray, got: %@.", @""), dictionaries],
                            MTLTransformerErrorHandlingInputValueErrorKey : dictionaries
                    };

                    *error = [NSError errorWithDomain:MTLTransformerErrorHandlingErrorDomain code:MTLTransformerErrorHandlingErrorInvalidInput userInfo:userInfo];
                }
                *success = NO;
                return nil;
            }

            NSMutableSet *models = [NSMutableSet setWithCapacity:dictionaries.count];
            for (id JSONDictionary in dictionaries) {
                if (JSONDictionary == NSNull.null) {
                    [models addObject:NSNull.null];
                    continue;
                }

                if (![JSONDictionary isKindOfClass:NSDictionary.class]) {
                    if (error != NULL) {
                        NSDictionary *userInfo = @{
                                NSLocalizedDescriptionKey: NSLocalizedString(@"Could not convert JSON array to model set", @""),
                                NSLocalizedFailureReasonErrorKey: [NSString stringWithFormat:NSLocalizedString(@"Expected an NSDictionary or an NSNull, got: %@.", @""), JSONDictionary],
                                MTLTransformerErrorHandlingInputValueErrorKey : JSONDictionary
                        };

                        *error = [NSError errorWithDomain:MTLTransformerErrorHandlingErrorDomain code:MTLTransformerErrorHandlingErrorInvalidInput userInfo:userInfo];
                    }
                    *success = NO;
                    return nil;
                }

                id model = [dictionaryTransformer transformedValue:JSONDictionary success:success error:error];

                if (*success == NO) return nil;

                if (model == nil) continue;

                [models addObject:model];
            }

            return models;
        } reverseBlock:^ id (NSSet *models, BOOL *success, NSError **error) {
            if (models == nil) return nil;

            if (![models isKindOfClass:NSSet.class]) {
                if (error != NULL) {
                    NSDictionary *userInfo = @{
                            NSLocalizedDescriptionKey: NSLocalizedString(@"Could not convert model set to JSON array", @""),
                            NSLocalizedFailureReasonErrorKey: [NSString stringWithFormat:NSLocalizedString(@"Expected an NSSet, got: %@.", @""), models],
                            MTLTransformerErrorHandlingInputValueErrorKey : models
                    };

                    *error = [NSError errorWithDomain:MTLTransformerErrorHandlingErrorDomain code:MTLTransformerErrorHandlingErrorInvalidInput userInfo:userInfo];
                }
                *success = NO;
                return nil;
            }

            NSMutableArray *dictionaries = [NSMutableArray arrayWithCapacity:models.count];
            for (id model in models) {
                if (model == NSNull.null) {
                    [dictionaries addObject:NSNull.null];
                    continue;
                }

                if (![model isKindOfClass:MTLModel.class]) {
                    if (error != NULL) {
                        NSDictionary *userInfo = @{
                                NSLocalizedDescriptionKey: NSLocalizedString(@"Could not convert model set to JSON array", @""),
                                NSLocalizedFailureReasonErrorKey: [NSString stringWithFormat:NSLocalizedString(@"Expected a MTLModel or an NSNull, got: %@.", @""), model],
                                MTLTransformerErrorHandlingInputValueErrorKey : model
                        };

                        *error = [NSError errorWithDomain:MTLTransformerErrorHandlingErrorDomain code:MTLTransformerErrorHandlingErrorInvalidInput userInfo:userInfo];
                    }
                    *success = NO;
                    return nil;
                }

                NSDictionary *dict = [dictionaryTransformer reverseTransformedValue:model success:success error:error];

                if (*success == NO) return nil;

                if (dict == nil) continue;

                [dictionaries addObject:dict];
            }

            return dictionaries;
        }];
    }

`setMappingTransformerWithTransformer:`

    + (NSValueTransformer <MTLTransformerErrorHandling> *)setMappingTransformerWithTransformer:(NSValueTransformer *)transformer {
        NSValueTransformer<MTLTransformerErrorHandling> *arrayMappingTransformer = [NSValueTransformer mtl_arrayMappingTransformerWithTransformer:transformer];

        id (^forwardBlock)(NSArray *jsonArray, BOOL *success, NSError **error) = ^id (NSArray *jsonArray, BOOL *success, NSError **error) {
            NSError *underlyingError = nil;
            NSArray *modelArray = [arrayMappingTransformer transformedValue:jsonArray success:success error:&underlyingError];

            if (*success == NO) {
                if (error != NULL) {
                    NSDictionary *userInfo = @{
                            NSLocalizedDescriptionKey: NSLocalizedString(@"Could not transform array", @""),
                            NSLocalizedFailureReasonErrorKey: [NSString stringWithFormat:NSLocalizedString(@"Could not transform value", @"")],
                            NSUnderlyingErrorKey: underlyingError,
                            MTLTransformerErrorHandlingInputValueErrorKey: jsonArray
                    };
                    *error = [NSError errorWithDomain:MTLTransformerErrorHandlingErrorDomain code:MTLTransformerErrorHandlingErrorInvalidInput userInfo:userInfo];
                }
                return nil;
            }

            if (modelArray == nil) { return nil; }

            return [NSSet setWithArray:modelArray];
        };

        id (^reverseBlock)(NSSet *models, BOOL *success, NSError **error) = nil;
        if (transformer.class.allowsReverseTransformation) {
            reverseBlock = ^ id (NSSet *models, BOOL *success, NSError **error) {
                NSError *underlyingError = nil;
                NSArray *jsonArray = [arrayMappingTransformer reverseTransformedValue:models.allObjects success:success error:&underlyingError];

                if (*success == NO) {
                    if (error != NULL) {
                        NSDictionary *userInfo = @{
                                NSLocalizedDescriptionKey: NSLocalizedString(@"Could not transform set", @""),
                                NSLocalizedFailureReasonErrorKey: [NSString stringWithFormat:NSLocalizedString(@"Could not transform value", @"")],
                                NSUnderlyingErrorKey: underlyingError,
                                MTLTransformerErrorHandlingInputValueErrorKey: models
                        };
                        *error = [NSError errorWithDomain:MTLTransformerErrorHandlingErrorDomain code:MTLTransformerErrorHandlingErrorInvalidInput userInfo:userInfo];
                    }
                    return nil;
                }

                if (jsonArray == nil) { return nil; }

                return jsonArray;
            };
        }

        if (reverseBlock != nil) {
            return [MTLValueTransformer transformerUsingForwardBlock:forwardBlock reverseBlock:reverseBlock];
        } else {
            return [MTLValueTransformer transformerUsingForwardBlock:forwardBlock];
        }
    }
