### ISSUE TITLE
JSONTransformers and arrays

### ISSUE THREAD

**Issue by justinmakaila** [Mantle/Mantle#297]
I'm having an issue with a `JSONTransformer` method. Our API responds with JSON representing a `PVideo` object. This video object has an `NSMutableArray` property, `commentsArray`,  for comments. The response format is similar to that shown below:
````
{
  object:{
    ...
    comments:{
      ...
      results:[
        {
          object:{<Comment object>},
          subjectiveObjectMeta:{<Object representing relationship>}
        },
        ...
      ],
      ...
    },
    ...
}
````
The root object is the video, extracted into a `<class>Result` object via cluster class.
The `video.comments.results` are mapped to the `commentsArray` property in my model, where I use the following transformer to extract each comment object:
````
+ (NSValueTransformer*)commentsArrayJSONTransformer {
    return [MTLValueTransformer transformerWithBlock:^NSMutableArray* (NSArray *commentsJSONArray) {
        commentsJSONArray = _.arrayMap(commentsJSONArray, ^PComment* (NSDictionary *commentJSON) {
            PCommentResult *result = [MTLJSONAdapter modelOfClass:PCommentResult.class fromJSONDictionary:commentJSON error:nil];
            return result.comment;
        });
        
        return [NSMutableArray arrayWithArray:commentsJSONArray];
    }];
}
````
However, I can't add objects to the array, either with `addObject:` or `insertObject:atIndex`.

**Comment by haojianzong** [comment]
Are you using `commentsArray` or `comments` as the property name? If your property is `comments`, you should name the transformer as `commentsJSONTransformer`.

**Comment by justinmakaila** [comment]
Sorry, this is so old I don't even have the code anymore.
