### ISSUE TITLE
String to NSNumber for coredata

### ISSUE THREAD

**Issue by BadChoice** [Mantle/Mantle#313]
I have setup my model with some NSNumber properties

```
@property (copy, nonatomic, readonly) NSString* name;
@property (copy, nonatomic, readonly) NSNumber* price;
@property (copy, nonatomic, readonly) NSString* photo;
@property (copy, nonatomic, readonly) NSNumber* order;
```
then, I create the model with a json like the following one
```
{
                "name": "One created today",
                "price": "7.50",
                "photo": null,
                "order": "1",
}
```
Everything is ok, the model is created and I can access all the properties
finally (and here comes the problem) I create a  managedobject with the following function:

```
NSManagedObject* object =  [MTLManagedObjectAdapter managedObjectFromModel:self														  insertingIntoContext:context																		 error:&error];
```

And I get the following error:

```
NSInvalidArgumentException', reason: 'Unacceptable type of value for attribute: property = "order"; desired type = NSNumber; given type = __NSCFString; value = 0.'
```

If I use @1 instead of "1" it works so I tried to create my converter

```
+ (NSValueTransformer *)orderTransformer {
    DLog(@"HEREEEEEE!!!!");
    return [MTLValueTransformer reversibleTransformerWithForwardBlock:^(NSString *str) {
        return @([str intValue]);
    } reverseBlock:^(NSNumber *number) {
        return [number stringValue];
    }];
}
```

But the DLog is never called, and it crashes as well

Isn't the string converted automatically to NSNumber?

My pod file uses the following:

```
platform :ios, '7.0'
pod 'Mantle'
```

**Comment by chenyingsunny** [comment]
I have the same question! 
"so the conversion from the json string to NSNumber in model works great, is when converting from model to managed object that "crashes""
hope the conversion handled by default by mantle!

**Comment by robb** [comment]
@chenyingsunny again, there is no automatic conversion from `NSString *` to `NSNumber *` in Mantle, you can add a value transformer to do it for you however you see fit.

Closing this one for its age, feel free to reopen if you have more questions, though.
