### ISSUE TITLE
MTLManagedObjectAdapter fails with non-optional relationship transformers

### ISSUE THREAD

**Issue by kylef** [Mantle/Mantle#328]
Take this example, a workout is made up of multiple exercises. The exercises *require* there to be a workout attached to them.

#### Workout
- name (required)
- exercises (to many)

#### Exercise
- name (required)
- workout (to one, required)

My MTL models would look something like:

```objective-c
FFGExerciseModel * pushupExercise = [[FFGWorkoutModel alloc] initWithDictionary:@{ @"name": @"Push Ups" } error:nil];
NSDictionary *workoutDictionary = @{ @"name": @"Kyle's First Workout", @"exercises": @[pushupExercise] };
FFGWorkoutModel *workout = [[FFGWorkoutModel alloc] initWithDictionary:workoutDictionary error:nil];
```

When using MTLManagedObjectAdapter on the workout, it will fail because it will try importing the exercise which has a required inverse relation to a workout. The workout is not yet set because it's done via `workout.exercises`.

Workaround: Don't use required inverse relations.

**Comment by jspahrsummers** [comment]
Core Data support has now moved to [a separate repository](https://github.com/Mantle/MTLManagedObjectAdapter). Please reopen this issue against that repo if you believe it's still valid.
