### ISSUE TITLE
no such file or directory when import mantle

### ISSUE THREAD

**Issue by hmilyyjm** [Mantle/Mantle#332]
wo have do According to the text  Improting Mantle, but  I  can't  compile  success,
libMantle-iOS.a  is in Debug  folder, Not Debug-iphonesimulator   
my  Xcode is 5.1.1,   
error is down :

Ld /Users/hmily/Library/Developer/Xcode/DerivedData/weatherDemo-fslumiungngkthenkvaiiwfxlouw/Build/Products/Debug-iphonesimulator/weatherDemo.app/weatherDemo normal i386
    cd /Users/hmily/Downloads/demo/weatherDemo
    export IPHONEOS_DEPLOYMENT_TARGET=7.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk -L/Users/hmily/Library/Developer/Xcode/DerivedData/weatherDemo-fslumiungngkthenkvaiiwfxlouw/Build/Products/Debug-iphonesimulator -F/Users/hmily/Library/Developer/Xcode/DerivedData/weatherDemo-fslumiungngkthenkvaiiwfxlouw/Build/Products/Debug-iphonesimulator -F/Users/hmily/Downloads/demo/weatherDemo/../../../Library/Developer/Xcode/DerivedData/weatherDemo-fslumiungngkthenkvaiiwfxlouw/Build/Products/Debug/libMantle-iOS.a -filelist /Users/hmily/Library/Developer/Xcode/DerivedData/weatherDemo-fslumiungngkthenkvaiiwfxlouw/Build/Intermediates/weatherDemo.build/Debug-iphonesimulator/weatherDemo.build/Objects-normal/i386/weatherDemo.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=7.1 /Users/hmily/Library/Developer/Xcode/DerivedData/weatherDemo-fslumiungngkthenkvaiiwfxlouw/Build/Products/Debug-iphonesimulator/libMantle-iOS.a -framework Accelerate -framework CoreImage -framework CoreGraphics -framework UIKit -framework Foundation -Xlinker -dependency_info -Xlinker /Users/hmily/Library/Developer/Xcode/DerivedData/weatherDemo-fslumiungngkthenkvaiiwfxlouw/Build/Intermediates/weatherDemo.build/Debug-iphonesimulator/weatherDemo.build/Objects-normal/i386/weatherDemo_dependency_info.dat -o /Users/hmily/Library/Developer/Xcode/DerivedData/weatherDemo-fslumiungngkthenkvaiiwfxlouw/Build/Products/Debug-iphonesimulator/weatherDemo.app/weatherDemo

clang: error: no such file or directory: '/Users/hmily/Library/Developer/Xcode/DerivedData/weatherDemo-fslumiungngkthenkvaiiwfxlouw/Build/Products/Debug-iphonesimulator/libMantle-iOS.a'

**Comment by robb** [comment]
Closing for age
