### ISSUE TITLE
Mantle not compatible with Swift

### ISSUE THREAD

**Issue by justMaku** [Mantle/Mantle#344]
Trying to compile Mantle with Swift project in XCode 6 fails with this error message:
```
<unknown>:0: error: cannot override 'init' which has been marked unavailable
<unknown>:0: error: cannot override 'init' which has been marked unavailable
<unknown>:0: error: 'init' is unavailable: Replaced by -initWithDictionary:error:
<unknown>:0: error: 'init' is unavailable: Replaced by -[MTLJSONAdapter initWithJSONDictionary:modelClass:]
```

**Comment by fatuhoku** [comment]
Bump.

So... Mantle doesn't work with Swift still?

**Comment by ArsalanReal** [comment]
Ahhhh... DeadLock.

Mantle is not for Swift thats mean????

**Comment by maxgoedjen** [comment]
I don't know if it's really supported or anything, but I've definitely used it together at this point. It's doable, if not super nice to use.

**Comment by robb** [comment]
I'm closing this one out since it doesn't really involve a concrete issue anymore and was originally posed under Swift 1.0. Feel free to open a new one if you run into any problems :sparkling_heart:

**Comment by fatuhoku** [comment]
Hi, just leaving a note for anybody seeking a Mantle alternative for Swift.

Through some digging, I found [Pistachiargo](https://github.com/felixjendrusch/Pistachiargo). I have not tried it yet.

**Comment by fabb** [comment]
This one also looks interesting: https://github.com/Hearst-DD/ObjectMapper
