### ISSUE TITLE
MTLManagedObject merging

### ISSUE THREAD

**Issue by farski** [Mantle/Mantle#351]
I'm finally getting around to replacing the [workaround](https://github.com/Mantle/Mantle/issues/260#issuecomment-37407946) from #260 with `mergeValueForKey:fromManagedObject` from #272. The workaround "just worked" as I was using it, but I am having a really hard time getting merging to work at all, and even when I get close the solutions I'm coming up with seem too crazy to be how this was expected to get used.

This is the closest I've gotten in terms of having code that roughly does what I think needs to be done, but it doesn't even work because I need several private methods.

I must be missing something when it comes to doing a basic merge. Any suggestions?

```
- (void)mergeValueForKey:(NSString *)key fromManagedObject:(NSManagedObject *)managedObject {
  NSString *propertyKey = key;
  
  id value = [self valueForKey:propertyKey];
  
  if (!value || value == NSNull.null) {
    NSString *managedObjectKey = self.class.managedObjectKeysByPropertyKey[key];
    id managedObjectValue = [managedObject valueForKey:managedObjectKey];
    
    MTLManagedObjectAdapter *adapter = [[MTLManagedObjectAdapter alloc] initWithModelClass:self.class];
    
    NSValueTransformer *attributeTransformer = [adapter entityAttributeTransformerForKey:propertyKey];
    if (attributeTransformer != nil) value = [attributeTransformer reverseTransformedValue:value];
    
    [self setValue:managedObjectValue forKey:propertyKey];
  }
}
```

**Comment by jspahrsummers** [comment]
Core Data support has now moved to [a separate repository](https://github.com/Mantle/MTLManagedObjectAdapter). Please reopen this issue against that repo if you believe it's still valid.
