### ISSUE TITLE
Transforming nil to enum causing crashes

### ISSUE THREAD

**Issue by micnguyen** [Mantle/Mantle#384]
Hi,

I'm seeing similar style questions coming up about null/nil JSON parsing - but I've got a specific case that's kinda different, it seems pretty straightforward but apparently not.

I've got a JSON response for example... 

``` json
{
    type: "1"
}
```

I parse test into an enum by looking at it and comparing it to a dictionary:

``` objective-c
typedef NS_ENUM(NSUInteger, BKPaymentInfoType) {
    BKPaymentInfoHouseAccount = 0,
    BKPaymentInfoCreditCard = 1,
};
...
...
+ (NSValueTransformer *)typeTransformer {
    NSDictionary *states = @{
                             @"0": @(BKPaymentInfoHouseAccount),
                             @"1": @(BKPaymentInfoCreditCard)
                             };
    return [MTLValueTransformer reversibleTransformerWithForwardBlock:^(NSString *str) {
        return states[str];
    } reverseBlock:^(NSNumber *state) {
        return [states allKeysForObject:state].lastObject;
    }];
}
```

Now, sometimes type can be null and I want it to become another type of enum. However, I can't seem to add the following key/value to the Dict and have it parse properly. It will just crash 

``` json
{
    type: null
}
```

``` objective-c
[NSNull null] : @(BKPaymentSomeNullCaseEnum),
```

I thought you can have null as a key in a NSDict? Anyone have any pointers as to how this situation can be dealt with? Apologies if it has been answered somewhere else, I've been searching for ages now.

Cheers,
Mike

**Comment by thuai** [comment]
+1
