### ISSUE TITLE
use of undeclared identifier 'stderr' Mantle

### ISSUE THREAD

**Issue by wangjordy** [Mantle/Mantle#405]
The environment: xcode6.1, ios8.0
I use cocosPods build my project,  open xcworkspace file, the error 'use of undeclared identifier 'stderr' Mantle' is poped up in xcode when running the project!

I don't know why prompt the error!  So Could you help me to resolved the error!

Email: wangjordy@gmail.com

Thank you!

**Comment by sevdouglas** [comment]
Just include the following at EXTRuntimeExtensions.m:
#include <stdio.h>
#include <stdlib.h>

This should solve the problem.

**Comment by robb** [comment]
Closing this one for lack of activity, feel free to reopen it if the problem persists. :v:
