### ISSUE TITLE
[Discussion] Using Mantle with Swift

### ISSUE THREAD

**Issue by PrideChung** [Mantle/Mantle#421]
Surprisingly this topic hasn't been discuss very much, I know @jspahrsummers doesn't recommend using Mantle with Swift, but my old project is written in Objective-C and it use Mantle as it's model layer. I want to transit the codebase to Swift and keep the model layer unify in the mean time, so I have no choice but use Mantle with Swift, turns out it's not that bad.

Since Objective-C and Swift are so different fundamentally, there are some pitfalls when using Mantle with Swift. I've found solutions for some of them, so I think I should document it here for reference.
### Declaring Properties

Swift has very different way to initiate objects, in short it hates uninitiated properties. Since you normally don't want to override the initializer, you can declare a property as none optional and provide a default value to make sure this property is initialized so the compiler won't bother you. But you must ensure this property will never be nil in the response JSON or you will get a crash because the Objective-C part try to set the property as nil but the Swift part wont't let it.

``` swift
class User: MTLModel, MTLJSONSerializing {
    var name: String = ""
}
```

If you can't guarantee a property won't be nil, you should declare it as optional, then use it as normal optional value. But more often, I want to set a default safety value to replace the nil value. I found the following approach works pretty well:

``` swift
class User: MTLModel, MTLJSONSerializing {
    var name: String! = "" {
        didSet {
            if name == nil {
                name = ""
            }
        }
    }
}
```

I declare the `name` property as implicy unwrap optional so I don't bother to unwrap it everytime when I use it, it has a default value and if a nil value is set, I replace it with a safety empty string value, so this property will never be nil.
### Better MTLJSONAdapter API

Using MTLJSONAdapter in Swift requires you to provide the target model's type then cast the returned value into target model's type, why we have to write the type twice? Use generic! And passing in a NSError pointer for error reporting is Objective-C's practise, in Swift we have tuples for that.
I wrote a small wrapper for MTLJSONAdapter to make it easier to use, feel free to copy

``` swift
extension MTLJSONAdapter {
    class func modelOfClass<T: MTLModel>(T.Type, fromJSONDictionary: [String: AnyObject]?) -> (T?, NSError?) {
        var error: NSError?
        let model = modelOfClass(T.self, fromJSONDictionary: fromJSONDictionary, error: &error) as? T
        return (model, error)
    }

    class func modelsOfClass<T: MTLModel>(T.Type, fromJSONArray: [AnyObject]!) -> ([T]?, NSError?) {
        var error: NSError?
        let models = modelsOfClass(T.self, fromJSONArray: fromJSONArray, error: &error)
        return (models as? [T], error)
    }
}
```
### Type 'YourMTLModelSubclass' does not conform to protocol 'NSObjectProtocol'

WTF, why is my model not conforming to 'NSObjectProtocol', it's inherited from `MTLModel`! :anger:  
It looks like a bug in the Swift compiler, it will happen when your MTLModel subclass is written in Swift and it adopts a protocol is written in Objective-C.  I hope this bug no longer exist when you're reading this, but if it do,  add this lines to your `MTLModel` subclass, it's dark magic.

``` swift
//MARK: NSObjectProtocol hack
override func isEqual(object: AnyObject?) -> Bool {
    return super.isEqual(object)
}

override func `self`() -> Self {
    return self
}
```

-- More to Add --

**Comment by newbdez33** [comment]
You saved my ASS!!! Thank you!

**Comment by hlung** [comment]
Nice extension on `MTLJSONAdapter`!

I'm using Xcode 6.3.1 and iOS 8.3, I don't see that 'YourMTLModelSubclass' problem anymore :)

**Comment by jshier** [comment]
@PrideChung Are you still using Mantle with Swift? I could use some guidance regarding implementation, as I've been having issues with Mantle 2's value transformers not being called. Here's my class:
```
import Foundation
import Mantle

class SwiftCurrentWeather : MTLModel, MTLJSONSerializing {
    var currentWeather = "Failed to fetch current weather."
    
    static func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject]! {
        return ["currentWeather" : "current.temperature"]
    }
    
    class func currentWeatherJSONTransformer() -> NSValueTransformer {
        let _forwardBlock: MTLValueTransformerBlock? = { (value, success, error) in
            return "\(Formatters.temperatureFormatter(value as! NSNumber)) °F"
        }
        
        return MTLValueTransformer(usingForwardBlock: _forwardBlock)
    }
}

struct Formatters {
    static let _temperatureFormatter: NSNumberFormatter = {
        let formatter = NSNumberFormatter()
        formatter.numberStyle = .DecimalStyle
        formatter.maximumFractionDigits = 1

        return formatter
    }()

    static func temperatureFormatter(temperature: NSNumber) -> String? {
        return _temperatureFormatter.stringFromNumber(temperature)
    }
}
```

The `currentWeatherJSONTransformer()` function gets called but it doesn't actually call the `_forwardBlock` so no transformed value is returned.

Also, I'm currently getting a protocol error on `isEqual`:
```
Mantle.MTLModel:52:14: warning: parameter of 'isEqual' has different optionality than expected by protocol 'NSObjectProtocol'
  @objc func isEqual(object: AnyObject!) -> Bool
             ^
ObjectiveC.NSObjectProtocol:2:14: note: requirement 'isEqual' declared here
  @objc func isEqual(object: AnyObject?) -> Bool
```

**Comment by hlung** [comment]
I also get this `parameter of 'isEqual' has different optionality` warning in my Swift project too. Is there a fix yet?

```
/path/to/my/project/Mantle.MTLModel:52:14: Parameter of 'isEqual' has different optionality than expected by protocol 'NSObjectProtocol'
```

**Comment by truemetal** [comment]
I was able to fix the warning above by adding this method implementation into my MTLModel subclass

    override func isEqual(object: AnyObject?) -> Bool {
        if object == nil { return false }
        return super.isEqual(object)
    }

**Comment by borut-t** [comment]
I am also having issue JSONTransformer not executing forward block. Any clues?

**Comment by hlung** [comment]
I found a super easy way to use default value when input is nil.
- provide a default value in variable declaration as usual
- implement `-setNilValueForKey:` that which does nothing

```
class Page: MTLModel, MTLJSONSerializing {
    var likes: Int = 0

    class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject]! {
        return [
            "likes": "likes"
        ]
    }
    
    // skip setting nil value for all keys
    override func setNilValueForKey(key: String) {
        // do nothing
    }
}
```

**Comment by dev-gao** [comment]
Better MTLJSONAdapter API

**Comment by dev-gao** [comment]
'Better MTLJSONAdapter API ' does not work on Xcode7.3 Swift2.2。 ‘&’ used with non-inout argument of type ().

+ (id)modelOfClass:(Class)modelClass fromJSONDictionary:(NSDictionary *)JSONDictionary error:(NSError **)error
+ (id)modelOfClass:(Class)modelClass fromJSONDictionary:(NSDictionary *)JSONDictionary

These two method can not be differed in Swift2.2. When you use modelOfClass in Swift2.2 , Xcode consider it to be the second one. But The second method is deprecated and MTLJSONAdapter does not offer a way to invoke the first one.
