### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by hymanwang** [Mantle/Mantle#426]
When I install Mantle to my project manually, I can't find libMantle.a in step 4. It's targets include Mantle-Mac and Mantle-iOS, but Mantle-iOS is a framework, not static lib, how can I fix this issue?

**Comment by songfrank** [comment]
However, dylibs/framework are only supported on iOS 8.0 and later. But my app supported from iOS 7.0.

**Comment by jspahrsummers** [comment]
iOS 7 support was removed in https://github.com/Mantle/Mantle/pull/369#issuecomment-59981975. If you still require it, I'd suggest using [1.5.1](https://github.com/Mantle/Mantle/releases/tag/1.5.1).
