### ISSUE TITLE
Update CocoaPods podspec to 1.5.3

### ISSUE THREAD

**Issue by cfcommando** [Mantle/Mantle#432]
It's little more than bumping the tags in the podspec, but I think it requires someone with privileges update it on Mantle's behalf. This shouldn't take more than a couple of minutes of work, but is pretty important.

Thanks.

**Comment by kylef** [comment]
@robb I've assigned you since you have ownership of the Pod. I'm willing to take care of this if you would rather.

**Comment by dcaunt** [comment]
I also have access to update the Pods – I've [pushed 1.5.3](https://github.com/CocoaPods/Specs/blob/master/Specs/Mantle/1.5.3/Mantle.podspec.json) and it should be available shortly.

**Comment by robb** [comment]
Thanks, David!

**Comment by cfcommando** [comment]
Much appreciated, thank you!
