### ISSUE TITLE
Mantle with deeply nested JSON data?

### ISSUE THREAD

**Issue by StevenVeshkini** [Mantle/Mantle#433]
I have JSON data with 3 nested object types. The first two transform correctly into their respective MTLModel subclasses. However, it seems that the third (the most deeply nested group of objects) remains as an NSDictionary (or array of NSDictionaries). It seems like my code is fine (I am doing pretty much the exact same transformations in the third object type as the first two). Could there be something I am overlooking?

**Comment by robb** [comment]
Can you post some examples? It sounds like there may be a transformer that's set up incorrectly, but it's hard to tell with looking at the code.

**Comment by StevenVeshkini** [comment]
JSON:

    [
       {
          "title" : abcdefg
          "episodes" : [
              {
                  "title" : hijklmno
                  "videos" : [
                      {
                           "url" : xxxx
                      }, ...]
              }, ...]
        },
    ...]

Models:
```obj-c
@interface Series : MTLModel <MTLJSONSerializing>
@property (nonatomic, copy) NSString *title;
@property (nonatomic, strong) NSArray *episodes;
@end

@implementation
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"title" : @"title",
             @"episodes" : @"episodes"
    };
}
+ (NSValueTransformer *)episodesJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:Episode.class];
}
@end

@interface Episode : MTLModel <MTLJSONSerializing>
@property (nonatomic, copy) NSString *title;
@property (nonatomic, strong) NSArray *videos;
@end

@implementation Episode
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"title" : @"title",
             @"videos" : @"videos"
             };
}
+ (NSValueTransformer *)videosJSONTranformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:Video.class];
}
@end

@interface Video : MTLModel <MTLJSONSerializing>
@property (nonatomic, strong) NSURL *videoURL;
@end

@implementation Video
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"videoURL" : @"url"
             };
}
+ (NSValueTransformer *)videoURLJSONTransformer {
    return [NSValueTransformer valueTransformerForName:MTLURLValueTransformerName];
}
@end
```

The problem is that the video MTLModel's are remaining as dictionaries. @robb

**Comment by jspahrsummers** [comment]
Hmm, I don't see anything obviously wrong here. Can you paste the description for one of your incorrectly-instantiated Mantle models?

**Comment by StevenVeshkini** [comment]
Not exactly sure what you are looking for, but in the debugger it says that the incorrectly instantiated object is a NSCFDictionary and the representation is 

```
{
  url = "abc";
}
```

**Comment by robb** [comment]
Can you add breakpoints to all relevant transformer methods to see if they are hit?

**Comment by StevenVeshkini** [comment]
Ok I feel really stupid and I am so sorry for wasting you guys' time. I misspelled the videos json transformer as `videoJSONTranformer` instead of `videosJSONTransformer`.
