### ISSUE TITLE
Is it possible to map an array of an array of MTLModel objects?

### ISSUE THREAD

**Issue by jonahneugass-ck** [Mantle/Mantle#434]
I am trying to map the following and can't quite figure out how to do it:

<pre>
  "rows":[
          [
           {
           "text":"text1",
           "icon" : "icon",
           "link" : "http://link"
           }
           ],
          [
           {
           "text":"text2",
           "icon" : "icon",
           "link" : "http://link"
           }
           ]
          
          ]
</pre>

**Comment by jspahrsummers** [comment]
Yes, it's possible, but what do you want the resulting model graph to look like? Assumably the nested arrays are somehow relevant to the structure of the models, or else they wouldn't exist.

**Comment by jonahneugass-ck** [comment]
The nested arrays represent the sections and rows in a UITableView.

**Comment by jonahneugass-ck** [comment]
Never mind. Got it. Thanks for the help!

**Comment by ZaggerWang** [comment]
Can you share how did you do this?

**Comment by jonahneugass-ck** [comment]
Sure:

```
+ (NSValueTransformer *)allRowsJSONTransformer
{
    return [MTLValueTransformer transformerWithBlock:^id(NSArray *inSectionJSONArray) {
        NSMutableArray *sectionArray = [[NSMutableArray alloc] initWithCapacity:inSectionJSONArray.count];
        for( NSArray *section in inSectionJSONArray )
        {
            NSError *error;
            NSArray *cardItemArray = [MTLJSONAdapter modelsOfClass:[CKMCardItem class] fromJSONArray:section error:&error];
            if( cardItemArray != nil )
            {
                [sectionArray addObject:cardItemArray];
            }
        }
        return sectionArray;
    }];
}
```
