### ISSUE TITLE
How to filter which property should be used in NSCoding

### ISSUE THREAD

**Issue by onmyway133** [Mantle/Mantle#435]
I see that Mantle use `propertyKeys` method to retrieve all properties to NSCoding, what is the best way to filter out this set, just like how we use `NSNull.null` to filter out properties in `JSONKeyPathsByPropertyKey`

**Comment by jspahrsummers** [comment]
Just remove it from the `+propertyKeys` set returned by your superclass.

**Comment by onmyway133** [comment]
@jspahrsummers but that conflicts with `JSONKeyPathsByPropertyKey`

`(id)initWithJSONDictionary:(NSDictionary *)JSONDictionary modelClass:(Class)modelClass error:(NSError **)error`

```
NSSet *propertyKeys = [self.modelClass propertyKeys];
	for (NSString *mappedPropertyKey in self.JSONKeyPathsByPropertyKey) {
		if (![propertyKeys containsObject:mappedPropertyKey]) {
			NSAssert(NO, @"%@ is not a property of %@.", mappedPropertyKey, modelClass);
			return nil;
		}

		id value = self.JSONKeyPathsByPropertyKey[mappedPropertyKey];

		if (![value isKindOfClass:NSString.class] && value != NSNull.null) {
			NSAssert(NO, @"%@ must either map to a JSON key path or NSNull, got: %@.",mappedPropertyKey, value);
			return nil;
		}
	}
```

**Comment by jspahrsummers** [comment]
If you don't want a property to be considered for anything at all, remove it from `+propertyKeys`, and avoid ever mentioning it in `+JSONKeyPathsByPropertyKey`.

**Comment by robb** [comment]
Closing this one for lack of activity, feel free to reopen it if the problem persists. :v:
