### ISSUE TITLE
Override export of enum properties 

### ISSUE THREAD

**Issue by matsoftware** [Mantle/Mantle#436]
Hi, I'm working with the last version of Mantle. I have an enum like this:

typedef enum : NSUInteger {
    GHIssueStateOpen,
    GHIssueStateClosed
} GHIssueState;

and a property @property (nonatomic, assign) GHIssueState state;

When creating a JSON dictionary representation of the object using [MTLJSONAdapter JSONDictionaryFromModel:object] I'd like to export a string mapping to that enum, not the integer value itself (in that case, I would like that the key 'state' will return 'GHIssueStateOpen' string, not the 0 value).

To do this I put a new method in the .m file of my class: 

-(NSString *)getState {
    
    switch (_state) {
        case GHIssueStateOpen:
            return @"GHIssueStateOpen";
            break;
        case GHIssueStateClosed:
            return @"GHIssueStateClosed";
            break;
        default:
            break;
    }
    
}

and it is working fine. The synthesised getter and setter of _state ivar a non overriden and this method is called only when doing the JSONDictionaryFromModel call.

My question is: is this a correct way to accomplish this? Is there some undocumented feature that I can break If I take this approach or is it fine?

Thank you very much in advance.

**Comment by jspahrsummers** [comment]
You should be using a transformer. See the `stateJSONTransformer` [example in the README](https://github.com/Mantle/Mantle/blob/f797bd4837b61d37847a4833024aab268599a681/README.md#mtlmodel).

**Comment by matsoftware** [comment]
Thank you very much, I created a custom propertyJSONTransformer method in the implementation. :)
