### ISSUE TITLE
Compilation error when using cocoapods' new framework system

### ISSUE THREAD

**Issue by hartbit** [Mantle/Mantle#438]
When using the latest version of CocoaPods and using frameworks for compilation, Mantle has compilation errors because of it's umbrella header `Mantle.h`:

```
#import <Mantle/MTLJSONAdapter.h> // include of non-modular header inside framework module 'Mantle.Mantle'
```

I think this can fixed by importing in this way:

```
#import "MTLJSONAdapter.h"
```

I tried forking Mantle to fix it, but can't get Mantle to build, even after updating submodules (compilation error with `Expecta` :cry: )

**Comment by jspahrsummers** [comment]
We don't support CocoaPods usage of Mantle. This is a correct specification of an umbrella header. If there are issues, please consult the CocoaPods folks.
