### ISSUE TITLE
Adding your license to my project

### ISSUE THREAD

**Issue by Czajnikowski** [Mantle/Mantle#439]
Hi,

Thanks for developing such a nice library at first :) I have used it to support my SDK that we are about to release soon. The thing I'm concerned about is licensing. It's a closed source project and at the moment we don't have specific license document, the only one place where we have copyright notices are .h files with something like this:

    //
    //  <Class>.h
    //  <SDKName>
    //
    //  Created by <Author> on <Date>.
    //  Copyright (c) 2015 <Company>. All rights reserved.
    //

I'm wondering if simply adding a line like this to every .h file will satisfy your licensing needs:

    //  This software uses Mantle (https://github.com/Mantle/Mantle/blob/master/LICENSE.md)

I don't know if it matters, but all Mantle symbols are hidden inside the SDK so any Mantle classes and files are not exposed as a public API.

**Comment by jspahrsummers** [comment]
_Ideally,_ we would prefer the attribution somewhere where users can get to it (maybe a Settings view or something).

However, if you're unable or unwilling to do that for whatever reason, it's fine to not have it. You don't need to put attribution in your own source code, as long as Mantle's source tree retains its LICENSE file.

**Comment by Czajnikowski** [comment]
Thanks @jspahrsummers ! As my SDK is not exposing any of Mantle files I will retain the comment in all .h files
