### ISSUE TITLE
How can i get the toJsonString() method?

### ISSUE THREAD

**Issue by jbasttdi** [Mantle/Mantle#441]
thanks for your great work.Now i have 3 model:

'@interface A : Entity
@property(strong,nonatomic) NSString* _id;
@property(strong,nonatomic) NSString* title;
@property(strong,nonatomic) SyncEntity *syncEntity;

@interface SyncEntity:NSObject
@property(strong,nonatomic) NSString* synctitle;
@property(strong,nonatomic) NSString* comments;

@interface Entity:NSObject
@property(strong,nonatomic) NSString* entityKey;
@property(strong,nonatomic) NSString* entityValue;

There are some code like these 
A *a=[[A alloc]init];
a._id=@"id";
a.title=@"title";
a.syncEntity=[[SyncEntity alloc]init];
a.syncEntity.synctitle=@"synctitle";
a.syncEntity.comments=@"comments";
a.entityKey=@"entityKey";
a.entityValue=@"entityValue";'

How can i get the jsonstring of the a object use mantle?

thanks.

**Comment by robb** [comment]
You need to pass your model to `MTLJSONAdapter` and encode the resulting dictionary using `NSJSONSerialization`

**Comment by jbasttdi** [comment]
thanks,i'm a newbie,can give me some code? thanks.

**Comment by jspahrsummers** [comment]
See the README.
