### ISSUE TITLE
`@self` in keypath doesn't work for reverse JSON transforms

### ISSUE THREAD

**Issue by jcayzac** [Mantle/Mantle#442]
Hi,

I have a JSON-serializable model implemented like this:

``` objc
@interface XYZModel : MTLModel <MTLJSONSerializing>
@property (copy, nonatomic, readonly) NSString *foo;
@property (copy, nonatomic, readonly) XYZTimestamps *timestamps;
@property (copy, nonatomic, readonly) XYZName *name;
@end

@implementation XYZModel
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{@"timestamps": @"@self",
             @"name": @"@self",
             @"foo": @"bar",
}
+ (NSValueTransformer *)timestampsJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:XYZTimestamps.class];
}
+ (NSValueTransformer *)nameJSONTransformer {
    return [NSValueTransformer mtl_JSONDictionaryTransformerWithModelClass:XYZName.class];
}
@end
```

It works great for parsing my JSON, which is of the form:

``` json
{
  "lastName":"foo",
  "middleName":"bar",
  "firstName":"baz",
  "foo":"bar",
  "updatedDatetime":"2014-10-15 05:50:35",
  "registeredDatetime":"2014-10-15 05:50:35"
}
```

However, calling `[MTLJSONAdapter JSONDictionaryFromModel:obj]` on my model gives me the following JSON back:

``` json
{
  "@self" : {
    "firstName" : "baz",
    "lastName" : "foo",
    "middleName" : "bar"
  },
  "foo" : "bar"
}
```

…because `MTLJSONAdapter` doesn't check for `@self` and calls `[JSONDictionary setValue:value forKeyPath:JSONKeyPath]` (twice, so the `name` property overwrites the object previously serialized for the `timestamps` property) instead of merging the dictionaries.

Is this intended behavior? What are my options to re-flatten my model when exporting it back to JSON?

**Comment by jspahrsummers** [comment]
It's surprising that `@self` _ever_ worked. I'd consider it a fluke. Everything in the dictionary is supposed to be an actual _key_, not a key path (which are what support the `@` operators).

**Comment by jcayzac** [comment]
Lots of the APIs I hit have highly-redundant response fields. Right now I had to ditch Mantle due to its lack of support for partials. Would be a very welcome addition!

**Comment by jgrandelli** [comment]
In this vain, we have a few places where we use `@self` to pass the entire son payload to a transformer for a property. Is there a newer suggested way of accomplishing this within the model?

**Comment by marcelofabri** [comment]
Maybe [this](https://github.com/Mantle/Mantle/blob/master/CHANGELOG.md#mapping-multiple-json-fields-to-a-single-property) is what want? The original issue is #263.

**Comment by jgrandelli** [comment]
Thanks @marcelofabri. I took a look that for another scenario that is similar. I was wondering if other than listing all the potential keys in an array if it were possible to pass everything. Its looking like that may not be possible anymore.
