### ISSUE TITLE
Swift & Computed Properties with Core Data

### ISSUE THREAD

**Issue by startupthekid** [Mantle/Mantle#444]
I just discovered an interesting bug, not so much one with the framework, more with the nature of Swift. 
I have a bunch of attributes and relationships defined on an `MTLModel` subclass and then some other random properties like an image that I didn't want in my entity. 

In `managedObjectKeysByPropertyKey`, I was returning a mapping of all the entity keys with their corresponding property key and for the properties not defined in CoreData, I gave them a value of `NSNull()`. Everything was working great until I tried converting managed objects I received from a fetch request into models using `MTLManagedObjectAdapter.modelOfClass(modelClass, fromManagedObject: result, error: &error)`. The conversion failed due to illegal property keys. The reason is because one of my non-CoreData properties is a Swift computed property and for some reason isn't picked up in `propertyKeys` (defined in `MTLModel.m`).

The solution was pretty easy, just take the computed property out of the dictionary returned by `managedObjectKeysByPropertyKey`. It looks like computed properties aren't returned from `class_copyPropertyList`. Who'd have thunk?

**Comment by jspahrsummers** [comment]
Thanks for the write-up. I'm a bit confused about what the next steps are, though—are you suggesting that there's something we should fix here?

**Comment by startupthekid** [comment]
Not necessarily, I'm not sure how you would go about detecting computed properties since there's not a backing instance store. Just a friendly warning on the README would be a great start.

**Comment by jspahrsummers** [comment]
`+propertyKeys` is documented to [not return computed properties](https://github.com/Mantle/Mantle/blob/d9dc95002cfbf3929d2b70d2c8a77e6bf5b1b88a/Mantle/MTLModel.h#L45-L47). Were you looking for something more than that?

**Comment by jspahrsummers** [comment]
Core Data support has now moved to [a separate repository](https://github.com/Mantle/MTLManagedObjectAdapter). Please reopen this issue against that repo if you believe it's still valid.
