### ISSUE TITLE
Bad nil representation

### ISSUE THREAD

**Issue by dchohfi** [Mantle/Mantle#445]
Hey guys, I use Mantle on all my projects, and so far it's one of the best libraries out there, because it's easy to use and also easy to customize.

But, I'm working on a project that has the most weird serialization method I've ever seen and I'm trying to migrate that complex and hard to maintain code to use Mantle.

But I'm facing a problem that I don't really know if there is an easy way to fix.

For some reason they decided to change all the null values inside the json for an empty string, yes, an empty string. So, if you are expecting a new object inside a value and that value is null they changed that to return an empty string.

The problem is: if I have an object that has a property of NSDictionary type, and for instance the value inside the json is null, instead of null there is an empty string. I've created a custom json transformer for that property but I want to know if there is a better approach to do this.

My custom transformer looks like:

```objective-c
+ (NSValueTransformer *)optionsJSONTransformer {
    return [MTLValueTransformer reversibleTransformerWithBlock:^id(id value) {
        if ([value isKindOfClass:[NSString class]]) {
            return nil;
        }
        return value;
    }];
}
```

options are a NSDictionary property of my class.

**Comment by jspahrsummers** [comment]
That seems like a fine way to solve the problem.

**Comment by dchohfi** [comment]
But the problem is, I don't really want to repeat this in ALL of my properties, 'cause an empty string can be returned to everything, even arrays, boolean and numbers.. btw, thank you @jspahrsummers

**Comment by robb** [comment]
If you use the `2.0-development` branch, you could subclass `MTLJSONAdapter` and override `+[MTLJSONAdapter transformerForModelPropertiesOfClass:]`

**Comment by robb** [comment]
Closing this one for lack of activity, feel free to reopen it :v:
