### ISSUE TITLE
Using MTLValueTransformer to transform an NSNumber to an int error

### ISSUE THREAD

**Issue by hkellaway** [Mantle/Mantle#448]
I'm using Mantle to successfully transform values in my model - but this one comes back with the error: `Incompatible block pointer types sending 'int (^)(NSNumber *__strong)' to parameter of type 'MTLValueTransformerBlock' (aka 'id (^)(__strong id)')`:

    + (NSValueTransformer *)numDownvotesJSONTransformer
    {
        return [MTLValueTransformer reversibleTransformerWithForwardBlock:^(NSNumber *number) {
            return [number intValue];
        } reverseBlock:^(int value) {
            return [NSNumber numberWithInt:value];
        }];
    }

This similar transform works fine:

    + (NSValueTransformer *)longitudeJSONTransformer
    {
        return [MTLValueTransformer reversibleTransformerWithForwardBlock:^(NSNumber *number) {
            return [NSDecimalNumber decimalNumberWithDecimal:[number decimalValue]];
        } reverseBlock:^(NSDecimalNumber *decimalNumber) {
            return [NSNumber numberWithDouble:[decimalNumber doubleValue]];
        }];
    }

Not understanding the difference here.

**Comment by jspahrsummers** [comment]
Transformers must operate upon objects. You don't need to do anything for an `NSNumber` going to a primitive property, because Key-Value Coding takes care of that automatically.

**Comment by hkellaway** [comment]
Thanks
