### ISSUE TITLE
Same JSONTransformer for multiple properties of the same type

### ISSUE THREAD

**Issue by marcusficner** [Mantle/Mantle#449]
Hey,

is it possible to use the same JSON Transformer for properties of the same type?

i.e. the JSON contains something like this: 

```
{
  "level1": 0
  "level2": 10,
  "level3": 20,
  "level4: 100
}
```

The level* properties should map to the same enum and I'm looking for a way to avoid duplicated code.

**Comment by ikesyo** [comment]
You can use `+JSONTransformerForKey:` in the case (see the [README](https://github.com/Mantle/Mantle#jsontransformerforkey)), like:

```objc
+ (NSValueTransformer *)JSONTransformerForKey:(NSString *)key {
    if ([key hasPrefix:@"level"]) {
        return YOUR_ENUM_TRANSFORMER;
    }

    return nil;
}
```

**Comment by marcusficner** [comment]
Great, thank you @ikesyo!
