### ISSUE TITLE
externalRepresentation not found during migration

### ISSUE THREAD

**Issue by macdrevx** [Mantle/Mantle#450]
I've made some changes to my data model and I'm trying to write a migration by incrementing the value returned by `+modelVersion` and implementing `+dictionaryValueFromArchivedExternalRepresentation:version:`.

I noticed that `+dictionaryValueFromArchivedExternalRepresentation:version:` was not getting called, and it seems like the reason is that at [MTLModel+NSCoding.m:182](https://github.com/Mantle/Mantle/blob/d9dc95002cfbf3929d2b70d2c8a77e6bf5b1b88a/Mantle/MTLModel%2BNSCoding.m#L182) the part that does the calling is skipped due to a nil `externalRepresentation`. `externalRepresentation` is retrieved from the coder on the previous line: `[coder decodeObjectForKey:@"externalRepresentation"]`. I've inspected my archive and can confirm that no such key has been encoded there, nor does an inspection of the Mantle codebase suggest that this key is ever encoded.

The comment on 180 leads me to believe that this mechanism is in place to handle migrations between Mantle versions rather than data model versions (`// Handle the old archive format.`).

Is this correct? If so, what's the recommended approach to handling data model migrations?

I'm using Mantle 1.4.1 via CocoaPods, but it appears as though the behavior is the same in the most recent on master as well.

**Comment by jspahrsummers** [comment]
You should be using [`-decodeValueForKey:withCoder:modelVersion:`](https://github.com/Mantle/Mantle/blob/d9dc95002cfbf3929d2b70d2c8a77e6bf5b1b88a/Mantle/MTLModel%2BNSCoding.h#L99) for migrations if you don't have old archives.

**Comment by macdrevx** [comment]
Perfect. Thanks for the quick answer.

**Comment by jspahrsummers** [comment]
No problem!
