### ISSUE TITLE
Different results of JSONKeyPathsByPropertyKey, based on intended action

### ISSUE THREAD

**Issue by akmarinov** [Mantle/Mantle#453]
Hey,

I was wondering if there's a way to provide different content in JSONKeyPathsByPropertyKey, based on whether it's called in serialization or deserialization?

The issue is that I get a bunch of JSON from a server that looks like

```json
{
  "participant_id": 123,
  "event_code": "A123",
  "dob": "1980-01-01",
  "gender": "M",
  "first_name": "John",
  "last_name": "Doe",
}
```
but then later on I get it from CoreData and have to deserialize it and send it to another service that uses different key paths, like for example

```json
{
  "participantId": 123,
  "eventCode": "A123",
  "dateOfBirth": "1980-01-01",
  "gender": "M",
  "firstName": "John",
  "lastName": "Doe",
}
```
Is there a way to detect whether the data is serializing or deserializing? 
Or some other way that I can include support for multiple keypath mappings?

Thanks!

**Comment by jspahrsummers** [comment]
You could either create your own JSON dictionary in the latter format, or perhaps implement a subclass that sets up different key paths (which you can initialize using the values from the original instance).

**Comment by robb** [comment]
Closing this one for lack of activity, feel free to reopen it if the problem persists. :v:
