### ISSUE TITLE
MTLURLValueTransformerName doesn't work for Url with UTF8 characters.

### ISSUE THREAD

**Issue by haojianzong** [Mantle/Mantle#456]
My url contains spaces, and I use MTLURLValueTransformer as following in my model:

```objc
+ (NSValueTransformer *)orderUrlJSONTransformer {
    return [NSValueTransformer valueTransformerForName:MTLURLValueTransformerName];
}
```

Example of my url: 
https://github.com/myorder/hello hello hello.pdf   (there are spaces between each hello)

But MTLURLValueTransformer will not parse the string into url, instead it returns nil.

I end up writing my own ValueTransformer method as following:

```objc
+ (NSValueTransformer *)orderJSONTransformer {
    return [MTLValueTransformer transformerWithBlock:^(NSString *urlStr) {
        
        NSString *encodedUrlStr = [urlStr stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
        NSURL *url = [NSURL URLWithString:encodedUrlStr];
        return url;
    }];
}
```

Should the MTLURLValueTransformer be modified to support this kind of url? Thanks a lot.

**Comment by robb** [comment]
It's my understanding that spaces aren't valid characters inside a HTTP URL, and I don't think `MTLURLValueTransformer` should try to make any guesses as to what the intention was.

Of course, if you know that the API you're working with is delivering malformed URLs, your approach makes a lot of sense.

**Comment by SoftwareEngieer** [comment]
Thanks for your solution sharing @haojianzong

**Comment by CodeLife2012** [comment]
I agree Robb, this is not a valid URL.
