### ISSUE TITLE
Crash when convert NSString to BOOL

### ISSUE THREAD

**Issue by ivampir** [Mantle/Mantle#466]
I have JSON:

{"name":"Alex","visible":"1"}

My class "RT_Region" have properties:

@property (strong, nonatomic, readonly) NSString *name;
@property (assign, nonatomic, readonly) BOOL visible;

Whan I try to create object:

RT_Region *region = [MTLJSONAdapter modelOfClass:RT_Region.class fromJSONDictionary:regionDict error:&error];

I have crash:

2015-03-06 14:22:47.245 Rostelecom[2617:127109] -[__NSCFString charValue]: unrecognized selector sent to instance 0x7b970c70
2015-03-06 14:22:47.292 Rostelecom[2617:127109] *** Caught exception setting key "visible" : -[__NSCFString charValue]: unrecognized selector sent to instance 0x7b970c70
2015-03-06 14:22:47.372 Rostelecom[2617:127109] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString charValue]: unrecognized selector sent to instance 0x7b970c70'

**Comment by jspahrsummers** [comment]
You need to use a JSON transformer. Mantle does not automatically transform values for you.

**Comment by IIIOS** [comment]
i have this problem too ,how to slove？？？？

**Comment by revolter** [comment]
@jspahrsummers, I have this problem too. I find the `README` not explicit enough, maybe it should include at least an example with a `BOOL` property. Which kind of transformer should I implement, and how? I tried this:

**Comment by conradev** [comment]
@revolter Are you seeing your transformer being called?

**Comment by revolter** [comment]
Yes. I also tried `return [NSValueTransformer valueTransformerForName:MTLBooleanValueTransformerName];` but didn't work, and I finally managed to make it work using:

 	return [NSValueTransformer mtl_valueMappingTransformerWithDictionary:@{
		@"0": @(NO),
		@"1": @(YES)
	}];

**Comment by dcaunt** [comment]
@revolter this is very difficult to diagnose. Can you post your model classes and an example of the JSON?

**Comment by revolter** [comment]
I have the model `User` with:

`User.h`:

	@interface User : MTLModel <MTLJSONSerializing>

	@property (nonatomic, assign) BOOL dirty;

	@end

`User.m`:

	@implementation User

	+ (NSValueTransformer *)dirtyJSONTransformer {

		return [NSValueTransformer valueTransformerForName:MTLBooleanValueTransformerName];
	}

	@end

and I try to create it using:

	NSArray *userResults = [ZeeSQLiteHelper readQueryFromDB:@"SELECT * FROM user"];
	NSMutableDictionary *userResult = userResults.firstObject;

	NSError *error;
	User *user = [MTLJSONAdapter modelOfClass:[User class] fromJSONDictionary:userResult error:&error];

where `userResult` looks like:

	{
		dirty = 1;
	}

and `error` is:

	Error Domain=MTLTransformerErrorHandlingErrorDomain Code=1 "Could not convert number to boolean-backed number or vice-versa" UserInfo={MTLTransformerErrorHandlingInputValueErrorKey=1, NSLocalizedDescription=Could not convert number to boolean-backed number or vice-versa, NSLocalizedFailureReason=Expected an NSNumber, got: 1.}

If I change the `dirtyJSONTransformer` implementation to return:

	[NSValueTransformer mtl_valueMappingTransformerWithDictionary:@{
		@"0": @(NO),
		@"1": @(YES)
	}];

it works.

**Comment by conradev** [comment]
@revolter that is because `MTLBooleanValueTransformerName` converts between two `NSNumbers`, so `@1` to `@YES` and vice versa. That is why the failure reason of the error you received is

```
Expected an NSNumber, got: 1
```

You need a custom transformer, like you built, to go from a string like `@"1"` to `@YES` and vice-versa.

**Comment by revolter** [comment]
@conradev, Well, from the name of it, it sounded like it transform to/from Boolean values... It would be great if the `README` would show examples for booleans too.
