### ISSUE TITLE
MTLManagedObjectAdapter modelOfClass Crashes when Using Inverse Relationship 

### ISSUE THREAD

**Issue by lvandyk** [Mantle/Mantle#471]
I have a core data managed object that I want to edit via a form. So I change its properties and then using MTLManagedObjectAdapter to transform it to a MTLModel to get sent to an API.

It crashes on the modelOfClass call at description method of MTLModel. I did a simple NSLog of self.class and it infinitely loops between the relationship (each class) until I get a EXEC_BAD_ACCESS.

I turned off the inverse relationship and now it works. Any solutions to the problem? I don't want to go removing all the inverse relationships on my models.

My scenario:

SpaceEntity has many Milestone Entities. Milestone entity has one Space Entity. Using modelOfClass on milestone gives me the crash. Both relationships are optional.

Anyone else have the same issue?

**Comment by jspahrsummers** [comment]
Can you please share some real code that demonstrates the issue?

**Comment by lvandyk** [comment]
I tracked it down. Maybe its not inverse relationships. I have the following class:

```
#import <Mantle/Mantle.h>
#import <CoreData/CoreData.h>

@interface Space : MTLModel <MTLJSONSerializing, MTLManagedObjectSerializing>

@property (nonatomic, copy, readonly) NSString* identifier;
@property (nonatomic, copy) NSString* name;
@property (nonatomic, copy, readonly) NSDate* createdAt;
@property (nonatomic, copy, readonly) NSDate* updatedAt;
@property NSSet* tools;
@property NSSet* users;
@property NSSet* wikiPages;
@property NSSet* milestones;

@end
```

If I change the name of milestones property, it works but If I do this then I assume I cannot use relationships with MTL?

**Comment by jspahrsummers** [comment]
@Mantle/core-data Any ideas here?

**Comment by jspahrsummers** [comment]
Core Data support has now moved to [a separate repository](https://github.com/Mantle/MTLManagedObjectAdapter). Please reopen this issue against that repo if you believe it's still valid.
