### ISSUE TITLE
%@ is not a property of %@.

### ISSUE THREAD

**Issue by valeIT** [Mantle/Mantle#476]
[Question on StackOverlow, but since no one answered I figured I might ask here as well.](http://stackoverflow.com/questions/29049892/parsing-json-with-mantle-swift)
I'm using swift, passing a very long JSON with nested objects.

My model class [named: lv2Class]:

        import Foundation

    class lv2Class: MTLJSONSerializing {
        let type: String = ""
        let available: Bool = true
        let kind: String = ""
        let loot: String = ""
        let advanced: Array<lv3Class> = []

            class func advancedJSONTransformer() -> NSValueTransformer {
            return NSValueTransformer.mtl_JSONArrayTransformerWithModelClass(lv3Class.self)
        }

            override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject]!
        {
            return ["type": "Type",
            "available": "Available",
            "kind": "Kind",
            "loot": "Loot",
            "advanced": "Advanced"]
        }
    }

It fails the assertion in MTLJSONAdapter.m [line 149] saying that "propertyKeys" doesn't contain "available", but the property is in the model class and in the JSON.

The value passed for it in the JSON is true/false as bool, but at times it passes it as 1 or 0, so i implemented:

      class func availableJSONTransformer() -> NSValueTransformer {
        return NSValueTransformer.mtl_valueMappingTransformerWithDictionary(
        [
            "true" : true,
            1 : true,
            "1" : true,
            "false" : false,
            0 : false,
            "0" : false
        ])
    }

But the method doesn't even get called ( I set a breakpoint there). 

The problem is not only in this model, but also in some other models, especially when Bools are around, but not always (happened with an Int as well) so I really have no idea where the problem might be, if it's on my hand (I suppose so)...

**Comment by robb** [comment]
If the property is declared using `let`, I would assume it's not a writable property and thus [not picked-up by `propertySet`](https://github.com/Mantle/Mantle/blob/a4a26feb8f90c3a60241ea344839e1cbb2901adf/Mantle/MTLModel.h#L45-L47), can you confirm this?

FWIW, I'm not checking SO for Mantle questions ever and I'm not sure Justin is, I'd recommend filing issues here either way, since this allows us to attach it to the fix if need be.

**Comment by jspahrsummers** [comment]
@robb's intuition is correct. You'll also need the `dynamic` keyword on each of those properties, in order for KVC to work properly.

**Comment by valeIT** [comment]
I tried changing them to var already, before asking the question, but nothing changed - forgot to mention it, sorry. I guess that the problem is that it can't be bridged from swift class to objective C correctly since when i tried to mark them as <code>dynamic</code> it wouldn't let me for that very reason. Problem is with swift Int,Float and Bool.  I changed them to the objective-C / C equivalent and now it works. Oh swift... xD

Thanks guys ;)

**Comment by jshier** [comment]
@valeIT How did you change them to the Objective-C equivalent? Event using something like CInt, I'm still getting a similar error. I know there's ObjCBool, but there don't seem to be any primitive types that work for something like a number. I'm trying Mantle 2 with Swift 2, BTW.

**Comment by valeIT** [comment]
Hey' I'm using mantle 2 with Swift 1.2. I have them as NSInteger, CFloat and ObjCBool and worst case scenario AnyObject xD
