### ISSUE TITLE
property validation methods not documented

### ISSUE THREAD

**Issue by Ashton-W** [Mantle/Mantle#479]
If I'm understanding the tests correctly, if you implement a method matching `- (BOOL)validate<#PropertyName#>:error:` it will be called as part of validation of the object.

See test: [MTLModelValidationSpec.m](https://github.com/Mantle/Mantle/blob/2.0-development/MantleTests/MTLModelValidationSpec.m)

I don't see this mentioned in the README, it is a neat feature!

**Comment by jspahrsummers** [comment]
Mantle is simply using Cocoa's [Key-Value Validation](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/KeyValueCoding/Articles/Validation.html) API, the same way it uses Key-Value Coding.

We could probably document that `-validate:` does this, but the mechanics of implementing per-property validation are best understood from Apple's docs.

**Comment by Ashton-W** [comment]
Thanks, that's about all that would need to be said, including the mention of Cocoa Key-Value Validation.

**Comment by adamkaplan** [comment]
You should also mention that Cocoa's Key-Value Validation is hideously slow and does _absolutely nothing_ by default.

The default implementation of this method searches the receiver for a validation methods via slow reflection. If such a method is found it is invoked and the result is returned. If no such method is found, YES is returned and much time is wasted.

In performance critical paths, users might see a win by just overriding the validation method and just returning YES...
