### ISSUE TITLE
how to do about the jsonString like this

### ISSUE THREAD

**Issue by perfectChao** [Mantle/Mantle#482]
the json string like blow , which the imgPaths contain the NSString type,  how to do about this?

```json
{
    "userid": "9", 
    "username": "jack", 
    "imgPaths": [
        "http://xxxx1.png", 
        "http://xxxx2.png", 
        "http://xxxx3.png"
    ]
}
```

**Comment by robb** [comment]
Have you tried using a value transformer?

**Comment by perfectChao** [comment]
robb: Yes, but the imagePath like "http://xxxxx1.png" is not a MTLModel

**Comment by robb** [comment]
You could convert the `imgPaths` array to an array of `NSURL`s by using

```objc
[NSValueTransformer mtl_arrayMappingTransformerWithTransformer:[NSValueTransformer valueTransformerForName:MTLURLValueTransformerName]]
```

or something to that extend.

**Comment by perfectChao** [comment]
http://stackoverflow.com/questions/23268124/transform-nsstring-to-nsurl-within-a-json-array-with-mantle
thank you for robb , my mantle version is 1.x so i didn't find this interface, it is in version 2.x, i have get the answer above the url

**Comment by robb** [comment]
I would recommend going with 2.0 at this point, it's pretty stable and migration shouldn't be difficult (unless you use CoreData).
