### ISSUE TITLE
Handling non existing keys

### ISSUE THREAD

**Issue by eridbardhaj** [Mantle/Mantle#483]
Hey guys this library is doing just great for me, but I have a question related to non existing keys in a JSON File when I have mapped them under `JSONKeyPathsByPropertyKey`. 

Lets say I have mapped **@"someProperty": @"someKey"**, now its supposed that value this property is nil (and it is nil indeed), but I want to transform it under `JSONTransformerForKey` by this code 

```
    if ([key isEqualToString:@"someProperty"])
    {
        return [MTLValueTransformer reversibleTransformerWithBlock:^id(id object)
                {
                    return @"";
                }];
    }
```

But this code is not even being called.

So my question is, how to transform a **nil value** that is not present in a JSON File but is being mapped under `JSONKeyPathsByPropertyKey`?

**Comment by robb** [comment]
If the value is not present in the JSON dictionary, the transformer will not be invoked by the adapter. (If the value is `NSNull.null`, that is a different matter.)

Instead, you can set a default value by overriding `-init` and assinging `@""` to `someProperty`.

**Comment by dcaunt** [comment]
[Here is some example code](http://stackoverflow.com/a/27504488/80425) implementing Robb's suggestion

**Comment by eridbardhaj** [comment]
@robb Thank you for your clarification, I am interested also for NSNull.null, if you have a guide link or issue can you provide it to me please.
@dcaunt  thank you too, but my issue is related also with unstable API which sometimes returns specific keys and sometimes it doesn't.

**Comment by robb** [comment]
If the value is `NSNull.null`, your value transformer should be invoked. It could be that there is a typo in the property key somewhere, but it's hard to tell without seeing your actual code.
