### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=3840

### ISSUE THREAD

**Issue by owenwillis** [Mantle/Mantle#484]
I began using Mantle 1.3 as part of the Objective C best practices Weather App that was published a while ago. For that, we were using the OpenWeather API. I've been frustrated with the quality of the data I've been getting from them and am trying to switch to the Wunderground API. Every time I run the app, however, I get the following error:

Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (JSON text did not start with array or object and option to allow fragments not set.) UserInfo=0x7f9c93d30350 {NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

This doesn't make sense to me because when I run the request on a browser, the JSON text is appearing. Any help is greatly appreciated, and if you need to see any of my code, just let me know.

Best,

Owen

**Comment by jspahrsummers** [comment]
That error means that the top-level JSON object is not an array or (JSON) object. For example, JSON text that is only `null`, a number, or a string is not a valid API response.

If that's the only choice you have with the API, you can try wrapping it in an `NSArray` or `NSDictionary` before giving it to Mantle.

**Comment by owenwillis** [comment]
That makes sense. At what point in the code would I wrap it?

Here is my code, as is. After reading a couple of similar issues on StackOverflow, I added in NSJSONReadingAllowFragments to NSJSONSerialization under options. It's now spitting back a different error: Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (Invalid value around character 1.) UserInfo=0x7fbc4bd1d750 {NSDebugDescription=Invalid value around character 1.}

Code Below:
```
#pragma fetching JSON data
-(RACSignal *)fetchJSONFromURL:(NSURL *)url{
    NSLog(@"Fetching: %@", url.absoluteString);
     
    return [[RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        NSURLSessionDataTask *dataTask = [self.session dataTaskWithURL:url completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
            if (! error){
                NSError *jsonError = nil;
                id json = [NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingAllowFragments error:&jsonError];
                if (! jsonError){
                    [subscriber sendNext:json];
                }
                else{
                    [subscriber sendError:jsonError];
                }
            }
            else{
                [subscriber sendError:error];
            }
            [subscriber sendCompleted];
        }];
        [dataTask resume];
        return [RACDisposable disposableWithBlock:^{if(dataTask.state == NSURLSessionTaskStateRunning || dataTask.state == NSURLSessionTaskStateSuspended) {
            [dataTask cancel];
        };
                }];
    }]
    doError:^(NSError *error){
        NSLog(@"%@", error);
    }];
}


#pragma fetching current conditions

- (RACSignal *)fetchCurrentConditionsForLocation:(CLLocationCoordinate2D)coordinate {
    PFUser *User = [PFUser currentUser];
    
    _coordinatesLabel = User[@"location"];
    
    
    
    NSLog (@"client.coordinatesLabel = %@", _coordinatesLabel);
   
    
    if (_coordinatesLabel.length  > 0){
        
        NSString *urlString = [NSString stringWithFormat:@"http://api.wunderground.com/api/1b25ded6c196ee9f/conditions/q/%@.json", _coordinatesLabel];
       
        NSURL *url = [NSURL URLWithString:urlString];
        
        return [[self fetchJSONFromURL:url] map:^(NSDictionary *json) {
            
            return [MTLJSONAdapter modelOfClass:[WVNCondition class] fromJSONDictionary:json error:nil];

        }];
        
    }
    else{
    
    NSString *urlString = [NSString stringWithFormat:@"http://api.wunderground.com/api/1b25ded6c196ee9f/conditions/q/%f,%f.json",coordinate.latitude, coordinate.longitude];
    NSURL *url = [NSURL URLWithString:urlString];
    return [[self fetchJSONFromURL:url] map:^(NSDictionary *json) {
        return [MTLJSONAdapter modelOfClass:[WVNCondition class] fromJSONDictionary:json error:nil];
    }];
    }
}

- (RACSignal *)fetchHourlyForecastForLocation:(CLLocationCoordinate2D)coordinate {
    NSString *urlString = [NSString stringWithFormat:@"http://api.wunderground.com/data/api/1b25ded6c196ee9f/hourly/q/%f,%f.json",coordinate.latitude, coordinate.longitude];
    NSURL *url = [NSURL URLWithString:urlString];
    return [[self fetchJSONFromURL:url] map:^(NSDictionary *json) {
    RACSequence *list = [json[@"list"] rac_sequence];
    return [[list map:^(NSDictionary *item) {
    return [MTLJSONAdapter modelOfClass:[WVNCondition class] fromJSONDictionary:item error:nil];
        }] array];
    }];
}

- (RACSignal *)fetchDailyForecastForLocation:(CLLocationCoordinate2D)coordinate {
    
    if (_coordinatesLabel.length  > 0){
        
        NSString *urlString = [NSString stringWithFormat:@"http://api.wunderground.com/api/1b25ded6c196ee9f/forecast/q/%@.json", _coordinatesLabel];
        NSURL *url = [NSURL URLWithString:urlString];
    
        return [[self fetchJSONFromURL:url] map:^(NSDictionary *json) {
            
            RACSequence *list = [json[@"list"] rac_sequence];
            
            return [[list map:^(NSDictionary *item) {
                return [MTLJSONAdapter modelOfClass:[WVNDailyForecast class] fromJSONDictionary:item error:nil];
            }] array];
        }];
        
    } else{
    
    NSString *urlString = [NSString stringWithFormat:@"http://api.wunderground.com/api/1b25ded6c196ee9f/forecast/q/%f,%f.json",coordinate.latitude, coordinate.longitude];
        NSURL *url = [NSURL URLWithString:urlString];
        
        return [[self fetchJSONFromURL:url] map:^(NSDictionary *json) {
            
            RACSequence *list = [json[@"list"] rac_sequence];
            
            return [[list map:^(NSDictionary *item) {
                return [MTLJSONAdapter modelOfClass:[WVNDailyForecast class] fromJSONDictionary:item error:nil];
            }] array];
        }];
    }
}
```

**Comment by jspahrsummers** [comment]
Can you share the actual JSON you're using?

**Comment by owenwillis** [comment]
So I was able to solve this issue! After looking back at my code, I realized that I never took out the data transforming in my '''MTLModel'''. The issue I'm having right now though is with this piece of JSON:

'''
{
  "response": {
    "version": "0.1",
    "termsofService": "http://www.wunderground.com/weather/api/d/terms.html",
    "features": {
      "forecast": 1
    }
  },
  "forecast": {
    "txt_forecast": {
      "date": "9:41 AM EDT",
      "forecastday": [
        {
          "period": 0,
          "icon": "clear",
          "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
          "title": "Wednesday",
          "fcttext": "Sunny. High 61F. Winds NW at 5 to 10 mph.",
          "fcttext_metric": "Sunny. High 16C. Winds NW at 10 to 15 km/h.",
          "pop": "0"
        },
        {
          "period": 1,
          "icon": "nt_clear",
          "icon_url": "http://icons.wxug.com/i/c/k/nt_clear.gif",
          "title": "Wednesday Night",
          "fcttext": "Clear skies. Low 41F. Winds light and variable.",
          "fcttext_metric": "Clear skies. Low 4C. Winds light and variable.",
          "pop": "0"
        },
        {
          "period": 2,
          "icon": "clear",
          "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
          "title": "Thursday",
          "fcttext": "Generally sunny despite a few afternoon clouds. High 71F. Winds SSW at 15 to 25 mph.",
          "fcttext_metric": "Sunshine and some clouds. High 22C. Winds SSW at 25 to 40 km/h.",
          "pop": "0"
        },
        {
          "period": 3,
          "icon": "nt_chancerain",
          "icon_url": "http://icons.wxug.com/i/c/k/nt_chancerain.gif",
          "title": "Thursday Night",
          "fcttext": "Partly cloudy in the evening. Increasing clouds with periods of showers after midnight. Low near 60F. Winds SSW at 10 to 20 mph. Chance of rain 60%.",
          "fcttext_metric": "Partly cloudy skies early followed by increasing clouds with showers developing later at night. Low around 15C. Winds SSW at 15 to 30 km/h. Chance of rain 60%.",
          "pop": "60"
        },
        {
          "period": 4,
          "icon": "chancetstorms",
          "icon_url": "http://icons.wxug.com/i/c/k/chancetstorms.gif",
          "title": "Friday",
          "fcttext": "Scattered showers and thunderstorms. High 79F. Winds SW at 15 to 25 mph. Chance of rain 60%.",
          "fcttext_metric": "Scattered thunderstorms. High 26C. Winds SW at 15 to 30 km/h. Chance of rain 60%.",
          "pop": "60"
        },
        {
          "period": 5,
          "icon": "nt_chancetstorms",
          "icon_url": "http://icons.wxug.com/i/c/k/nt_chancetstorms.gif",
          "title": "Friday Night",
          "fcttext": "Scattered thunderstorms during the evening, then windy overnight with occasional showers. Low around 55F. SW winds at 10 to 15 mph, increasing to 20 to 30 mph. Chance of rain 60%.",
          "fcttext_metric": "Scattered thunderstorms during the evening, then windy overnight with occasional showers. Low 12C. SW winds at 10 to 15 km/h, increasing to 30 to 50 km/h. Chance of rain 60%.",
          "pop": "60"
        },
        {
          "period": 6,
          "icon": "partlycloudy",
          "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          "title": "Saturday",
          "fcttext": "Sun and a few clouds with gusty winds. High 56F. Winds NW at 25 to 35 mph.",
          "fcttext_metric": "Sun and a few clouds with gusty winds. High 13C. Winds NW at 30 to 50 km/h.",
          "pop": "10"
        },
        {
          "period": 7,
          "icon": "nt_clear",
          "icon_url": "http://icons.wxug.com/i/c/k/nt_clear.gif",
          "title": "Saturday Night",
          "fcttext": "Clear skies. Low 39F. Winds W at 10 to 15 mph.",
          "fcttext_metric": "Clear skies. Low 3C. Winds W at 15 to 25 km/h.",
          "pop": "0"
        }
      ]
    },
    "simpleforecast": {
      "forecastday": [
        {
          "date": {
            "epoch": "1427929200",
            "pretty": "7:00 PM EDT on April 01, 2015",
            "day": 1,
            "month": 4,
            "year": 2015,
            "yday": 90,
            "hour": 19,
            "min": "00",
            "sec": 0,
            "isdst": "1",
            "monthname": "April",
            "monthname_short": "Apr",
            "weekday_short": "Wed",
            "weekday": "Wednesday",
            "ampm": "PM",
            "tz_short": "EDT",
            "tz_long": "America/New_York"
          },
          "period": 1,
          "high": {
            "fahrenheit": "61",
            "celsius": "16"
          },
          "low": {
            "fahrenheit": "41",
            "celsius": "5"
          },
          "conditions": "Clear",
          "icon": "clear",
          "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
          "skyicon": "",
          "pop": 0,
          "qpf_allday": {
            "in": 0.00,
            "mm": 0
          },
          "qpf_day": {
            "in": 0.00,
            "mm": 0
          },
          "qpf_night": {
            "in": 0.00,
            "mm": 0
          },
          "snow_allday": {
            "in": 0.0,
            "cm": 0.0
          },
          "snow_day": {
            "in": 0.0,
            "cm": 0.0
          },
          "snow_night": {
            "in": 0.0,
            "cm": 0.0
          },
          "maxwind": {
            "mph": 10,
            "kph": 16,
            "dir": "NW",
            "degrees": 320
          },
          "avewind": {
            "mph": 9,
            "kph": 14,
            "dir": "NW",
            "degrees": 320
          },
          "avehumidity": 32,
          "maxhumidity": 0,
          "minhumidity": 0
        },
        {
          "date": {
            "epoch": "1428015600",
            "pretty": "7:00 PM EDT on April 02, 2015",
            "day": 2,
            "month": 4,
            "year": 2015,
            "yday": 91,
            "hour": 19,
            "min": "00",
            "sec": 0,
            "isdst": "1",
            "monthname": "April",
            "monthname_short": "Apr",
            "weekday_short": "Thu",
            "weekday": "Thursday",
            "ampm": "PM",
            "tz_short": "EDT",
            "tz_long": "America/New_York"
          },
          "period": 2,
          "high": {
            "fahrenheit": "71",
            "celsius": "22"
          },
          "low": {
            "fahrenheit": "60",
            "celsius": "16"
          },
          "conditions": "Clear",
          "icon": "clear",
          "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
          "skyicon": "",
          "pop": 0,
          "qpf_allday": {
            "in": 0.04,
            "mm": 1
          },
          "qpf_day": {
            "in": 0.00,
            "mm": 0
          },
          "qpf_night": {
            "in": 0.04,
            "mm": 1
          },
          "snow_allday": {
            "in": 0.0,
            "cm": 0.0
          },
          "snow_day": {
            "in": 0.0,
            "cm": 0.0
          },
          "snow_night": {
            "in": 0.0,
            "cm": 0.0
          },
          "maxwind": {
            "mph": 25,
            "kph": 40,
            "dir": "SSW",
            "degrees": 192
          },
          "avewind": {
            "mph": 19,
            "kph": 31,
            "dir": "SSW",
            "degrees": 192
          },
          "avehumidity": 41,
          "maxhumidity": 0,
          "minhumidity": 0
        },
        {
          "date": {
            "epoch": "1428102000",
            "pretty": "7:00 PM EDT on April 03, 2015",
            "day": 3,
            "month": 4,
            "year": 2015,
            "yday": 92,
            "hour": 19,
            "min": "00",
            "sec": 0,
            "isdst": "1",
            "monthname": "April",
            "monthname_short": "Apr",
            "weekday_short": "Fri",
            "weekday": "Friday",
            "ampm": "PM",
            "tz_short": "EDT",
            "tz_long": "America/New_York"
          },
          "period": 3,
          "high": {
            "fahrenheit": "79",
            "celsius": "26"
          },
          "low": {
            "fahrenheit": "55",
            "celsius": "13"
          },
          "conditions": "Chance of a Thunderstorm",
          "icon": "chancetstorms",
          "icon_url": "http://icons.wxug.com/i/c/k/chancetstorms.gif",
          "skyicon": "",
          "pop": 60,
          "qpf_allday": {
            "in": 0.31,
            "mm": 8
          },
          "qpf_day": {
            "in": 0.16,
            "mm": 4
          },
          "qpf_night": {
            "in": 0.15,
            "mm": 4
          },
          "snow_allday": {
            "in": 0.0,
            "cm": 0.0
          },
          "snow_day": {
            "in": 0.0,
            "cm": 0.0
          },
          "snow_night": {
            "in": 0.0,
            "cm": 0.0
          },
          "maxwind": {
            "mph": 25,
            "kph": 40,
            "dir": "SW",
            "degrees": 216
          },
          "avewind": {
            "mph": 17,
            "kph": 27,
            "dir": "SW",
            "degrees": 216
          },
          "avehumidity": 60,
          "maxhumidity": 0,
          "minhumidity": 0
        },
        {
          "date": {
            "epoch": "1428188400",
            "pretty": "7:00 PM EDT on April 04, 2015",
            "day": 4,
            "month": 4,
            "year": 2015,
            "yday": 93,
            "hour": 19,
            "min": "00",
            "sec": 0,
            "isdst": "1",
            "monthname": "April",
            "monthname_short": "Apr",
            "weekday_short": "Sat",
            "weekday": "Saturday",
            "ampm": "PM",
            "tz_short": "EDT",
            "tz_long": "America/New_York"
          },
          "period": 4,
          "high": {
            "fahrenheit": "56",
            "celsius": "13"
          },
          "low": {
            "fahrenheit": "39",
            "celsius": "4"
          },
          "conditions": "Partly Cloudy",
          "icon": "partlycloudy",
          "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
          "skyicon": "",
          "pop": 10,
          "qpf_allday": {
            "in": 0.00,
            "mm": 0
          },
          "qpf_day": {
            "in": 0.00,
            "mm": 0
          },
          "qpf_night": {
            "in": 0.00,
            "mm": 0
          },
          "snow_allday": {
            "in": 0.0,
            "cm": 0.0
          },
          "snow_day": {
            "in": 0.0,
            "cm": 0.0
          },
          "snow_night": {
            "in": 0.0,
            "cm": 0.0
          },
          "maxwind": {
            "mph": 35,
            "kph": 56,
            "dir": "NW",
            "degrees": 312
          },
          "avewind": {
            "mph": 25,
            "kph": 40,
            "dir": "NW",
            "degrees": 312
          },
          "avehumidity": 41,
          "maxhumidity": 0,
          "minhumidity": 0
        }
      ]
    }
  }
}
'''

I'm trying to access the data in the  ''' simpleforecast.forecastday''' array (the high and low temperature particularly), but everything I've done is just pulling in null values.

Thanks for all of your help!

**Comment by jspahrsummers** [comment]
Can you please include the code you're using in your `MTLModel` to parse that JSON?

**Comment by owenwillis** [comment]
Sure!
```
#import "Mantle.h"


@interface WVNCondition : MTLModel <MTLJSONSerializing>

@property(nonatomic) NSDate *date;
@property(nonatomic) NSString *weekday;
@property(nonatomic) NSNumber *humidity;
@property(nonatomic) NSNumber *temperature;
@property(nonatomic) NSNumber *tempHigh;
@property(nonatomic) NSNumber *tempLow;
@property(nonatomic) NSString *locationName;
@property(nonatomic) NSString *conditionDescription;
@property(nonatomic) NSString *condition;
@property(nonatomic) NSNumber *windBearing;
@property(nonatomic) NSNumber *windSpeed;
@property(nonatomic) NSString *icon;
@property(nonatomic) NSString *report;
@property(nonatomic) NSArray *dailyForecast;

-(NSString *)imageName;

@end
```

```
#import "WVNCondition.h"

@implementation WVNCondition

#pragma weather images

+(NSDictionary *)imageMap{
    static NSDictionary *_imageMap = nil;
    
    if (! _imageMap){
        
        _imageMap = @{       @"clear" : @"weather-clear",
                             @"mostlysunny" : @"weather-few",
                             @"partlysunny" : @"weather-few",
                             @"partlycloudy" : @"weather-few",
                             @"mostlycloudy" : @"weather-broken",
                             @"chancerain" : @"weather-shower",
                             @"rain" : @"weather-rain",
                             @"tstorms" : @"weather-tstorm",
                             @"snow" : @"weather-snow",
                             @"hazy" : @"weather-mist",
                             @"nt_clear" : @"weather-moon",
                             @"nt_mostlysunny" : @"weather-few-night",
                             @"nt_partyly cloudy" : @"weather-few-night",
                             @"cloudy" : @"weather-broken",
                             @"rain" : @"weather-shower",
                             @"nt_rain" : @"weather-rain-night",
                             @"chancetstorms" : @"weather-tstorm",
                             @"flurries" : @"weather-snow",
                             @"fog" : @"weather-mist",
                             };
    }
    return _imageMap;
}

-(NSString *)imageName{
    return [WVNCondition imageMap][self.icon];   
}

#pragma API key dictionary

+(NSDictionary *)JSONKeyPathsByPropertyKey{
    return @{
             @"locationName": @"current_observation.display_location.city",
             @"humidity": @"current_observation.relative_humidity",
             @"temperature": @"current_observation.temp_f",
             @"condition": @"current_observation.weather",
             @"tempLow": @" ",
             @"tempHigh": @" ",
             @"icon": @"current_observation.icon",
             @"windBearing": @"current_observation.wind_dir",
             @"windSpeed": @"current_observation.wind_mph"
             };
    
}
```

```
#import "WVNCondition.h"
#import "WVNForecasts.h"


@interface WVNDailyForecast : WVNCondition

@end
```
```
#import "WVNDailyForecast.h"

@implementation WVNDailyForecast

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"dailyForecast": @"simpleforecast.forecastday"
             };
}

+ (NSValueTransformer *)dailyforecastJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:WVNForecasts.class];
}
@end
```
```
#import <Foundation/Foundation.h>
#import "Mantle.h"
#import "WVNDailyForecast.h"
#import "WVNCondition.h"

@interface WVNForecasts : MTLModel <MTLJSONSerializing>

@property(nonatomic, copy) NSString *weekday;
@property(nonatomic, copy) NSNumber *humidity;
@property(nonatomic, copy) NSNumber *tempHigh;
@property(nonatomic, copy)NSNumber *tempLow;
@property(nonatomic, copy)NSString *condition;
@property(nonatomic, copy)NSNumber *windSpeed;
@property(nonatomic, copy) NSString *icon;
@property(nonatomic, copy) NSString *report;
@end
```

```
#import "WVNForecasts.h"

@implementation WVNForecasts

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"condition" : @"period.conditions",
             @"tempHigh" : @"period.high.fahrenheit",
             @"tempLow" : @"period.low.fahrenheit",
             @"windSpeed" : @"period.avewind.mph",
             @"icon" : @"period.icon",
             @"weekday" : @"date.weekday",
             @"humidity" : @"period.avehumidity",
             
             };
}
@end
```

**Comment by owenwillis** [comment]
So just to clarify my code, WVNCondition handles the current conditions API, while WVNDailyForecast handles the 3-day forecast. Since many of the fields are the same, WVNDailyForecast is meant to override WVN Condition for the fields that are used. This worked with the OpenWeather API, which didn't have any nested data in the 3-day forecast, but I'm struggling to make it work with the above JSON.

Thanks again,

Owen

**Comment by owenwillis** [comment]
Here is a different ```WVNDailyForecast``` configuration that I also tried:

```
#import "WVNDailyForecast.h"

@implementation WVNDailyForecast

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    NSMutableDictionary *paths = [[super JSONKeyPathsByPropertyKey]mutableCopy];
    
    paths[@"condition"] = @"forecast.simpleforecast.forecastday.conditions";
    paths[@"tempHigh"] = @"forecast.simpleforecast.forecastday.high.fahrenheit";
    paths[@"tempLow"] = @"forecast.simpleforecast.forecastday.low.fahrenheit";
    paths[@"humidity"] = @"forecast.simpleforecast.forecastday.avehumidity";
    paths[@"icon"] = @"forecast.simpleforecast.forecastday.icon";
    
    paths[@"windSpeed"] = @"forecast.simpleforecast.forecastday.avewind.mph";
             
    return paths;

}

//+ (NSValueTransformer *)dailyforecastJSONTransformer {
   // return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:WVNForecasts.class];
//}//

+(NSValueTransformer *)conditionJSONTransformer{
    return [MTLValueTransformer reversibleTransformerWithForwardBlock:^(NSArray *values){
        return [values firstObject];} reverseBlock:^(NSString *str){
        return@[str];
    }];
}

+(NSValueTransformer *)tempLowJSONTransformer{
    return [self conditionJSONTransformer];
}

+(NSValueTransformer *)humidityJSONTransformer{
    return [self conditionJSONTransformer];
}

+(NSValueTransformer *)windSpeedJSONTransformer{
    return [self conditionJSONTransformer];
}

+(NSValueTransformer *)iconJSONTransformer{
    return [self conditionJSONTransformer];
}

@end
```

**Comment by owenwillis** [comment]
I was able to resolve the issue! There was a problem with the JSON file when i converted it to an array. I turned ```WVNDailyForecast``` into it's own ```MTLModel``` and now everything is working fine (including the JSONTransformers). I'm not sure why it was happening, but the JSON file is sort of strange, so that might have been causing it. Thanks for your help!

**Comment by robb** [comment]
:ok_hand:

**Comment by 788zhang** [comment]
I  also  meet same program ,but I can't solve this .
