### ISSUE TITLE
enhancement suggestion : valueTransformer for property type

### ISSUE THREAD

**Issue by GreatWiz** [Mantle/Mantle#485]
It's possible to map the same valueTransformer to multiple properties programmatically by overriding  ` valueTransformerForKeyPath `, but it could be cleaner to be able to define a valueTransfomer for a type (or class), across the app (as part of the MTLModel hierarchy, or in the JSONAdapter which seems to fit the 2.0 design ). This mapping can then be used when there is no custom ` propertyNameValueTransfomer ` selector when deserializing JSON objects.
Many properties, such as custom objects (e.g. Person) or UIKit objects (e.g. UIColor) will probably be always mapped to the same type of json object/field. Therefore I think that being able to map a type to a valueTransformer would clean up a lot of the boiler plate code. 

If you like the idea, I can work on a pull request with this for 2.0 .

**Comment by robb** [comment]
Thanks for the suggestion! :sparkling_heart: 

You can already do this by subclassing `MTLJSONAdapter` and overriding `-transformerForModelPropertiesOfClass:` or `-transformerForModelPropertiesOfObjCType:` :sparkles:

**Comment by GreatWiz** [comment]
oops, I guess I should have examined 2.0 more carefully. 😳 
Great job, it's a really useful feature :)
