### ISSUE TITLE
Ambiguous expansion of macro 'weakify'

### ISSUE THREAD

**Issue by antrix1989** [Mantle/Mantle#488]
If you use ReactiveCocoa and Mantle as modules, you will get "Ambiguous expansion of macro 'weakify'" warning. It is because this macros is defined in both libraries. Perhaps they should be wrapped into:

```
#ifndef
...
#endif
````
Example project: https://www.dropbox.com/s/6ddusry7hlb9unr/test.zip?dl=0

**Comment by jspahrsummers** [comment]
Mantle does not export `@strongify` and `@weakify`. If you're seeing collisions, it's probably via CocoaPods or something.

**Comment by jshier** [comment]
I think if whoever is the unofficial podspec maintainer for Mantle could add EXTScope.h to the private headers it would fix this issue.

**Comment by dcaunt** [comment]
This should now be resolved by CocoaPods/Specs#13115 for those integrating 2.0

**Comment by robb** [comment]
Closing this one for lack of activity, feel free to reopen it if the problem persists. :v:
