### ISSUE TITLE
Can I use mantle 2.0 in iOS 7

### ISSUE THREAD

**Issue by foobra** [Mantle/Mantle#490]
I don't need swift or dynamic framework support. Can I use it in iOS7 directly?

**Comment by jspahrsummers** [comment]
Such usage isn't supported (and so we may not be able to help resolve issues with it), but should theoretically work.

**Comment by dcaunt** [comment]
As far as I could see, there are no code changes that increased the iOS or OS X version requirements for Mantle from version 1 to 2. 

I know that CocoaPods isn't a supported installation method, but I have not heard of any problems with the [podspec for 2.0](https://github.com/CocoaPods/Specs/blob/master/Specs/Mantle/2.0/Mantle.podspec.json) in trunk.
