### ISSUE TITLE
Implementing MTLModel shows error parsing JSON dictionary

### ISSUE THREAD

**Issue by quantumpotato** [Mantle/Mantle#491]
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Channel 0x7fb34b5d1420> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key user.'
            
                NSDictionary *json = @{@"u1" : @{@"handle" : @"h1", @"authToken" : @"123"}};
                NSError *e = nil;
                Channel *c = [[Channel alloc] initWithDictionary:json error:&e];
                NSLog(@"channel.u1.handle: %@", c.u1.handle);
            
            Channel.m:
            
                + (NSDictionary *)JSONKeyPathsByPropertyKey {
                    return @{
                             @"u1" : @"u1"
                             };
                }
                
        + (NSValueTransformer *)u1Transformer {
            return [MTLJSONAdapter dictionaryTransformerWithModelClass:[User class]];
        }
    
        
        User.m:
        
        + (NSDictionary *)JSONKeyPathsByPropertyKey {
            return @{
                     @"handle" : @"handle",
                     @"authToken" : @"token"
                     };
        }
    
    
    Using [Mantle, iOS json parsing framework][1].
    
    How do I parse my JSON into cocoa objects?
    
    
      [1]: https://github.com/Mantle/Mantle

from http://stackoverflow.com/questions/29572536/implementing-mtlmodel-shows-error-parsing-json-dictionary

**Comment by robb** [comment]
It looks like `Channel` is not key value coding-compliant for the key `user`. Does it have a property like that?

**Comment by quantumpotato** [comment]
It has User *u1 and User *u2 . The JSON mapping shows the same.

**Comment by robb** [comment]
Oh, nevermind. You need to use `MTLJSONAdapter` to create your model, *not* `-initWithDictionary:error:` as you are doing in:

```objc
[[Channel alloc] initWithDictionary:json error:&e];
```

**Comment by quantumpotato** [comment]
Channel inherits from MTLModel, how do I use MTLJSONAdapter to create Channel?

**Comment by robb** [comment]
Yup.

**Comment by quantumpotato** [comment]
```
    NSDictionary *json = @{@"user" : @{@"handle" : @"h1", @"authToken" : @"123"}};
    NSError *e = nil;
    
    Channel *c = [MTLJSONAdapter modelOfClass:[Channel class] fromJSONDictionary:json error:&e];
    NSLog(@"channel.u1.handle: %@", c.u1.handle);


 *** Assertion failure in -[MTLJSONAdapter initWithModelClass:], /Users/quantum/sonar/client/Pods/Mantle/Mantle/MTLJSONAdapter.m:136
2015-04-12 09:01:01.068 Sonar[933:9988] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [modelClass conformsToProtocol:@protocol(MTLJSONSerializing)]'

@interface Channel : MTLModel <MTLJSONSerializing>

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"u1" : @"user"
             };
}

```

**Comment by robb** [comment]
Does `modelClass` conform to the `MTLJSONSerializing` protocol?

**Comment by quantumpotato** [comment]
@robb see above post with the Channel interface and its implementation of `MTLJSONSerializing` protocol with `JSONKeyPathsByPropertyKey`. That's the only required method.

**Comment by robb** [comment]
It's really hard to figure out what's going on there. I would suggest using the debugger to see where this dictionary gets passed in, but it's not really something we can do for you.

**Comment by quantumpotato** [comment]
@robb the dictionary is passed in from the line before. Here's the issue:

    NSDictionary *json = @{@"user" : @{@"handle" : @"h1", @"authToken" : @"123"}};
    NSError *e = nil;
    
    Channel *c = [MTLJSONAdapter modelOfClass:[Channel class] fromJSONDictionary:json error:&e];
    NSLog(@"channel.u1.handle: %@", c.u1.handle);
  
Channel is created successfully. I can `po c.u1` and get

```
po c.u1
{
    authToken = 123;
    handle = h1;
}
```

but the u1 is a dictionary instead of a User model. Hence why `po c.u1.handle` excepts with no method  `handle` for `NSDictionary`.

In Channel.m I implement

```
+ (NSValueTransformer *)u1Transformer {
    return [MTLJSONAdapter dictionaryTransformerWithModelClass:[User class]];
}
```

which should, if I understand Mantle's spec correctly, populate the property `u1` on Channel with a `User` object. Instead `u1` gets populated with an NSDictionary.

**Comment by robb** [comment]
That needs to be [`+ u1JSONTransformer`](https://github.com/Mantle/Mantle#jsontransformerforkey), you should be able to verify with a breakpoint that `u1Transformer` is never invoked.

**Comment by quantumpotato** [comment]
Doh, thanks @robb !
