### ISSUE TITLE
Integer values in model not working

### ISSUE THREAD

**Issue by pilot34** [Mantle/Mantle#492]
I have such model class
```objective-c
@interface GiphyImage : MTLModel<MTLJSONSerializing>

@property (strong, nonatomic, readonly) NSString *url;

@property (nonatomic, readonly) NSInteger height;
@property (nonatomic, readonly) NSInteger width;
@property (nonatomic, readonly) NSInteger size;

@end
```

Parsing json with numbers in height, width, size returning error:

**Error Domain=MTLTransformerErrorHandlingErrorDomain Code=1 "Value did not match expected type" UserInfo=0x7feef266f0d0 {MTLTransformerErrorHandlingInputValueErrorKey=349291, NSLocalizedDescription=Value did not match expected type, NSLocalizedFailureReason=Expected 349291 to be of class NSValue}**

If I add such simple ValueTransformer for height, width and size: everything is working.

```objective-c
@implementation MTLJSONAdapter (Transformers)

+ (NSValueTransformer<MTLTransformerErrorHandling> *)integerTransformer {
    return [MTLValueTransformer
            transformerUsingForwardBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
                return value;
            } reverseBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
                return value;
            }];
}
@end
```

```objective-c
@implementation GiphyImage

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return [NSDictionary mtl_identityPropertyMapWithModel:self];
}

+ (NSValueTransformer *)heightJSONTransformer {
   return [MTLJSONAdapter integerTransformer];
}

+ (NSValueTransformer *)widthJSONTransformer {
    return [MTLJSONAdapter integerTransformer];
}

+ (NSValueTransformer *)sizeJSONTransformer {
    return [MTLJSONAdapter integerTransformer];
}

@end
```

Is it bug or feature? I think supporting scalar types by default is good idea.

Full project code is here http://monosnap.com/file/gJEM69DkaOZwtZRU1se4VHdWlUY0ZX

**Comment by jspahrsummers** [comment]
This definitely sounds like a regression, since primitives should indeed be supported.

@robb Any ideas?

**Comment by robb** [comment]
Could it be that the input value is an `NSString` and not an `NSNumber`?

**Comment by dcaunt** [comment]
@pilot34 can you provide your input JSON please?

**Comment by pilot34** [comment]
You're right, there are strings :( Sorry for panic 
http://api.giphy.com/v1/gifs/trending?api_key=dc6zaTOxFJmzC

**Comment by robb** [comment]
No worries, our fault really.
