### ISSUE TITLE
Should README show an example of Mantle earlier?

### ISSUE THREAD

**Issue by Ashton-W** [Mantle/Mantle#493]
I have an anecdote: everyone I've shown the Mantle github page to has been confused by the `README` starting with an example of _not_ using Mantle, and almost half way down the page we see the first example of **Mantle**.

It is my opinion that the `README` should quickly get to the point and show off **Mantle**. I would still include the descriptive before & after write up after a quick introduction to the framework.

Thoughts?

**Comment by jspahrsummers** [comment]
Sure, this is a great idea! If you'd like to submit a pull request to make this change, we'd be more than happy to review it. :sparkles:

**Comment by Vanson** [comment]
How to integration Mantle into a project, without cocoapods?

**Comment by jspahrsummers** [comment]
@Vanson See https://github.com/Mantle/Mantle/pull/498. That is not related to this issue, so please ask further questions in a new issue if you have them.

**Comment by Vanson** [comment]
@jspahrsummers  Thank you very much.

**Comment by danielgalasko** [comment]
I think this is a great idea. Showing the simplicity of MTLModel in the first part of the README is way more enticing than starting off with the headache of doing it manually. I don't mind taking some time to bring the introduction of MTLModel up if you haven't already @Ashton-W ?

**Comment by Ashton-W** [comment]
Please, go ahead

**Comment by robb** [comment]
:sparkling_heart:
