### ISSUE TITLE
Serialising custom object into array

### ISSUE THREAD

**Issue by jjramos-developer** [Mantle/Mantle#494]
I have a class that it is just a wrapper on top of NSMutableArray .
```objective-c
@interface WrapperClass

@property (strong, nonatomic) NSMutableArray *array;
- (void)someMethodA;
- (void)someMethodB;

@end
```

All objects in that array are objects of this class

```objective-c
@interface CustomClass

@property (copy, nonatomic) NSString *key;
@property (copy, nonatomic) NSString *value;

@end
```

When I serialise an object of WrapperClass, I want it to be serialised into an array. At the same time, when I get a JSON object, I want that array to be serialised into a WrapperClass object and not just an NSArray.

The only solution I have found is, by providing this implementation of  `+ (NSValueTransformer *)arrayJSONTransformer`

```objective-c
[MTLValueTransformer reversibleTransformerWithForwardBlock:^id(NSArray *array) {
        NSMutableArray *values = [[NSMutableArray alloc] initWithCapacity:array.count];
        for (NSDictionary *dict in array) {
            [values addObject:[MTLJSONAdapter modelOfClass:[CustomClass class]
                                        fromJSONDictionary:dict
                                                     error:nil]];
        }
        return values;
    } reverseBlock:^id(WrapperClass *wrapper) {
        NSMutableArray *array = [[NSMutableArray alloc] initWithCapacity:wrapper.array.count];
        for (CustomClass *keyValue in wrapper.array) {
            [array addObject:[MTLJSONAdapter JSONDictionaryFromModel:keyValue]];
        }
        return array;
```

Is there a better way to achieve this? I’m doing some manual work that Mantle would do although I couldn’t find a better way to achieve what I wanted. 

I would appreciate some advice regarding whether this approach can be optimised.

Thanks.

**Comment by jspahrsummers** [comment]
I think that solution is reasonable. :sparkles:

Mantle isn't really built to support this kind of edge case, so I think it's understandable that it would take a little bit more leg work. Sorry about that!

**Comment by jjramos-developer** [comment]
@jspahrsummers thanks a lot for your help and for the great work with this framework.

**Comment by jspahrsummers** [comment]
No problem! :blush:
