### ISSUE TITLE
Merge <=> Union

### ISSUE THREAD

**Issue by sgtsquiggs** [Mantle/Mantle#497]
This was throwing me off for a while.

I understood "merge" to basically mean the union of two models (of the same class).

In Mantle, ```- (void)mergeValuesForKeysFromModel:(MTLModel *)model``` will copy all values, even if those values are nil, basically creating a clone. I would expect non-nil values from ```model``` to overwrite existing values in ```self```, while nil values are ignored.

Was this the intended behavior or am I just plain wrong?

**Comment by robb** [comment]
With just `nil`, it's quite difficult to model both _unknown_ and _not something_, which makes it impossible for Mantle to offer an implementation for `-mergeValuesForKeysFromModel:` that suits everybody's needs.

I suggest you override the method to perform custom merging logic as it makes sense for your domain.

**Comment by sgtsquiggs** [comment]
I agree. "Not set" does not equate to "no value". I wrote a category to add a union method, though "union" doesn't feel like the correct verb.

**Comment by jspahrsummers** [comment]
I agree this is confusing, but @robb's points about not being able to infer a reasonable merge strategy are accurate, so I'm not sure there's any action we can take here.
