### ISSUE TITLE
'Mantle/MTLJSONAdapter.h' file not found

### ISSUE THREAD

**Issue by sseen** [Mantle/Mantle#500]
When checkout the project on the other mac, this issue is always come.

![2015-04-16 11 50 28](https://cloud.githubusercontent.com/assets/3367000/7185293/6e8b8314-e494-11e4-8873-c7b8acb7c5d2.png)

But in the project pods file, MTLJSONAdapter.h is not missing.
![2015-04-16 11 51 38](https://cloud.githubusercontent.com/assets/3367000/7185465/56f0bd36-e495-11e4-8214-57277bb5d15d.png)

**Comment by dcaunt** [comment]
Looks like you're including Mantle via CocoaPods, what version of Mantle are you importing and what does your Podfile look like? Have you run `pod install`? The Pods-<redacted>-Private.xcconfig warnings are probably related to the trouble you are having.

**Comment by robb** [comment]
Closing this for age, feel free to reopen.
