### ISSUE TITLE
 'Mantle/Mantle.h' file not found

### ISSUE THREAD

**Issue by yishuiliunian** [Mantle/Mantle#502]
![screenshot](https://cloud.githubusercontent.com/assets/846525/7198192/3b0fe54c-e51c-11e4-8b34-f38c8bd842bb.png)

when i build the octokit for mac, it occurs this error. how to deal with it ?

**Comment by jspahrsummers** [comment]
Are you building from the workspace? And did you run `script/bootstrap` in the repository?

**Comment by exstalis** [comment]
I'm having the same problem after updating podfile, I tried to fix it by re-adding header search  path after pod update and pod init didn't work.

**Comment by jspahrsummers** [comment]
@exstalis We don't support CocoaPods installation or maintain the podspec ourselves, so I'm afraid I can't help there.

**Comment by drouillard** [comment]
@yishuiliunian  You are likely specifying and old version

Your podfile should be something like

pod 'Mantle', '1.5.4'

if you have '0.x.x' version then the file won't be found.

**Comment by reckonsys** [comment]
I had downloaded SDK i'm using in swift it is showing 'Mantle/Mantle.h' file not found

**Comment by drouillard** [comment]
If you are using Swift then you need to build the bridge

https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID122

Mantle-Bridging-Header.h (be sure to update build settings as well per above link)

    #ifndef Mantle_Bridging_Header_h
    #define Mantle_Bridging_Header_h

    #import <Mantle/Mantle.h>
  
    #endif /* Mantle_Bridging_Header_h */

Then in your swift files

    import Mantle

**Comment by vishnukaey** [comment]
I had the same issue, could not get through. I had to add the framework manually into my project and it worked.

**Comment by drouillard** [comment]
CocoaPods will automatically build the bridge

    use_frameworks!
