### ISSUE TITLE
JSONDictionaryFromModel:error: not work

### ISSUE THREAD

**Issue by ondev** [Mantle/Mantle#504]
I have check the latest code in the master repository.  and test the JSONDictionaryFromModel:error,

my mode write the code like:
```
@implementation AuthorCodeReqParam
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{};
}
@end

//then
AuthorCodeReqParam *param = [AuthorCodeReqParam new];
param.xxx = @"xxx";

//then 
NSDictionary *dic = [MTLJSONAdapter JSONDictionaryFromModel:param error:&error];
//the dic always is nill here
```

I have debug the code,  in MTLJSONAdapter.m at 187 line, the variable  propertyKeysToSerialize is nil,

I think this serializablePropertyKeys:forModel: is not correct here, not use the mode in the function implement.

Any help?
 
Best Regards

**Comment by robb** [comment]
You need to implement `+JSONKeyPathsByPropertyKey` and return a mapping from property keys to JSON key paths, e.g. `return @{ @"xxx": @"json_x_x_x" }`.

**Comment by zhangliugang** [comment]
if property name equal dictionary key name, can i pass it in + (NSDictionary *)JSONKeyPathsByPropertyKey;

**Comment by robb** [comment]
@zhangliugang You can no longer return `@{}` to map every property name to a JSON key path of the same name. You probably want to use (`+mtl_identityPropertyMapWithModel:`)[https://github.com/Mantle/Mantle/blob/master/Mantle/NSDictionary+MTLMappingAdditions.h#L13-L19] for that.

**Comment by ondev** [comment]
@robb Thanks very much,  the latest version need us to map the json key to property, even if these names are equal.
