### ISSUE TITLE
How to use Mantle for mapping objects

### ISSUE THREAD

**Issue by matrosovDev** [Mantle/Mantle#506]
So I have a model user that I receive from API in json. One of the key is "status", but sometimes I receive status as an integer and sometimes as an structure like a dictionary.

What is solution can be here?

Or there is just one solution, make duplicated class where is a status property is an NSInteger and another one has it's own type for status where we can use value transformation.

**Comment by robb** [comment]
Have you tried using a custom value transformer that can handle both integers and dictionaries as inputs?

**Comment by matrosovDev** [comment]
yep, the transformer works perfect. But I think I have another issue. So API return for me different type of object so in one case it's an NSDictionary and in other it's an NSInteger.

**Comment by robb** [comment]
Yeah, I was thinking you could have a transformer that can handle both `NSNumber` and `NSDictionary *` if you don't want to have a class cluster.

**Comment by matrosovDev** [comment]
so let's assume I have and JSON that return for me data

base_url/some_api/user

{
status: 1 // here is a number
}

but another base_url/some_api/user_me

{
status: {some new keys here} // here is a status a dictionary that represented as class then for example AMStatus.h (.m)
}

So both api return for me a user. First request return for me any users, and second api return for me a user which is my user, but in second case it return for me status as a dictionary which I need to parse to my object.

I think there is only one solution to have two classes:
AMUser (this contains status as NSNumber)
AMUserMe (and this contains status as an Object - > AMStatus)

**Comment by robb** [comment]
:+1: that's a totally reasonable approach. Make sure to implement [`+classForParsingJSONDictionary:`](https://github.com/Mantle/Mantle/blob/5d864afc4c2786298c2bb94191bca08cd226a737/Mantle/MTLJSONAdapter.h#L65-L76) to return either `AMUser.class` or `AMUserMe.class` depending on the `status` value.

I'm closing this one out, but feel free to reopen if you have any other isses. :sparkling_heart:
