### ISSUE TITLE
mtl_identityPropertyMapWithModel throws exception

### ISSUE THREAD

**Issue by ellern** [Mantle/Mantle#507]
>*** Assertion failure in +[NSDictionary(MTLMappingAdditions) mtl_identityPropertyMapWithModel:](), /.../Pods/Mantle/Mantle/NSDictionary+MTLMappingAdditions.m:16

It works if I change the JSONKeyPathsByPropertyKey method to use this:

    + (NSDictionary *)JSONKeyPathsByPropertyKey {
        NSArray *propertyKeys = [self.class propertyKeys].allObjects;
        return [NSDictionary dictionaryWithObjects:propertyKeys forKeys:propertyKeys];
    }

Am I doing something wrong, or is this a bug?

```
// Player.h
#import <Foundation/Foundation.h>
#import <Mantle/Mantle.h>

@interface Player : MTLModel <MTLJSONSerializing>

@property (nonatomic) NSString *PlayerId;
@property (nonatomic) NSInteger Score;

@end

// Player.m
#import "Player.h"

@implementation Player

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return [NSDictionary mtl_identityPropertyMapWithModel:self];
}

@end

- (void)testPlayerModel {
    Player *player = [Player new];
    player.PlayerId = @"player1";
    player.Score = 123;
    
    NSError *error = nil;
    NSDictionary *serialized = [MTLJSONAdapter JSONDictionaryFromModel:player error:&error];
    
    XCTAssertNil(error);
    XCTAssertEqualObjects(@"player1", (NSString*)[serialized objectForKey:@"PlayerId"]);
    XCTAssertEqual(123, [[serialized objectForKey:@"Score"] integerValue]);
}
```

**Comment by robb** [comment]
Most likely, Mantle is linked twice so the `MTLModel` class that triggers the assert is not the one your object inherits from. See https://github.com/CocoaPods/CocoaPods/issues/1411
