### ISSUE TITLE
Parsing JSON with Period in Key

### ISSUE THREAD

**Issue by masgharneya** [Mantle/Mantle#508]
I am trying to parse some JSON with a period in it, but it is causing issues with Mantle. Any way of working around this issue without modifying the keys before Mantle sees them?

Example: 

``` json
    "optional.detail" : {
      "name" : "Test",
      "all.pictures" : [
        {
          "original" : "original.jpg",
          "mobile" : "mobile.jpg"
        }
      ]
    }
```

**Comment by robb** [comment]
Not currently, this came up before in #403 and I still think extending `MTLJSONAdapter` to handle escaped periods would be the simplest option. We'd gladly review a PR to that extend :sparkling_heart:

**Comment by dcaunt** [comment]
@robb I don't know if your [suggestion in #403](https://github.com/Mantle/Mantle/pull/403#issuecomment-59399205) will work as Xcode treats it as an escape sequence.

**Comment by robb** [comment]
ugh, I see. `@"foo\\.bar"` then? Alternatively, we'd have to promote a JSON keypath into a type that can be composed of arbitrary strings, e.g.: 

```objc
 (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
        @"name": MTLJSONKeyPaths(@"com.github.com", @"user,  @"name", @"firstName")
    }
}
```

**Comment by dcaunt** [comment]
I think the double escape would be preferable, in order to keep the existing dot syntax for key paths.

**Comment by masgharneya** [comment]
I will give the double escape a try and create a PR when I can.

**Comment by Lukapple** [comment]
Same issue here. Any workaround yet?
