### ISSUE TITLE
mtl_valueForJSONKeyPath:success:error:]: unrecognized selector

### ISSUE THREAD

**Issue by engmsaleh** [Mantle/Mantle#509]
I have made the Models but I always get this error
 -[__NSDictionaryI mtl_valueForJSONKeyPath:success:error:]: unrecognized selector sent to instance 0x7f9041512a30

**Comment by robb** [comment]
How are you integrating Mantle into your project?

**Comment by engmsaleh** [comment]
@robb  Thanks for your reply , it indeed solved the problem :) , I have installed it using Cocoapods but didn't add any flags.
