### ISSUE TITLE
Tests won't compile on Xcode 6.3

### ISSUE THREAD

**Issue by rex-remind101** [Mantle/Mantle#513]
It looks as if the Quick and Nimble dependencies need to upgrade to be compatible with the latest changes in swift. In the meantime, I can't seem to be able to compile the tests.

![screen shot 2015-05-06 at 11 56 55 am](https://cloud.githubusercontent.com/assets/4573957/7501254/96b73a24-f3e7-11e4-9eed-54196ba38d40.png)
![screen shot 2015-05-06 at 11 59 22 am](https://cloud.githubusercontent.com/assets/4573957/7501255/98a4e9da-f3e7-11e4-9134-1db4eb734c33.png)
![screen shot 2015-05-06 at 11 59 28 am](https://cloud.githubusercontent.com/assets/4573957/7501257/9a844fd4-f3e7-11e4-8d5f-8c55885655ad.png)

**Comment by jspahrsummers** [comment]
This is unfortunate, since we only use the Objective-C bits. I guess there's no way around that. :confused: 

In any case, we'd greatly appreciate a pull request bumping their versions! :pray:
