### ISSUE TITLE
Proper way to instantiate a new instance of a MTLModel subclass

### ISSUE THREAD

**Issue by dwsjoquist** [Mantle/Mantle#514]
Given a class like this:
    @interface MyModel : MTLModel<MTLJSONSerializing>

is this the proper way to instantiate a new instance?

    MyModel *instance = [MTLJSONAdapter modelOfClass:[MyModel class] fromJSONDictionary:json error:&error];

I would have expected something like the following, but it does not work. It builds and runs, but most of the Mantle magic is ignored, so things like "xyzzyJSONTransformer" methods are not called. (They are called in the above usage.)

    MyModel *instance = [[MyModel alloc] initWithDictionary:json error:&error];

**Comment by robb** [comment]
```objc
MyModel *instance = [MTLJSONAdapter modelOfClass:[MyModel class] fromJSONDictionary:json error:&error];
```

is the proper way to deserialize a Mantle model from a JSON dictionary, yeah.

```objc
MyModel *instance = [[MyModel alloc] initWithDictionary:json error:&error];
```

on the other hand initializes a Mantle model from a dictionary (*not JSON*) representation.

**Comment by dwsjoquist** [comment]
Thanks, that explains what I was seeing in my testing sandbox. Mantle looks pretty sweet, looking forward to using it.
