### ISSUE TITLE
Type coercion desirable? 

### ISSUE THREAD

**Issue by jshier** [Mantle/Mantle#515]
In working with a rather, shall we say, unreliable backend recently, our iOS app has hit some issues that the Android version avoided. This is due to Android using the gson library, which has the rather handy ability to coerce return values with the wrong type to the one designated by the model object definition being serialized. So for instance, if you're expecting a string and receive a number, gson will convert it to a string for you, automatically. I'm wondering if Mantle would consider this a desirable feature, and, if so, if there's any preferred strategy for implementation? I can see quite a few ways to implement this feature, most of which are hindered by the fact that Mantle encourages transformations over model objects whose property types conform only to the accepted JSON types. Perhaps something like `+(NSDictionary *)preferredJSONTypesForProperties` would work there?

Thoughts?

**Comment by robb** [comment]
Thanks for the suggestion.

We have [`-transformerForModelPropertiesOfClass:` and `-transformerForModelPropertiesOfObjCType:`](https://github.com/Mantle/Mantle/blob/8848226647862b73b6ea15dace48943a8b2b42aa/Mantle/MTLJSONAdapter.h#L198-L227) which do similar things for Booleans and `NSURL`s right now. I'm very hesitant to add anything more magic than those, especially number/string conversion though, that seems pretty fragile.

**Comment by jshier** [comment]
I agree that magic conversions should be avoided, and some type coercions are to unsafe or code intensive to be viable. But something like automatically converting numbers to strings (at least in the initial parsing) should be completely safe, given that they're already wrapped in an NSNumber and have been validated by the JSON parser. I'll take a look at the methods you mentioned, but it seems like the transformations I'm talking about would take place before anything else, so that future transformations would get the types they expect. If I have some time I may hack together a possible implementation.

**Comment by jspahrsummers** [comment]
I'm not sure it is safe. For example, how should the number be localized if it has a decimal point, represents a negative number, might need thousands separators, etc.?

And the _reverse_ certainly isn't safe, since it's not always possible to obtain a number from a string.

I'd suggest overriding the methods that @robb pointed out, and adding your own transformations there. That allows you to have the behavior you've described, but doesn't introduce edge cases that might trip up other consumers of Mantle proper.
