### ISSUE TITLE
as you know ,I has a string from service,but it's a NSNumber in my model, what should i do...

### ISSUE THREAD

**Issue by ccguo** [Mantle/Mantle#517]
As you know ,I has a string from service,but it's a NSNumber in my model, what should i do...

**Comment by ccguo** [comment]
I did this ,but it don't work...
@property (nonatomic,retain) NSNumber  *cityId;
//
+ (NSValueTransformer *)cityIdJSONTransformer {
    return [MTLValueTransformer reversibleTransformerWithForwardBlock:^(NSString *str) {
        return [NSNumber numberWithInt:[str intValue]];
    } reverseBlock:^(NSNumber *cityId) {
        return cityId;
    }];
}

/*json
{
weatherinfo: {
city: "北京",
cityid: "101010100",
temp: "9",
WD: "西南风",
WS: "2级",
SD: "22%",
WSE: "2",
time: "10:35",
isRadar: "1",
Radar: "JC_RADAR_AZ9010_JB",
njd: "暂无实况",
qy: "1015"
}
}
*/

**Comment by ccguo** [comment]
Execuse me，I have got the issue, very veru bad ,the shine is error...

**Comment by liuxuan30** [comment]
I don't know what are you talking about.

**Comment by ccguo** [comment]
I was inside the project and want to use mantle, but this place often appear a problem, to server in the implementation of the type of data and before the document discrepancies, if the interface is a string, the model is nsnumber. I try with tutorial method of conversion, has been found ineffective, later found to be mapping table wrong, very sorry...

[来自百度翻译]

**Comment by jspahrsummers** [comment]
> I try with tutorial method of conversion, has been found ineffective, later found to be mapping table wrong, very sorry...

@ccguo Were you able to figure it out, or did you still have questions?

**Comment by robb** [comment]
Closing this one for lack of activity, feel free to reopen it if the problem persists. :v:
