### ISSUE TITLE
a strict version of modelOfClass:fromJSONDictionary: ?

### ISSUE THREAD

**Issue by knlr** [Mantle/Mantle#518]
Consider I'm using modelOfClass:fromJSONDictionary: and I want to be able to tell if something in the mapping went wrong, like a missing key or a type error (e.g. property is a NSNumber but it's a string in the JSON and an NSString is assigned). 

I could write validation functions in my model classes checking the validity of each property. Or there could be a 'strict' version of modelOfClass:fromJSONDictionary that returns nil and gives an error when a key was not found or a wrong type is assigned to a property. Is it possible? If so, would you add this?

**Comment by jspahrsummers** [comment]
AFAIK the method should already have this “strict” behavior. Are you seeing something different?

**Comment by knlr** [comment]
Yes I do. Maybe I didn't make myself clear. When a mapped key is not contained in the JSON, the mapped property will be nil, the model object will be created and the error is nil. Example:

    @interface MTLTweet : MTLModel <MTLJSONSerializing>
    
    @property (nonatomic) NSString* text;
    @property (nonatomic) NSString* userName;
    @property (nonatomic) NSString* profileImageURL;
    
    @end

    @implementation MTLTweet
    
    + (NSDictionary *)JSONKeyPathsByPropertyKey {
            return @{
                 @"text": @"Text", 
                 @"userName": @"user.name",
                 @"profileImageURL": @"user.profileimageurl" // intentionelly misspelled 
                 };
    }

    @end

the NSDictionary (abbreviated):
    (lldb) po response
    
    {        
        text = "Piraeus Egypt has highest retail banking portfolio growth for 2014 http://t.co/t4YI8M7bee #DaytonFinancialAdvice";    
        user =     {    
            name = "John Stamos";
            "profile_image_url" = "http://pbs.twimg.com/profile_images/378800000731641435/275da1fb86bcb0d8b55a9da640881643_normal.jpeg";
        };
    }

instantiating the model object:

    MTLTweet* tweet = [MTLJSONAdapter modelOfClass:MTLTweet.class
                                fromJSONDictionary:response
                                             error:&error];

    (lldb) po tweet
    <MTLTweet: 0xc767c80> {
        profileImageURL = "<null>";
        text = "@coxin_jon Pitiful, Recession in Bush s 8th! Year was Housing bubbles fault? Auto/Banking sectors near destroyed. 2 Costly not paid for wars";
        userName = Jonnykam;
    }

I want the tweet to be nil if one of the properties is nil.

**Comment by robb** [comment]
> I could write validation functions in my model classes checking the validity of each property. 

In this case, `-validateProfileImageURL:error:` would never be invoked. I'd recommend overriding `-[MTLModel validate:]` and check `profileImageURL != nil` there.

**Comment by danielgalasko** [comment]
So @knlr just to confirm, you would like to specify a list of non nullable properties on an MTLModel subclass? 

Like a `MTLJSONCompulsoryKeyPathsSerializing` protocol that the JSONAdapter would use as an added step during serialization?
