### ISSUE TITLE
Support property attributes: `nonnull` and `nullable`

### ISSUE THREAD

**Issue by Ashton-W** [Mantle/Mantle#521]
Should **Mantle** support validation based on the new property attributes `nonnull` and `nullable`
[Read about them here](https://developer.apple.com/swift/blog/?id=25)

``` objc
@property (copy, nullable) NSString *name;
@property (copy, readonly, nonnull) NSArray *allItems;
```

Assuming they are available in the runtime, should **Mantle** use them to inform the validation of models? The checks these attributes add are at compile time, so have no effect on **Mantle**'s KVC powered features.

**Comment by jspahrsummers** [comment]
I'm pretty sure these are not available at runtime. Even if they were, Mantle doesn't perform much automatic validation—most of that is up to your model.

**Comment by Ashton-W** [comment]
That is true, it is up to you to add *Key-Value Validation* methods to your model. This doesn't exactly fall under the JSON checks.
Maybe this could be changed to an enhancement for validation helper methods in **Mantle**. Which if possible, would include checking nullability.

Currently, writing the Key-Value Validation methods is a drag.
