### ISSUE TITLE
Mapping Array of Arrays

### ISSUE THREAD

**Issue by emejia160** [Mantle/Mantle#522]
I have a model like this:
@interface XYClass : XYBaseModel

@property (nonatomic, copy) NSString *singleValue;
@property (nonatomic, copy) NSArray *recordValue;

@end

The property recordValue is an array of arrays. It is possible to map this with mantle? I tried with JSONTransformer

+ (NSValueTransformer *)recordValueJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:XYRecordValue.class];
}
Where XYRecordValue class is:

@interface XYRecordValue : XYBaseModel

@property (nonatomic, copy) NSArray *records;

@end

But i got an exception : "Caught exception Expected a dictionary or an NSNull, got: <CFArray 0x7b7f17f0 [0x30be808]>{type = immutable, count = 5, values = (..."

Thanks!

**Comment by jspahrsummers** [comment]
You'll need to write a custom JSON transformer for this case. Mantle doesn't automatically un-nest arrays for you.
