### ISSUE TITLE
Current release does not compile?  Am I missing something?

### ISSUE THREAD

**Issue by slycrel** [Mantle/Mantle#524]
I used the 2.0 release source originally to implement mantle, which worked pretty ok, other than the 2.0 release has ```class``` as a variable name in a few places.  During development this wasn't an issue, just change the local headers.

I would like to now use carthage to manage this dependency across our team.  However, the current direction of using ```github "Mantle/Mantle"``` has the same issue, it does not compile due to the class named variables.  Other than waiting for a new release is there anything that can be done here?

Thanks in advance!

**Comment by jspahrsummers** [comment]
Mantle hasn't been written with Objective-C++ in mind. If you'd like to submit a pull request that fixes it up for that use case, we'd be happy to review it. :pray:

**Comment by cmicali** [comment]
It looks like this was fixed a while ago - any chance we could get this pushed to Cocoapods?

One example: https://github.com/Mantle/Mantle/commit/ddf43709de66e9cdf2dc2f48c015cbd17c302893

**Comment by jspahrsummers** [comment]
Sorry, we don't maintain or officially support the Mantle podspec. Please contact the contributors on the podspec file directly.

**Comment by cmicali** [comment]
Well it's not just the podspec - the most recent release/tag was 2.0 which does not include this fix, so there would need to be a newer release that the podspec could point to.

**Comment by slycrel** [comment]
cmicali I believe is correct that this has already been fixed/changed in master.  The currently tagged release of 2.0 does not compile either as a framework via carthage or the 3rd party cocoapods without modification to those header files.  I had hoped I wouldn't have to wait for an arbitrary release date to see this go away.

I'll be working around this I guess by not using carthage, which is a shame.  I was looking forward to it.  Thanks for your response.

**Comment by jspahrsummers** [comment]
Sorry, I didn't realize we needed a new release as well. [2.0.1](https://github.com/Mantle/Mantle/releases/tag/2.0.1) has been tagged.

**Comment by cmicali** [comment]
Thanks @jspahrsummers!

**Comment by dcaunt** [comment]
I'll update the spec. Thanks for the tag @jspahrsummers

**Comment by cmicali** [comment]
:thumbsup: @dcaunt

**Comment by jspahrsummers** [comment]
Had to cut another release, [2.0.2](https://github.com/Mantle/Mantle/releases/tag/2.0.2), to fix a crash introduced in 2.0.1. Sorry about the churn! :disappointed_relieved:

**Comment by slycrel** [comment]
Thanks!

**Comment by dcaunt** [comment]
Just pushed [2.0.2](https://github.com/CocoaPods/Specs/blob/master/Specs/Mantle/2.0.2/Mantle.podspec.json) to trunk for CocoaPods users
