### ISSUE TITLE
No known class method for selector 'mtl_modelErrorWithException:'

### ISSUE THREAD

**Issue by donileo** [Mantle/Mantle#527]
Im getting an archive error when trying to build my app. The following is reported by Xcode and fails to archive my app: Pods/Mantle/Mantle/MTLModel.m:57:22: No known class method for selector 'mtl_modelErrorWithException:'.

The weird thing is building the app itself works. Just archive is failing.

-As a fix I added #import "NSError+MTLModelException.h" to the top of the MTLModel.m file but Im not sure if this project itself should have the be in there.

**Comment by robb** [comment]
This may be an issue with your build configuration. Are you passing in the `-ObjC` Linker Flag to Release builds?

**Comment by donileo** [comment]
Yes I am passing it in. Using cocoa pods it seems its already added in and I see that it is.

**Comment by jspahrsummers** [comment]
This seems like a CocoaPods issue. Mantle itself compiles fine.
