### ISSUE TITLE
Type Validation

### ISSUE THREAD

**Issue by hengw** [Mantle/Mantle#531]
I am a little confused over type validation. I read from the issues that type validation should be automatically supported but it does not seem so. 

```
@interface TestObj : MTLModel <MTLJSONSerializing>

@property (nonatomic, strong) NSString *test;

@end

@implementation TestObj

+ (NSDictionary *)JSONKeyPathsByPropertyKey
{
    return [NSDictionary mtl_identityPropertyMapWithModel:self.class];
}

@end

//Calling function
- (void) createObj {
    NSDictionary *dict = @{@"test":@(1)};
    NSError *error;
    NSData *jsonData = [NSJSONSerialization dataWithJSONObject:dict
                                                       options:0
                                                         error:&error];

    TestObj *testObj = [MTLJSONAdapter modelOfClass:[TestObj class] fromJSONDictionary:dict error:&error];
    NSLog(@"%@",testObj.test.class) // => Is NSNumber and will crash if try to do something with it
}
```

Can I know what am i missing here? Thanks!

**Comment by robb** [comment]
Seems like a bug to me

**Comment by hengw** [comment]
I am still trying to understand the code. If I am not wrong, the type validation is supposed to happen here?

In MTLJSONAdapter:

```
+ (NSDictionary *)valueTransformersForModelClass:(Class)modelClass {

...

			if (propertyClass != nil) {
				transformer = [self transformerForModelPropertiesOfClass:propertyClass];
			}

			if (transformer == nil) transformer = [NSValueTransformer mtl_validatingTransformerForClass:NSObject.class];

...

```

Why are we checking against NSObject.class instead of propertyClass?

**Comment by robb** [comment]
yeah, exactly. See #532

**Comment by hengw** [comment]
Ok. Thanks a lot! It works now. 
From what I see, so as long as 1 property is invalid, the whole object is invalid.
Is there any way we can still have a partially initialized object but with the invalid property set as nil?

**Comment by robb** [comment]
Not out of the box, I would suggest writing a `MTLJSONAdapter` subclass that overrides `+transformerForModelPropertiesOfClass:` to return an adapter that tries to parse and falls back to nil otherwise.

**Comment by hengw** [comment]
Ok. I will try that. Thanks a lot. =)
