### ISSUE TITLE
Command line build

### ISSUE THREAD

**Issue by Invader-Zim** [Mantle/Mantle#534]
I have everything working inside Xcode.  I can build, debug, archive, export AdHoc IPA, and deploy.  But we use Jenkins for nightly builds.

xcodebuild -sdk iphoneos -scheme $PROJECT_NAME archive -archivePath "$TARGET_DIR/$ARCHIVE_NAME" PROVISIONING_PROFILE="${UUID}"

I get the following error

=== BUILD TARGET Mantle-iOS OF PROJECT Mantle WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: Provisioning profile does not match bundle identifier: The provisioning profile specified in your build settings (“XYZ AdHoc”) has an AppID of “com.XYZ” which does not match your bundle identifier “com.Mantle”.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'

If I change the Mantle bundle identifier I can get it to build, but of course it won't deploy because the framework and the app will have the same bundle id.  I haven't found others with this problem.  So clearly I am doing something wrong.

**Comment by jspahrsummers** [comment]
Passing in `PROVISIONING_PROFILE="${UUID}"` will apply that build setting to every target build, AFAIK. Mantle shouldn't need to build with a provisioning profile.

I would set that in your app's AdHoc (or whichever) build configuration instead, so it doesn't have to be specified on the command line.

**Comment by Invader-Zim** [comment]
Thanks for the quick response.  I thought of that shortly after posting.  The following builds now.

xcodebuild -sdk iphoneos -scheme $PROJECT_NAME archive -archivePath "$TARGET_DIR/$ARCHIVE_NAME"

Now I am having problems when I try to install.  I generate the IPA with the following:

xcrun -sdk iphoneos PackageApplication -v "$TARGET_DIR/$ARCHIVE_NAME/Products/Applications/$PROJECT_NAME.app" -o "$TARGET_DIR/$IPA_NAME" --sign "${DEVELOPER_NAME}" --embed "${PROVISIONING_PROFILE}"

And when I try to install the IPA to my phone I get

The executable was signed with invalid entitlements.
The entitlements specified in your application’s Code Signing Entitlements file do not match those specified in your provisioning profile. (0xE8008016).

**Comment by Invader-Zim** [comment]
Nevermind.  I misunderstood.  I needed to set the app target's provisioning profile, then omit those parameters from both xcodebuild and xcrun.  It's working now.

**Comment by jspahrsummers** [comment]
:+1:
