### ISSUE TITLE
Any suggested way to interact with SQlite?

### ISSUE THREAD

**Issue by engmsaleh** [Mantle/Mantle#540]
Hi, 
Thanks for this awesome lib.
I'm trying to consider options to save to save data locally other than CoreData , I have looked to FMDB and found that there is a lib called MTLFMDBAdapter but unfortunately it isn't using the latest version of Mantle and this makes it unsuitable?
Does anyone have other options?

Thanks

**Comment by robb** [comment]
Looks like [MTLFMDBAdapter has just upgrade to 2.0](https://github.com/tanis2000/MTLFMDBAdapter/commit/9371b486d5eac142d6e22a4a06c1c6927e4db1b3)

**Comment by engmsaleh** [comment]
Thanks @robb I will check it :)

**Comment by robb** [comment]
Closing this for now, feel free to reopen it if anything new comes up.
