### ISSUE TITLE
Mantle in XCTests: model classes are failing the MTLModel.class check

### ISSUE THREAD

**Issue by cbowns** [Mantle/Mantle#542]
I'm spuriously encountering a *very* strange issue with Mantle in some unit tests in my iOS app.

My test occasionally fails this parameter assertion:

```
+ (NSValueTransformer *)mtl_JSONDictionaryTransformerWithModelClass:(Class)modelClass {
	NSParameterAssert([modelClass isSubclassOfClass:MTLModel.class]);
…
```
(effectively [this assertion](https://github.com/Mantle/Mantle/blob/d236caa864cdbb105539619aee9abbf91a64a776/Mantle/MTLJSONAdapter.m#L470); looks like I'm on a different version of Mantle in this project.)

On further searching, it looks like this may be the same issue as https://github.com/Mantle/Mantle/issues/168 ?

What's the root cause of this, exactly? I've done iOS and OS X build engineering, grok the runtime, etc etc… it just seems odd that I'm getting double-class implementations in the runtime here. This is literally the first test I've started writing on the app. (I do have libPods.a manually linked to satisfy linker requirements for frameworks the app uses.)

Here's some debugger output:

```
(lldb) po modelClass
BoldPost

(lldb) po [modelClass superclass]
MTLModel

(lldb) p [modelClass superclass]
(Class) $6 = MTLModel
(lldb) p MTLModel.class
(Class) $7 = MTLModel
(lldb) c
2015-06-22 16:54:08.423 BOLD[7746:334780] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [modelClass isSubclassOfClass:MTLModel.class]'
```

**Comment by robb** [comment]
Yeah, pretty sure it's a duplicate of #168. Most likely Mantle is linked twice, but it's hard to say how without looking at your project.

**Comment by cbowns** [comment]
Gotcha. I'll pull it up in `otool` and see what's what.

**Comment by cbowns** [comment]
1. I goddamn hate how Xcode hides the actual commands it uses to run tests.
2. Do you know how I could verify that's the actual issue? I'm digging through the target's *Tests binary with `otool` but can't find any duplicate symbol definitions.

```
% ○ xcrun otool -t -v /Users/cbowns/Library/Developer/Xcode/DerivedData/BOLD-bggamslslsqutdguespryufgnvar/Build/Products/Debug-iphonesimulator/BOLDTests.xctest/BOLDTests | grep -i MTLModel      [14:45:01]
+[MTLModel(NSCoding) modelVersion]:
+[MTLModel(NSCoding) encodingBehaviorsByPropertyKey]:
___52+[MTLModel(NSCoding) encodingBehaviorsByPropertyKey]_block_invoke:
+[MTLModel(NSCoding) allowedSecureCodingClassesByPropertyKey]:
___61+[MTLModel(NSCoding) allowedSecureCodingClassesByPropertyKey]_block_invoke:
___61+[MTLModel(NSCoding) allowedSecureCodingClassesByPropertyKey]_block_invoke_2:
-[MTLModel(NSCoding) decodeValueForKey:withCoder:modelVersion:]:
-[MTLModel(NSCoding) initWithCoder:]:
-[MTLModel(NSCoding) encodeWithCoder:]:
___38-[MTLModel(NSCoding) encodeWithCoder:]_block_invoke:
+[MTLModel(NSCoding) supportsSecureCoding]:
+[MTLModel(OldArchiveSupport) dictionaryValueFromArchivedExternalRepresentation:version:]:
+[MTLModel modelWithDictionary:error:]:
-[MTLModel init]:
-[MTLModel initWithDictionary:error:]:
+[MTLModel enumeratePropertiesUsingBlock:]:
___42+[MTLModel enumeratePropertiesUsingBlock:]_block_invoke:
+[MTLModel propertyKeys]:
___24+[MTLModel propertyKeys]_block_invoke:
___24+[MTLModel propertyKeys]_block_invoke_2:
-[MTLModel dictionaryValue]:
-[MTLModel mergeValueForKey:fromModel:]:
-[MTLModel mergeValuesForKeysFromModel:]:
-[MTLModel validate:]:
-[MTLModel copyWithZone:]:
-[MTLModel description]:
-[MTLModel hash]:
-[MTLModel isEqual:]:
+[NSError(MTLModelException) mtl_modelErrorWithException:]:
```

**Comment by cbowns** [comment]
I suppose this does verify at runtime that the addresses are different.

Hoisting out the class variables:

```
+ (NSValueTransformer *)mtl_JSONDictionaryTransformerWithModelClass:(Class)modelClass {
    Class mantleClass = MTLModel.class;
    Class objectClass = modelClass;
	NSParameterAssert([objectClass isSubclassOfClass:mantleClass]);
```

The debugger gives me:

```
(lldb) p [objectClass superclass]
(Class) $9 = MTLModel
(lldb) p MTLModel.class
(Class) $10 = MTLModel
(lldb) po mantleClass
MTLModel
(lldb) p mantleClass
(Class) $11 = 0x0000000117139c10
(lldb) x/x $9
0x106c8bbd8: 0x06c8bc00
(lldb) x/x $10
0x106c8bbd8: 0x06c8bc00
(lldb) x/x $11
0x117139c10: 0x17139c38

(lldb) p [modelClass isSubclassOfClass:mantleClass]
(bool) $13 = false
(lldb) p [modelClass isSubclassOfClass:[MTLModel class]]
(bool) $14 = true
```

**Comment by cbowns** [comment]
I'm going to close this out since this isn't Mantle-specific. I'll write up how I solve this, though.

**Comment by cbowns** [comment]
Basically, I was running into https://github.com/AliSoftware/OHHTTPStubs/wiki/A-tricky-case-with-Application-Tests. My tests were hosted by the app, so I was getting duplicated symbols at runtime when it loaded up my tests plugin.
