### ISSUE TITLE
how to map a NSArray value with KVC 

### ISSUE THREAD

**Issue by lizhaobomb** [Mantle/Mantle#543]
Weather is like    
 weather =     (
                {
            description = "few clouds";
            icon = 02d;
            id = 801;
            main = Clouds;
        }
    );

and in my JSONKeyPathsByPropertyKey method i wrote
{
             @"conditionDescription": @"weather.description",
             @"condition": @"weather.main",
             @"icon": @"weather.icon",
}

I also have impelement this method
+ (NSValueTransformer *)conditionDescriptionJSONTransformer {

    return [MTLValueTransformer reversibleTransformerWithForwardBlock:^(NSArray *values) {
        return [values firstObject];
    } reverseBlock:^(NSString *str) {
        return @[str];
    }];

}

but i always get this error:
Error Domain=MTLJSONAdapterErrorDomain Code=3 "Invalid JSON dictionary" UserInfo=0x7fcd32c79c60 {NSLocalizedDescription=Invalid JSON dictionary, NSLocalizedFailureReason=JSON key path weather.main could not resolved because an incompatible JSON dictionary was supplied: 

how should i do to get the right result?..thanks

**Comment by robb** [comment]
The key path is resolved before the value transformer is invoked and since `weather` maps to an array, `weather.main` cannot be resolved. Have you considered having a property of `NSArray` of `XYConditions` instead?

**Comment by lizhaobomb** [comment]
thank you @robb ,since it couldn't write like that..  so i use a property of NSArray of XYConditions instead,and when i used this Property i wrote condition[0][@"main"];
