### ISSUE TITLE
 error: expected ';' after method prototype - (NSValueTransformer *)transformerForModelPropertiesOfClass:(Class)class;

### ISSUE THREAD

**Issue by DavidYangNO1** [Mantle/Mantle#544]
Object "A" use the mantle, and another class which the file extension is ".mm"  reference the object "A". when compile and build, the error is: expected ';' after method prototype - (NSValueTransformer *)transformerForModelPropertiesOfClass:(Class)class. can anybody help how to solve the problem.

**Comment by liuyunclouder** [comment]
hey，David，I am not having the same problem, how did you solve it

**Comment by DavidYangNO1** [comment]
just avoid cycles reference,

**Comment by DavidYangNO1** [comment]
@liuyunclouder I forget,may be avoid circle reference, in the .h file, use the 
@class and the .mm reference custom model .h

**Comment by liuyunclouder** [comment]
多谢哈哈

2015-10-12 10:04 GMT+08:00 DavidYang <notifications@github.com>:
