### ISSUE TITLE
null to nil

### ISSUE THREAD

**Issue by DongjieLi** [Mantle/Mantle#545]
```
AFNetworking parse JSON:          "avatar_url" = "<null>";
Mantle:        avatarURL = "<null>";
```
when I set label text, it will appear (null).

**Comment by robb** [comment]
Not sure what your problem is?

**Comment by DongjieLi** [comment]
JSON map mantle model ,property possible "<null>". e.g. avatar_url = "<null>"
aLabel.text = avatar_url, aLabel text will show (null)

**Comment by robb** [comment]
Are you sure you're using `MTLJSONAdapter` to deserialize the JSON and not `-initWithDictionary:`?

**Comment by DongjieLi** [comment]
I made the mistake.Thank you.
