### ISSUE TITLE
How to use many-to-many relationship on mantle? 

### ISSUE THREAD

**Issue by KeanSeo** [Mantle/Mantle#546]
I added relationshipModelClassesByPropertyKey on model A, B (many-to-many relationship). It seemed work well, but infinite loop error occured at [MTLModel description]. Is it possible to use many-to-many relationship directly? (Or convert to multiple one-to-many model by making intermediate model?)

Thanks.

**Comment by robb** [comment]
You probably want to make sure that you don't have a retain cycle using some form of weak collection and then override [`-storageBehaviorForPropertyWithKey:`](https://github.com/Mantle/Mantle/blob/master/Mantle/MTLModel.h#L134-L144) to remove the offending properties from causing infinite loops.

**Comment by KeanSeo** [comment]
It works, thanks!
