### ISSUE TITLE
how to parse model with different json key?

### ISSUE THREAD

**Issue by guxianxiong** [Mantle/Mantle#547]
when i got a same model for different json key like this:
one is:
+(NSDictionary *)JSONKeyPathsByPropertyKey
{
    return @{
             @"userId": @"userId",
             @"userName" : @"userName"
             };
}
the other is:
+(NSDictionary *)JSONKeyPathsByPropertyKey
{
    return @{
             @"userId": @"user_Id",
             @"userName" : @"user_Name"
             };
}
what can i do use the same model to parse Json with different key?

**Comment by robb** [comment]
I suggest you create two classes in a class cluster that have different implementations of `+ JSONKeyPathsByPropertyKey`.

**Comment by guxianxiong** [comment]
Thanks for reply.
So in this case, i should check condition in json response. if the key has 'user_Id', i return A model, and the key has 'userId' , return B model?

**Comment by conradev** [comment]
@guxianxiong Override the `+[id<MTLJSONSerializing> classForParsingJSONDictionary:]` method
