### ISSUE TITLE
Compiling as iOS 7 static library

### ISSUE THREAD

**Issue by Axlle** [Mantle/Mantle#553]
Mantle looks great! I like that it is convenient and straightforward (the public API _and_ the implementation) and I want to start using it in our app. Our app is iOS 7+ whereas Mantle is iOS 8+.

Is there anything stopping us from compiling Mantle as a static library? (like using Apple APIs, bundle resources, etc.) I've experimented with linking Mantle as an static library and it appears to work on iOS 7.

**Comment by robb** [comment]
Since it's not officially supported any longer, we won't be able to offer support unfortunately, but I don't think there is much stopping you otherwise.
