### ISSUE TITLE
Parsing dictionaries inside of a nested array?

### ISSUE THREAD

**Issue by quantumpotato** [Mantle/Mantle#555]
I have JSON that looks like this:

```
@[@"restaurant" : @{@"name" : @"Restaurant 1",
                              @"specials": @[
                                 @{@"special" : @{@"name" : @"special 1"}},
                                @{@"special" : @{@"name" : @"special 2"}},
```

..etc

how do I parse specials? 

I've tried

```
+ (NSValueTransformer *)specialsJSONTransformer {
    return  [MTLJSONAdapter arrayTransformerWithModelClass:[Special class]];
}
```

in my Restaurant class but it's parsing the outer level @{@"restaurant"} dictionary instead of the value of the @{@"restaurant"} dictionary. It looks like some sort of transformation block? I'm not understanding the API naming convention like forward block, reverse block.

Thank you for a great library!

**Comment by smidaharoun** [comment]
@quantumpotato Any solutions about this issue?

**Comment by quantumproducer** [comment]
No, but I haven't used this in a while. I've switched to writing my own JSON parsing.
