### ISSUE TITLE
Handling CGPoints

### ISSUE THREAD

**Issue by mobileben** [Mantle/Mantle#558]
I currently have a project where I have data coming in as JSON and then use it to populate my objects. I was using another library to do this, but it is woefully slow, so was looking for replacements. 

I just started with Mantle, so apologies if the questions have been asked previously. I looked at the issues (closed ones) too, and didn't notice an answers to them.

I have JSON that represents a CGPoint. It's something like "pointy":  { "x": 1, "y": 2 } in JSON. 

In the class it is something like:

@property (nonatomic, assign) CGPoint pointy;

During the deserialization, it will of course fail since it is an NSDictionary and not a CGPoint. What is the best way to handle this?

Also, I happen to hit  a few APIs where numbers in the JSON are either value or string representations of the number. Is there a recommended way to handle this in a more generic fashion so it can handle either. For example, can I build a transformer to do this?

Thanks.

**Comment by mobileben** [comment]
Okay, answering a bit of my own question. I found this works (it's a little sloppy right now):

```
+ (NSValueTransformer *)pointJSONTransformer {
    return [MTLValueTransformer transformerUsingForwardBlock:^id(NSDictionary *dict, BOOL *success, NSError *__autoreleasing*error){
        return [NSValue valueWithCGPoint:CGPointMake([dict[@"x"] doubleValue], [dict[@"y"] doubleValue])];
    } reverseBlock:^id(NSValue *point, BOOL *success, NSError *__autoreleasing*error) {
        CGPoint cgPt = [point CGPointValue];
        
        return @{@"x": @(cgPt.x), @"y": @(cgPt.y)};
    }];
}
```

Is this the correct way to do it?

**Comment by robb** [comment]
Yeah, that looks good to me. You might want to build a `NSValueTransformer` subclass if you end up doing this a lot, though.

**Comment by robb** [comment]
Closing this one, feel free to reopen if you have more questions.
