### ISSUE TITLE
Validating the presence of number primitives in a JSON dictionary

### ISSUE THREAD

**Issue by nsforge** [Mantle/Mantle#559]
Lets say I have a `Person` model:
```objc
@interface Person : MTLModel <MTLJSONSerializing>
@property NSString *name;
@property NSInteger ageInYears;
@end
```
With a JSON dictionary structure that looks like this:
```json
{
	"name": "Luke Skywalker",
	"age": 25
}
```
Since the `ageInYears` property is a non-object type, it has no concept of "null", so the two following JSON dictionaries will give the same results after parsing:
```json
{
	"name": "Luke Skywalker",
	"age": 0
}
```
```json
{
	"name": "Luke Skywalker"
}
```
In a project I'm working on at the moment, I'm performing aggressive type-safety and nullability validation in `-[MTLModel validate:]`, but as far as I can tell, you can't see the original JSON dictionary when that method is called, so there's no easy way to validate whether or not an `NSInteger` that is equal to 0 was actually 0 in the JSON, or "null".

Is it possible to see the original JSON that was used for the parsing by the time `-[MTLModel validate:]` is called? Is there another way to perform nullability validation for primitive number types?

**Comment by robb** [comment]
I would suggest initializing `age` to `NSNotFound` and validate against that. Alternatively, you could subclass `MTLJSONAdapter` and perform custom validation there (e.g. call `-[Person validateWithOriginalJSON:error:]`).

Giving `-[MTLModel validate:]` access to the original JSON would couple it to JSON serialization which is a concern of the adapter.

**Comment by robb** [comment]
Closing this one out for lack of activity, feel free to reopen if the problem persists.

**Comment by nsforge** [comment]
This seems like an unfortunate side-effect of the explicit strict separation of JSON serialisation and validation, but I understand why you've adopted that design philosophy. Thanks for the suggestion!
