### ISSUE TITLE
Mantle tutorial

### ISSUE THREAD

**Issue by bonzoq** [Mantle/Mantle#560]
Hi, 

I'm not sure if it's the best place but I wanted to let you know that I wrote a tutorial on using Mantle with Realm. Hope you could help spread the word. http://www.toptal.com/ios/simplifying-restful-api-use-and-data-persistence-on-ios-with-mantle-and-realm

Thanks!

**Comment by danielgalasko** [comment]
This is a great post, I actually featured this in my Flipboard. That being said I think this isn't the best place to advertise that. @robb please can we close this issue
