### ISSUE TITLE
Possibility to register transformers for base classes

### ISSUE THREAD

**Issue by mojidabckuu** [Mantle/Mantle#565]
Each server created with a lot of problems and to make my life easier and handle cases when my bool value for example string with "Y"/"N", "YES"/"NO","0"/"1" I would like to use transformation implicitly. Also I have the same problem that I receive in JSON `NSString` instead of `NSNumber` and Mantle put using KVC `NSString` object in `NSNumber` property. Is it possible to make implicit transformation to expected property type?

**Comment by robb** [comment]
You can subclass `MTLJSONAdapter` and override [-[MTLJSONAdapter transformerForModelPropertiesOfClass:] or -[MTLJSONAdapter transformerForModelPropertiesOfObjCType:]](https://github.com/Mantle/Mantle/blob/c9ce8e70f1ad143bd7168dbf6341ee869893a6b5/Mantle/MTLJSONAdapter.h#L198-L227) :sparkles:
