### ISSUE TITLE
JSONTransformerForKey hides all properties and require handle all cases

### ISSUE THREAD

**Issue by mojidabckuu** [Mantle/Mantle#566]
`+ (NSValueTransformer *)JSONTransformerForKey:(NSString *)key` method called and expect transformer for my property, but the problem that after calling and return nil value you putted `continue;` statement and deprived me from all other cases. I want to use only one particular case of transformer by key and save default logic. But now it is not possible. Although I can't make any workaround on it except of duplicate logic from `MTLJSONAdapter` by subclassing.

**Comment by robb** [comment]
>  I want to use only one particular case of transformer by key and save default logic.

Would it make sense to implement `+<Key>JSONTransformer` instead then?

**Comment by mojidabckuu** [comment]
I am trying to make some workaround for use some particular transformer where one occur in many other classes. As I understood it is better to inherit JSONAdapter, but I don't like inherit and add some logic to JSON engine :(

**Comment by robb** [comment]
If you'd like to have a JSON adapter that always transforms a certain data type with a custom value transformer, you will end up having to configure the adapter somehow. Why do you object to subclassing `MTLJSONAdapter` and overriding [-[MTLJSONAdapter transformerForModelPropertiesOfClass:] or -[MTLJSONAdapter transformerForModelPropertiesOfObjCType:]](https://github.com/Mantle/Mantle/blob/c9ce8e70f1ad143bd7168dbf6341ee869893a6b5/Mantle/MTLJSONAdapter.h#L198-L227) in this case?

**Comment by mojidabckuu** [comment]
Because I think it is much better to have customization or registering from the kit :)
