### ISSUE TITLE
watchOS 2 support (Mantle 1.5.4) is missing for cocoapods

### ISSUE THREAD

**Issue by mfiebig** [Mantle/Mantle#569]
## Explanation

Version 1.5.4 is missing support for WatchOS 2.

Using a Podfile like

```
...
target 'WatchOS2Target' do
  platform :watchos, '2.0'

  pod 'Mantle', '~> 1.5.0'
end
```

results in the following Error:

```
[!] The platform of the target `WatchOS2Target` (watchOS 2.0) is not compatible with `Mantle (1.5.4)`, which does not support `watchos`.
```
## Solution

Adding the following Line to the Mantle.podspec would solve this issue (Tested locally with development pod mechanism):

```
  s.watchos.deployment_target = "2.0"
```

BTW: Why is there no Podspec in the repository? I'd have created a pull-request if I could.

**Comment by ikesyo** [comment]
Mantle does not officialy support CocoaPods. All the specs are offered by third parties.

**Comment by dcaunt** [comment]
Yes, usual pods disclaimer, but I'll add it to the Podfile for Mantle's next release, presumably 2.0.3 whenever that lands.

In the meantime I'll see if I can PR a change to 1.5.4's Podfile, though technically we're supposed to make a new release. As an aside, I recommend migrating to Mantle 2!

**Comment by mfiebig** [comment]
Thanks for the Feedback!

Migrating to Mantle 2 is not an option right now, as we still need support of iOS 7 (and even 6 for a final short period).

> In the meantime I'll see if I can PR a change to 1.5.4's Podfile, though technically we're supposed to make a new release.

Exactly, that's why I wanted to sync this with you.

**Comment by robb** [comment]
@dcaunt let me know if you need me to tag an old commit 1.5.5 or whatever

**Comment by dcaunt** [comment]
@robb That would be great – then there's no change to the existing spec for 1.5.4. Do you think we should also tag 2.0.3? There are a few bug fixes and performance improvements.

**Comment by robb** [comment]
Can you give me a commit that would work for 1.5.4, I'll tag 2.0.3 right away

**Comment by dcaunt** [comment]
I was thinking we'd just tag against the same commit as 1.5.4, which is d9dc95002cfbf3929d2b70d2c8a77e6bf5b1b88a 

As far as I can see, the subsequent commits are all related to changes in 2.0.

**Comment by robb** [comment]
@dcaunt https://github.com/Mantle/Mantle/releases/tag/2.0.3

**Comment by robb** [comment]
@dcaunt https://github.com/Mantle/Mantle/releases/tag/1.5.5

Thanks for taking care of the Cocoapods side of things

**Comment by dcaunt** [comment]
@robb Many thanks!

@mfiebig I've pushed 1.5.5 and 2.0.3 with watchos 2.0 support. Let me know how you get on. 

FYI, the pod for 2.0 doesn't require iOS 7 or 8 as the code changes are backwards compatible. It is the project structure (frameworks) which requires iOS 8 and therefore the officially supported requirements are iOS 8.

**Comment by dcaunt** [comment]
@robb Can you add a framework zip for Carthage in the 2.0.3 release please?

**Comment by mfiebig** [comment]
@dcaunt Works great, thanks!

I'll have a look at 2.0 then. Maybe you should mention, that it's not a requirement from mantle itself, but the project structure.

I'll leave this ticket open to let you guys finish the Carthage release, ok?

**Comment by robb** [comment]
> Maybe you should mention, that it's not a requirement from mantle itself, but the project structure.

Well, there is not official iOS 7 support in 2.0, it just happens to work with CocoaPods. If we broke this accidental compatibility with 7, we wouldn't bump the major version since we never made any promises.
