### ISSUE TITLE
Parse only certain types of models

### ISSUE THREAD

**Issue by oozywaters** [Mantle/Mantle#572]
I have JSON response looking like this:
```
{
    id: 12345,
    text: "Post text",
    attachments: [{
        type: "photo",
        url: "http://xyz"
    },
    {
        type: "video",
        url: "http://xyz"
    }, 
    {
        type: "note",
        text: "Note text"
    },
    {
        type: "poll",
        content: "Poll content"
    }]
}
```
I know how to parse multiple nested models by implementing a common attachment super class and attachment types subclasses. But this solution requires me to implement every possible type of attachment model (photo, video, note, poll, etc). Is it possible to omit some of JSON objects while serializing models so my attachments array will only consist of photo and video models, for example?

**Comment by robb** [comment]
You could have a custom value transformer for `attachments` that parses the contents of the array using `MTLJSONAdapter` and ignores errors (i.e. cases where `+classForParsingJSONDictionary:` returns `nil`).

**Comment by oozywaters** [comment]
Could you please provide a code example, which demonstrates how to parse an array using `MTLJSONAdapter`?
Now I have the following value transformer:
```
+ (NSValueTransformer *)attachmentsJSONTransformer {
    return [MTLJSONAdapter arrayTransformerWithModelClass:[Attachment class]];
}
```
How should I get an array of attachments?

**Comment by robb** [comment]
Something like this? I didn't run this, but it should give you a rough idea

```objc
+ (NSValueTransformer *)attachmentsJSONTransformer {
    MTLJSONAdapter *adapter = [[MTLJSONAdapter alloc] initWithModelClass:XYAttachment.class];

    return [MTLValueTransformer
        transformerUsingForwardBlock:^(NSArray *attachments, BOOL *success, NSError **error) {
            NSError *internalError;

            NSMutableArray *results = [NSMutableArray arrayWithCapacity:attachment.count];
            for (NSDictionar *JSONDictionary in attachment) {
                XYAttachment *attachment = [adapter modelFromJSONDictionary:JSONDictionary error:&internalError];

                if (attachment == nil && error.code != MTLJSONAdapterErrorNoClassFound) {
                    *error = internalError;
                    *success = NO;
                    return nil;
                } else {
                    [results addObject:attachment];
                }
            }

            return results;
        }
        reverseBlock:^(NSNumber *num, BOOL *success, NSError **error) {
            return // bla
        }];
}
```

**Comment by oozywaters** [comment]
That's exactly what I needed. Thanks for the help.
