### ISSUE TITLE
Asymmetric Value Transformation

### ISSUE THREAD

**Issue by dillan** [Mantle/Mantle#573]
I've been doing a little work with Mantle and have found it be a delightful tool for writing the model layer of applications.

I have a use case where I'm interacting with a web service that uses different representations for data vended via a GET request versus a POST or PUT. For example, the web service responds to GET responses with dates formatted as traditional ISO8601 date strings. For example the GET response might look like:

    {
      "date": "2015-08-02T18:27:01.321Z"
    }

However, POST and PUT requests use a JSON dictionary to represent the date like so:

    {
      "__type": "Date",
      "iso": "2015-08-02T18:27:01.321Z"
    }

I'm wondering if anyone has any best practices for handling this kind of asymmetric behavior using Mantle.

Here is what I've seen:

* `+JSONTransformerForKey:` - Provides the ability to specify the value transformer used for serialization and deserialization. This works great when the values sent to and received from the web service are symmetric. I'm not seeing a clean way of handling asymmetric situations.
* I could create my alternate dictionary representations of my objects for POST and PUT requests, but it feels like there is a cleaner way to handle this situation.
* RestKit - I know RestKit has nifty request and response descriptors that might allow me to map things differently based on request or response type. RestKit is a nice tool for many projects, but I'd like to avoid adding it as a dependency to my project. I'd like to take advantage of many of the NSURLSession features, which are not currently available, due to a RestKit dependency on AFNetworking 1.3.0.

**Comment by robb** [comment]
Hmm, that seems tricky.

Maybe you could subclass `MTLJSONAdapter` to e.g. `XYZTypeAnnotatedJSONAdapter` and use that class for making `POST`/`PUT` requests?

**Comment by dillan** [comment]
Robb,
Good suggestion. It was a bit tricky, but it works. There are fair amount of code overriding the MTLJSONAdapter. If there is interest I would be happy to contribute my solution, but it may need a little clean up.

-Dillan

**Comment by robb** [comment]
It would be lovely to the this as its own repo and I'd be happy to link people your way if they face the same problem. :v:
