### ISSUE TITLE
Searching through NSArray of MTModel

### ISSUE THREAD

**Issue by engmsaleh** [Mantle/Mantle#574]
Is there a way to make Full-Text search on NSArray of MTModels through all of its properties?
For example , if I have NSArray of the below model "EventParticipant" and they are displayed into UITableViewController and I'm using SearchBar for searching, Could I make a predicate or something else to filter through all text properties of the model?

```
@interface EventParticipant : MTLModel <MTLJSONSerializing,MTLManagedObjectSerializing>

@property (nonatomic, copy, readonly) NSNumber *eventParticipantID;
@property (nonatomic, copy, readonly) NSString *eventParticipantFirstName;
@property (nonatomic, copy, readonly) NSString *eventParticipantLastName;
@property (nonatomic, copy, readonly) NSString *eventParticipantBiography;
@property (nonatomic, copy, readonly) NSString *eventParticipantOrganization;
@property (nonatomic, copy, readonly) NSString *eventParticipantPosition;

@property (nonatomic, copy, readonly) NSURL    *eventParticipantAvatar;
@property (nonatomic, copy, readonly) NSString *eventParticipantCity;

@property (nonatomic, copy, readonly) NSURL    *eventParticipantFacebookID;
@property (nonatomic, copy, readonly) NSURL    *eventParticipantTwitterID;
@property (nonatomic, copy, readonly) NSURL    *eventParticipantLinkedInId;
@property (nonatomic, copy, readonly) NSString *eventParticipantEmail;
@property (nonatomic, copy, readonly) NSString *eventParticipantStatus;

@property (readonly, nonatomic, assign, getter = isEventSpeaker) BOOL eventSpeaker;
@property (readonly, nonatomic, assign, getter = isEventParticipantIsDeleted) BOOL eventParticipantIsDeleted;
@property(strong,nonatomic) NSDate *eventParticipantLastModifiedDate;
```

**Comment by dillan** [comment]
You might consider using Apple's Search Kit APIs to do full text search of your model objects. NSHipster has a great article on the subject: http://nshipster.com/search-kit/

I see you class conforms to `MTLManagedObjectSerializing` so I'm guessing you are using Core Data. You might take a look around for full text search when using Core Data. For example, https://github.com/indragiek/SNRSearchIndex looks interesting.

**Comment by engmsaleh** [comment]
Thanks @dillan  for your reply.
I have checked the links that have provided , but it seems that they all work with the CoreData directly.
The point that you have refereed to is right , I'm using the CoreData for saving local data, but the point here that when I'm conducting the search I'm using NSArrays of the objects from Mantle models , that is already have been fetched from CoreData , so I will search through them , not through CoreData entities.

So, Do anything apply to my current situation or their are a best practice for better approach? Please advice

**Comment by dillan** [comment]
@engmsaleh Search Kit actually doesn't work with Core Data directly. It can be used to index a collection of custom model objects for full text search.

Another approach that might work, depending on the size of your data set, is to add a search string property to your model class that simply concatenates all of the attributes you are interested in searching into a single string. Then it would just be a matter of running your predicate to filter your array of objects.

    NSArray *eventParticipants = [self myCollectionOfAllEventParticipants];
    NSPredicate *searchStringPredicate = [NSPredicate predicateWithFormat:@"SELF.searchString CONTAINS[cd] %@", searchTerm];
    NSArray *searchResults = [eventParticipants filteredArrayUsingPredicate:searchStringPredicate];
