### ISSUE TITLE
Question: Mantle 2.0.3

### ISSUE THREAD

**Issue by chrisdhaan** [Mantle/Mantle#576]
I recently updated to Mantle 2.0.3 via Cocoapods. I am using Mantle and Overcoat in my application to return Yelp data and after updating I no longer received data back from my networking calls. I was wondering what specific changes might have changed from 2.0.2 to 2.0.3 to cause this issue. Thanks.

**Comment by dcaunt** [comment]
If you pin to 2.0.2 does it definitely resolve the issue?

Here's the [list of new commits](https://github.com/Mantle/Mantle/compare/2.0.2...2.0.3) in the [2.0.3 release](https://github.com/Mantle/Mantle/releases/tag/2.0.3). 

Without knowing which features you use, I wonder if you are a victim of the validation fix in https://github.com/Mantle/Mantle/pull/532

**Comment by chrisdhaan** [comment]
Yes. I reset my changes and pinned to 2.0.2 and the issue was resolved. I was able to receive data back from Yelp. Then going back to 2.0.3 I no longer received any more data. I tried this three time just to make sure updating to 2.0.3 was the culprit. Thanks for the links to the list of commits and #532. I'll see if they help.

**Comment by chrisdhaan** [comment]
Attached is the line of code that changed that has caused me to stop receiving data back. I could post my class in which I'm defining my MTLModel if that would help. Is there new validation that needs to be handled to take the attached code change into account?

![github change](https://cloud.githubusercontent.com/assets/5225621/9087938/9954f8e6-3b5b-11e5-9f89-4154facb9052.png)

**Comment by robb** [comment]
what's the value of `propertyClass` here?

**Comment by chrisdhaan** [comment]
The value of propertyClass is null. But it doesn't seem to default to the NSObject.class.

**Comment by robb** [comment]
Well if `propertyClass` is `nil`, then `nil ?: NSObject.class` will evaluate to `NSObject.class`.

Is your call to `MTLJSONAdapter` giving you an error?

**Comment by sergey-sportsetter** [comment]
@chrisdhaan Mantle has a great way of reporting serialisation errors (you can easily spot it in MTLJSONAdapter), which Overcoat completely ignores
Related issue: Overcoat/Overcoat#105

Just fixed a similar issue, in my case my properties were declared as ```objective-c NSString``` instead of ```objective-cNSObject```

**Comment by chrisdhaan** [comment]
@sergey-sportsetter Thanks for the tip. I will look into that this weekend and see if it fixes my issue.

**Comment by chrisdhaan** [comment]
@sergey-sportsetter This fixed the issue I was having. Thanks so much for the help. Closing this issue.
