### ISSUE TITLE
Variable keys for properties

### ISSUE THREAD

**Issue by mojidabckuu** [Mantle/Mantle#577]
Sometimes server side is not perfect. Everybody knows. And the same model can have different keys in json. Also if you are using different services for this. And task about aggregation different all keys to one model becomes your problem.
So mantle doesn't support variable keys in `JSONKeyPathsByPropertyKey` may be it can become a good feature.
For my particular issue I need transform `imageURL` that comes from the server with different keys like `image_url`, `image`, `photoURL`. I putted an array to `JSONProperties` and `JSONAdapter` grabs matched valuse to `NSDictionary` and calls `NSValueTransformer` with `MTLURLValueTransformerName` name which counts on `NSString` object as value. So it gives me an error.
What I can do in this situation?

**Comment by robb** [comment]
I would suggest using a class cluster that maps the `imageURL` property to the different keys if you know them in advance. Otherwise, I guess you could look into subclassing `MTLJSONAdapter`?
