### ISSUE TITLE
Object de/serialization lifecycle

### ISSUE THREAD

**Issue by gvaish** [Mantle/Mantle#583]
Couldn't find in the documentation and in the code.

It will be great if the objects have an extended life-cycle post-serialization and pre-deserialization. For example:
#### De-serialization / Object Construction
1. Get properties (exists)
2. De-serialize using transformer (exists)
3. Invoke a (new) method declared in the class `MTLModel` `[- objectDidDeserialize]` or an extended form `[- objectDidDeserializeFromDictionary:(NSDictionary *)dictionary]`. (does not exist)
   - The `MTLModel` sub-classes can override this method.
#### Serialization
1. Invoke a (new) method declared in the class `MTLModel` `[- objectWillSerialize]` or an extended form `[- objectWillSerializeToDictionary:(NSMutableDictionary *)dictionary]` (does not exist)
   - The `MTLModel` sub-classes can override this method.
2. Get properties (exists)
3. Serialize using transformer (exists)
#### Reasons

Object can perform some operations immediately after construction. For example, in cases where the JSON keys are dynamic (say, based on values from other keys), complete object construction may not have happened and those dynamic JSON keys may have been left as a `NSDictionary` in the model-class.

Similarly, objects can push complex or dynamic states in a structured form during serialization.

Thoughts?

**Comment by robb** [comment]
Thanks for your suggestion :sparkling_heart: 

So we're talking about basically calling `-modelDidSerializeFromDictionary:` as the last step in `-modelFromJSONDictionary:error:` and `-modelWillSerializeToDictionary:` as the first step in `-JSONDictionaryFromModel:error:`?

If so, you should already be able to achieve the former by subclassing `MTLJSONAdapter`. For the latter, I don't really see when this would be useful – can you provide an example? I'm specifically worried that the model will modify the `NSMutableDictionary` in a way that will conflict with the things `MTLJSONAdapter` does (coupling, yadda yadda).

**Comment by gvaish** [comment]
@robb How about the following?

```
-(void)objectDidDeserialize:(NSDictionary *)dictionary;

-(NSDictionary *)objectWillSerialize;
```

As far as sub-classing `MTLJSONAdapter` is concerned, it will be great if it was a first-class citizen of the core framework itself.

**Comment by robb** [comment]
> How about the following?

Both methods are JSON specific, so they should reflect that somehow, e.g.:

```objc
- (void)modelDidDeserializeFromJSONDictionary:(NSDictionary *)JSONDictionary;

- (NSDictionary)modelWillSerializeToJSONDictionary;
```

However, I'm even less sure what kind of logic I would put into the `-modelWillSerializeToJSONDictionary`, what use-case are you trying to solve that you can't already?

Mantle's philosophy thus far has been to favor models as much as value types as Objective-C allows us to, I'm worried that these methods are going to invite logic to be placed into the model that should maybe go into an adapter subclass. (But again, not sure what use case you have).

> As far as sub-classing MTLJSONAdapter is concerned, it will be great if it was a first-class citizen of the core framework itself.

Given how long we've managed to do without, I'm hesitant to increase the (albeit potentially `@optional`) surface area of the `MTLModel` protocol.
