### ISSUE TITLE
watch OS 2 error with Carthage or CocoaPods

### ISSUE THREAD

**Issue by bmueller** [Mantle/Mantle#584]
I was completely unable to get Mantle running with a manual installation and through CocoaPods in Xcode 7, so I finally gave up and tried Carthage instead. 

The install seems to have gone fine and the project can see the Mantle.h file, but now I'm getting the following error: 

![image](https://cloud.githubusercontent.com/assets/2242284/9210135/7a0380ba-4048-11e5-84a3-ada0b12fce3b.png)

How do I add watch OS 2 support to Mantle? This is getting very frustrating, as I've been doing nothing but trying to get Mantle running for the last 24 hours.

**Comment by bmueller** [comment]
Tried switching back to Cocoapods, and this is the error I'm getting in watchOS 2: 

![image](https://cloud.githubusercontent.com/assets/2242284/9211192/78f167ea-404e-11e5-96e8-2d17bdbea18b.png)

The main app runs fine. 

Tried this with both Mantle 2.0.3 and 1.5.5.

**Comment by ikesyo** [comment]
> The install seems to have gone fine and the project can see the Mantle.h file, but now I'm getting the following error:

It seems that you didn't link the framework in `Carthage/Build/watchOS` for watchOS app target, but linked one in `Carthage/Build/iOS`. Because the two platforms has different architectures, you can't link one to the other platform.

**Comment by bmueller** [comment]
When I ran everything through Carthage, I only got an iOS and a Mac framework. Was it supposed to create a folder with a watchOS framework as well?

**Comment by ikesyo** [comment]
Ah, Mantle itself does not have watchOS target. You could create a pull request that introduce watchOS target.

**Comment by robb** [comment]
Yeah, we'd :heart: to review a Pull Request to that extend.

**Comment by AriX** [comment]
See #598 (heads-up: not tested whether or not this still builds properly in Xcode 6, which doesn't know what a Watch Framework is)
