### ISSUE TITLE
NSDictionary (MTLJSONKeyPath)  has a bug!

### ISSUE THREAD

**Issue by angryapes** [Mantle/Mantle#587]
I use this api:http://api.openweathermap.org/data/2.5/weather?lat=39.996200&lon=116.461039&units=imperial

This is mycode to serialize my model objects from JSON:

```objc
    + (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"date": @"dt",
             @"locationName": @"name",
             @"humidity": @"main.humidity",
             @"temperature": @"main.temp",
             @"tempHigh": @"main.temp_max",
             @"tempLow": @"main.temp_min",
             @"sunrise": @"sys.sunrise",
             @"sunset": @"sys.sunset",
             @"conditionDescription": @"weather.description",
             @"condition": @"weather.main",
             @"icon": @"weather.icon",
             @"windBearing": @"wind.deg",
             @"windSpeed": @"wind.speed",
             };
}
```

I cannot get model from json with the method "+ (id)modelOfClass:(Class)modelClass fromJSONDictionary:(NSDictionary *)JSONDictionary error:(NSError **)error {
".

I think your code have a problem in class of "NSDictionary+MTLJSONKeyPath.h".

**Comment by ikesyo** [comment]
The value of `weather` key in the response JSON is an array of dictionary:

```
"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}]
```

So `@"condition": @"weather.main"` and `@"icon": @"weather.icon"` are not collect mapping.

**Comment by angryapes** [comment]
Thank you for your reply.But, how should I solve this problem?

**Comment by ikesyo** [comment]
One possible solution is:

```objc
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             ...
             @"conditionDescription": @"weather",
             @"condition": @"weather",
             @"icon": @"weather",
             ...
             };
}

+ (NSValueTransformer *)conditionDescriptionJSONTransformer {
    return [MTLValueTransformer transformerUsingForwardBlock:^id(NSArray *weather, BOOL *success, NSError **error) {
        return [weather.firstObject valueForKey:@"description"];
    }];
}

// Do the same with `condition` and `icon`
```

But I didn't test it, I'm not sure if it works correctly.

**Comment by robb** [comment]
Yeah, there really isn't a way for Mantle to specify a mapping into an JSON array right now and I don't think it's something that the framework should handle. I'm with @ikesyo that custom value transformers are probably the way to go :v:
