### ISSUE TITLE
On implicit transformations from JSON

### ISSUE THREAD

**Issue by zintus** [Mantle/Mantle#588]
I've just started using Mantle in our project and ran in counterintuitive behaviour during mapping nested JSON objects on nested objects hierarchy. There are two implicit transformers applied: boolean transformer and URL transformer, however no transformation is made for properties which type is conforming to `MTLJSONSerializing` protocol. I think we can safely apply `dictionaryTransformerWithModelClass` in this case.
What do you think about supporting such feature?

I've looked for way such implicit transform may be applied and found that documentation on `transformerForModelPropertiesOfClass` says that NSURL conversion is supported, but i can't find any signs of corresponding transformer applied. 
Can you point me to the related class/function?

PS Thanks for awesome job on Mantle! 🎯

**Comment by robb** [comment]
Thanks for the suggestions :sparkling_heart: 

There is #533 to address your first point. /cc @younthu

> Can you point me to the related class/function?

Of course. The transformer is declared [here](https://github.com/Mantle/Mantle/blob/6a9bd2687b9d32602c20f4c7f290900636454aaf/Mantle/MTLJSONAdapter.m#L635-L637) and invoked from [here](https://github.com/Mantle/Mantle/blob/6a9bd2687b9d32602c20f4c7f290900636454aaf/Mantle/MTLJSONAdapter.m#L445-L452).

**Comment by zintus** [comment]
Exactly my thoughts in PR discussion.

After staring at function body for another 5 minutes, i've got that `NSStringFromClass(modelClass)` will produce class name, not property name 😶

Thanks for instant response!

**Comment by robb** [comment]
Happy to help :-)
