### ISSUE TITLE
Mantle fails with Carthage version 0.8.0

### ISSUE THREAD

**Issue by praveencastelino** [Mantle/Mantle#589]
Mantle Entry in Cartfile:
github "Mantle/Mantle"

I'm getting the following error when i try "carthage update"
*** Fetching Mantle
A shell task failed with exit code 128:
fatal: Not a git repository (or any of the parent directories): .git

I have Xcode verison 6.4 (6E35b)

**Comment by mdiep** [comment]
I think this is an issue with Carthage's cache. Can you try deleting `~/Library/Caches/org.carthage.CarthageKit` and running `carthage` again?

**Comment by praveencastelino** [comment]
I was setting up my new mac book pro and that didn't have github private key installed in .ssh folder. Though i could fetch other repos, it failed only with Mantle. Once the keys are installed, everything worked fine.
