### ISSUE TITLE
when i opened Mantle.xcworkspace file, these question come out

### ISSUE THREAD

**Issue by ForeverHepburn** [Mantle/Mantle#591]
the file “Debug.xcconfig” couldn’t be opened because there is no such file。
The file “iOS-Framework.xcconfig” couldn’t be opened because there is no such file. (/Users/issuser/Downloads/Mantle-master-2/Carthage/Checkouts/xcconfigs/iOS/iOS-Framework.xcconfig)

**Comment by ikesyo** [comment]
Those files are managed by `xcconfigs` submodule, so you should run `git submodule update --init --recursive` at the repository's root.

**Comment by dcaunt** [comment]
Alternatively you can run `script/bootstrap` [as described in the README](https://github.com/Mantle/Mantle#importing-mantle) and it'll fetch submodules and do anything else that may be required.
