### ISSUE TITLE
Using MTLJSONAdapter with a nil JSON returns an object in Release mode and Nil in Debug mode

### ISSUE THREAD

**Issue by danielgalasko** [Mantle/Mantle#592]
I came across an interesting bug in Mantle that revealed itself once running tests under release mode. The issue seems to be that when the compiler optimisation level is bumped to to say `-[Os](Fastest, Smallest)` then the behaviour of `[MTLJSONAdapter modelOfClass:fromJSONDictionary:error:]` is undefined when the JSON dictionary is nil.

This actually occurs at line 307 of `MTLJSONAdapter`[here](https://github.com/Mantle/Mantle/blob/6a9bd2687b9d32602c20f4c7f290900636454aaf/Mantle/MTLJSONAdapter.m) specifically:

	BOOL success;
	value = [JSONDictionary mtl_valueForJSONKeyPath:JSONKeyPaths success:&success error:error];

	if (!success) return nil;//Compiler skips this
	
For some reason with compiler optimisation turned up, the compiler actually skips the if statement and breaks out of the else and straight into the next try-catch. Simply updating the if statement to:

    if (!success || !value) {
        return nil;
    }

Causes the test to pass. 

Here's a simple test case I constructed to test this (see below) and running the test under Debug mode succeeds. Changing to Release fails. Any thoughts on why this happens?

I have added this test case in [my fork](https://github.com/danielgalasko/Mantle/tree/bug-%23592)

	@interface MTLJSONTestModel : MTLModel<MTLJSONSerializing>
	@property (nonatomic, copy, readonly) NSString *property;
	@end
	
	@interface MTLModelJSONTests : XCTestCase
	@end

	@implementation MTLModelJSONTests

	- (void)testInitializingWithNilJSONReturnsNil {
		NSError *error;
		MTLJSONTestModel *mod = [MTLJSONAdapter modelOfClass:[MTLJSONTestModel class] fromJSONDictionary:nil error:&error];
		XCTAssertNil(error);
		XCTAssertNil(mod);
	}

	@end
	
	@implementation MTLJSONTestModel

	+ (NSDictionary *)JSONKeyPathsByPropertyKey {
		return @{NSStringFromSelector(@selector(property)) : @"jsonkey"};
	}

	@end

So that leads me to question what the expected behaviour of MTLJSONAdapter should be with nil JSON. I think its reasonable to assume that nil JSON should return a nil object by default? 

Happy to submit a PR if this is the case although I don't fully understand what the compiler is doing

**Comment by robb** [comment]
Would you mind running your test against the changes in #593?

**Comment by robb** [comment]
Whoops, apologies.

**Comment by danielgalasko** [comment]
@robb that was my first port of call, unfortunately it doesn't have any effect... most unusual

**Comment by robb** [comment]
:poop:

**Comment by danielgalasko** [comment]
Wait @robb my apologies, strangely it seems to be working now. Give me a minute to properly audit everything

**Comment by danielgalasko** [comment]
@robb that fixes the issue, thanks! 👍
