### ISSUE TITLE
In my project，When the variable type for NSInteger crash。

### ISSUE THREAD

**Issue by duxinfeng** [Mantle/Mantle#595]
Hi,
Server response:

```
{
    "count": 53222,
    "title": "小猴几，跟我学，吐舌头~",
    "url": "http://haojiazhang123.com",
    "label": "开心一刻",
    "subtype": 0,
    "qid": 487
}
```

```objc
@property (nonatomic, assign) NSInteger count;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, strong) NSURL *url;
@property (nonatomic, copy) NSString *label;
@property (nonatomic, assign) NSInteger qid;
@property (nonatomic, assign) NSInteger subtype;
//@property (nonatomic, copy) NSNumber *subtype;
```

When a “subtype”  is NSInteger type, My project crash.
When a “subtype”  is NSNumber type, it works properly.Other variable types is normal。

Thanks again！

**Comment by robb** [comment]
You're probably not handling `nil` values for primitive types. Try implementing [`-setNilValueForKey:`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Protocols/NSKeyValueCoding_Protocol/#//apple_ref/occ/instm/NSObject/setNilValueForKey:), maybe?

**Comment by duxinfeng** [comment]
You're right，Thanks again！

I realized setNilValueForKey method, then normal.

- (void)setNilValueForKey:(NSString *)key{
    if ([key isEqualToString:@"subtype"]) {
        self.subtype = 0;
    }
    else{
        [super setNilValueForKey:key];
    }
}

**Comment by robb** [comment]
:ok_hand:

**Comment by billxie1988** [comment]
@robb why mantle transfer NSInteger 0 to <nil>
<DateLimitResponseModel: 0x604001c71700> {
    durationLimit = 2;
    durationLimitUnit = 1;
    endTimeLimit = 1;
    endTimeLimitUnit = 5;
    startTimeLimit = 0;
    startTimeLimitUnit = 1;
}
(lldb) po self.limitModel.startTimeLimit
<nil>
(lldb) po self.limitModel.endTimeLimit
1
