### ISSUE TITLE
Question :Why not cache MTLJSONAdapter for model class?

### ISSUE THREAD

**Issue by CodeLife2012** [Mantle/Mantle#596]
Recreate MTLJSONAdapter each time seems strange，is there some reason to do do?

**Comment by robb** [comment]
It makes a lot of sense to cache instances `MTLJSONAdapter` e.g. in your API layer, but it's simpler for everyone if Mantle caches as little as reasonable out of the box. ✌

**Comment by CodeLife2012** [comment]
Thanks for you reply
