### ISSUE TITLE
Question:How to valid a array of NSString during tranfrom?

### ISSUE THREAD

**Issue by CodeLife2012** [Mantle/Mantle#597]
May be I can do this during validate.

**Comment by robb** [comment]
Not sure how you'd like to validate your strings, but have you checked out the [Key-Value Validation guide](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/KeyValueCoding/Articles/Validation.html)?

**Comment by CodeLife2012** [comment]
oh, I want to validate whether these strings really NSStrings or not.

**Comment by robb** [comment]
You could try something like:

```objc
- (BOOL)validateNames:(NSArray **)names error:(NSError **)error {
    for (id obj in *names) {
         if (![obj isKindOfClass:NSString.class]) {
             // TODO: populate `error`
             return NO;
         }
    }

    return YES;
}
```
