### ISSUE TITLE
Array of keys doesn't allow keypaths

### ISSUE THREAD

**Issue by jostster** [Mantle/Mantle#602]
I have a Contact model that comes in different object forms from the API. sometimes it is wrapped in a "contact" dictionary and sometimes it is not.
```
+ (NSDictionary*)JSONKeyPathsByPropertyKey {
	return @{
			 
			 @"fullName"        : @[@"contact.full_name", @"full_name"],
			 @"email"			: @[@"contact.email", @"email"],
			 @"userId"			: @[@"contact.id", @"id"],
			 @"avatar"			: @[@"contact.avatar", @"avatar"]
			 
			 };
}
```

will return the error
```
Contacts Error: Error Domain=MTLTransformerErrorHandlingErrorDomain Code=1 "Value did not match expected type" UserInfo=0x7ff43b438e30 {MTLTransformerErrorHandlingInputValueErrorKey={
    "contact.email" = "test@email.com";
}, NSLocalizedDescription=Value did not match expected type, NSLocalizedFailureReason=Expected {
    "contact.email" = "test@email.com";
} to be of class NSString but got __NSDictionaryM}
```

It appears the issue is it is reading the contact dictionary instead of the email field inside the contact dictionary.

**Comment by robb** [comment]
Mapping a property to an array is used for composite properties, not fallbacks.

I'd recommend using a class cluster in this case, where you'd have a different `+ JSONKeyPathsByPropertyKey` depending on whether you expect the `contact` dictionary to be present in the JSON.
