### ISSUE TITLE
Relative URL Value Support

### ISSUE THREAD

**Issue by donpark** [Mantle/Mantle#607]
Relative URLs are fairly common in JSON responses. What's the Mantle way to convert them into full URLs?

Key problems I see are 1) there is only one instance of MTLJSONAdapter and 2) absence of support for contextual information relevant to unmarshaling.

**Comment by robb** [comment]
> there is only one instance of `MTLJSONAdapter`

Not sure what you mean, you may create as many instances as you'd like. If they share state, it's a bug.

> absence of support for contextual information relevant to unmarshaling.

Have you considered subclassing `MTLJSONAdapter` and adding this contextual information?

**Comment by donpark** [comment]
I'll give that a try. Re multiple instance, my bad. Was too lazy to dig beyond Mantle API. :-)
