### ISSUE TITLE
Undefined symbols for architecture i386:

### ISSUE THREAD

**Issue by NorbertSzydlowski** [Mantle/Mantle#609]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_MBase", referenced from:
      _OBJC_CLASS_$_MVersion in MVersion.o
  "_OBJC_METACLASS_$_MBase", referenced from:
      _OBJC_METACLASS_$_MVersion in MVersion.o
ld: symbol(s) not found for architecture i386

Any idea?

@interface MBase : MTLModel <MTLJSONSerializing>
@interface MVersion : MBase

**Comment by robb** [comment]
There is probably something set up incorrectly on your end. How did you integrate Mantle?

**Comment by NorbertSzydlowski** [comment]
With cocoapods.

I have got this error after I added nested Mantle object
