### ISSUE TITLE
Parse nested model using Mantle, nested object remains dictionary

### ISSUE THREAD

**Issue by andr3a88** [Mantle/Mantle#612]
I've a problem with nested object model with Mantle. In the JSON response, profile becomes an object of MTLUser and twitterProfile dictionary it should be of type MTLTwitterUser. 

The problem is that twitterProfile remains a dicitonary instead of a MTLTwitterUser.

I did step through `[MTLJSONAdapter transformerForModelPropertiesOfClass:MTLTwitterUser.class]` and return nil but I cannot understand why.

JSON response

```
{
    data =     {
        profile =         {
            name = "";
            token = "";
            tokenSecret = "";
            twitterId = "";
            twitterProfile =             {
                "created_at" = "Fri Aug 30 09:54:46 +0200 2013";
                ........
            };
            username = "";
        };
    };
    status = success;
}
```

 MTLUser.h

```
@interface MTLUser : MTLModel <MTLJSONSerializing>
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *twitterId;
@property (nonatomic, copy) NSString *token;
@property (nonatomic, copy) NSString *tokenSecret;
@property (nonatomic, strong) MTLTwitterUser *twitterProfile;
@end
```

MTLUser.m

```
+ (NSDictionary *)JSONKeyPathsByPropertyKey {

       return @{
         @"name": @"name",
         @"twitterId": @"twitterId",
            ....
         @"twitterProfile": @"twitterProfile",
            ...
         };
    }

#pragma mark - JSONTransformer

+ (NSValueTransformer *)twitterProfileJSONTransformer {
    return [MTLJSONAdapter transformerForModelPropertiesOfClass:MTLTwitterUser.class];
}
```

 MTLTwitterUser.h

```
@interface MTLTwitterUser : MTLModel <MTLJSONSerializing>
@property (nonatomic, copy) NSString *idStr;
.....
....
@end
```

**Comment by robb** [comment]
> I did step through [MTLJSONAdapter transformerForModelPropertiesOfClass:MTLTwitterUser.class] and return nil but I cannot understand why.

Are you using the latest `master`? `2.0.4` does not include implicit parsing.

**Comment by andr3a88** [comment]
I'm using Mantle with cocoapods:
pod 'Mantle', '~> 2.0'

**Comment by robb** [comment]
I don't think you can easily use the current `HEAD` with CocoaPods.

@dcaunt Would you mind tagging `HEAD` and updating the `podspec`? :bow:

**Comment by andr3a88** [comment]
without implicit parsing how can I fix?

**Comment by robb** [comment]
[Simple, just implement `+ twitterProfile JSONTransformer`](https://github.com/Mantle/Mantle#jsontransformerforkey) :v:

**Comment by andr3a88** [comment]
Like this ?
 
     + (NSValueTransformer *)JSONTransformerForKey:(NSString *)key {
         if ([key isEqualToString:@"twitterProfile"]) {
             return [MTLJSONAdapter transformerForModelPropertiesOfClass:MTLTwitterUser.class];
         }
         return nil;
     }

I always twitterProfile as a dictionary instead of MTLTwitterUser

![error](https://cloud.githubusercontent.com/assets/6755254/9854059/19b784f2-5b07-11e5-8bea-479cd4453db0.png)

**Comment by robb** [comment]
more like

```objc
// MTLUser.m

+ (NSValueTransformer *)twitterProfileJSONTransformer {
    return [MTLJSONAdapter dictionaryTransformerWithModelClass:MTLTwitterUser.class];
}
```

**Comment by andr3a88** [comment]
to save bool and long is best pass through NSNumber? I find out the problem.... maybe!

**Comment by andr3a88** [comment]
I have a parse error "Expected 1 to be of class NSNumber but got NSTaggedPointerString" when i'm parsing nested object. 

How can figure out the object that has parsing problem? Nested objects  are similar to the following:

    + (NSValueTransformer *)twitterProfileJSONTransformer {
        return [MTLJSONAdapter dictionaryTransformerWithModelClass:MTLTwitterUser.class];
    }

    + (NSValueTransformer *)servicesJSONTransformer {
        return [MTLJSONAdapter arrayTransformerWithModelClass:[MTLService class]];
    }

    + (NSValueTransformer *)openingHoursJSONTransformer {
        return [MTLJSONAdapter arrayTransformerWithModelClass:MTLOpeningHours.class];
    }

**Comment by zhentan** [comment]
I'm having a similar issue where the nested object comes in as a nil if I use dictionaryTransformerWithModelClass: in the <key>JSONTransformer. However if i use transformerForModelPropertiesOfClass: instead I get the json dictionary. Either case I don't get the mapped Class object. Similar things has happened to me before when I have a key spelled incorrectly. What is the best way to debug this issue?

**Comment by asad-propelics** [comment]
same thing happening for me

**Comment by dcaunt** [comment]
@asad-propelics please open a new issue including a sample of your JSON and the relevant model header/implementation and I can take a look.
