### ISSUE TITLE
Reference of 'delegate' object

### ISSUE THREAD

**Issue by hisavali** [Mantle/Mantle#613]
Hi,

I have an object graph -- A owns B and B weakly refer to A (i.e delegate).

Whilst populating A, value transformer for B is supplied via `BJSONTransformer`. When `initWithDictionary:error:` is called on B, I need to populate `delegate` property by assigning object of 'A'.

JSON Structure:
```
A = {
    ...
    B = {
        ...
        C = [{},{}]
        ...
    }
    ...
}
```

I'm not sure how to inject/pass object of A to `dictionaryValue` such that it can be used by 'B'.

Thanks in advance and please let me know if more information is needed.

**Comment by robb** [comment]
Have you tried overriding the setter for B?

**Comment by hisavali** [comment]
Thanks for prompt response :+1: 

As graph traversing is depth-first, Mantle attempts to instantiate/populate C, B and then A. i.e `initWithDictionary:error:` of C gets invoked first, then of B and of A. 

Just before `initWithDictionary:error:` for B gets called, I wish to update`dictionary` parameter such that I can pass more information to about A which will be used by B during initialisation.

I'm not sure what you mean by overriding the setter. May I request you to elaborate.

**Comment by robb** [comment]
> Just before initWithDictionary:error: for B gets called, I wish to updatedictionary parameter such that I can pass more information about A in it which will be used by B during initialisation.

I think that would require subclassing `MTLJSONAdapter`, how about you instead do something like 

```objc
// A.m

- (void)setB:(B *)b {
    _b = b;
    _b.delegate = self;
}
```

**Comment by hisavali** [comment]
Thanks again for your response.

`setB:` will be defined once object of A is created. Requirement I have is to pass specific information which B will use during initialisation of itself.

**Comment by robb** [comment]
It's not easy discussing this problem in the abstract – are you actually setting a reference to the outside `A` instance? If so, you have a circular reference (not necessarily a retain cycle, assuming the reference is `weak`).

Since the instance of `B` is created by `MTLJSONAdapter` before the instance of `A` is – after all, `b` is a member of the dictionary passed to `-[A initWithDictionary:error:]` – no reference to the instance of `A` can be created since it doesn't exist at this point. 

If you just need access to some of the properties in the outer `A` JSON dictionary (which contains `B`), you could use a custom value transformer as well as [mapping `b` to multiple key paths in the `A` JSON dictionary](https://github.com/Mantle/Mantle/blob/7690ba79443e233ae2eaea8e5b85d6c2f249cb28/Mantle/MTLJSONAdapter.h#L24-L50).

**Comment by hisavali** [comment]
I agree it is bit odd to explain but you summed up accurately (that's what I meant by depth-first creation order):

> Since the instance of B is created by MTLJSONAdapter before the instance of A is – after all, b is a member of the dictionary passed to -[A initWithDictionary:error:] – no reference to the instance of A can be created since it doesn't exist at this point.

I don't need to access the property in outer `A` JSON, but need to add a new key-value to `dictionary` which will be passed to `-[B initWithDictionary:error:]`. This new key-value info would be extracted based on certain logic taking place at `A`. That's where I was wondering if I can override a method by sub-classing `MTLJSONAdaptor` for `A` such that it can modify `dictionary` by adding new key-value.

I hope I'm making myself clear. If not, please don't hesitate to ask more info.

Thanks for your patience.

**Comment by robb** [comment]
You could have a class cluster of `A`, where you implement `+[A classForParsingJSONDictionary:]` and each subclass of `A` has a different value transformer for `b`.

Alternatively, try something like:

```objc
// A.h
+ (NSDictionary *) JSONKeyPathsByPropertyKey {
    return @{
        @"b": @[ @"b", @"otherPropertyInA" ]
    };
}

+ (NSValueTransformer *)bJSONTransformer {
    // Return a NSValueTransformer that gets a dictionary like 
    //     @{
    //         @"b": @{ ??? }
    //         @"otherPropertyInA": ???
    //     }
    // and returns a `B` instance.
}
```

?

**Comment by hisavali** [comment]
Thank for your input. I have opted for customising value transformer for `B`.I'm closing this issue (rather question).  Thanks again. And keep up the great work. :smiley:
