### ISSUE TITLE
-[MTLJSONAdapter dictionaryTransformerWithModelClass:] possible multithreading problem

### ISSUE THREAD

**Issue by YuAo** [Mantle/Mantle#615]
Encountered a strange problem with Mantle recently.

Program crashes in `-[MTLJSONAdapter modelFromJSONDictionary:error:]`. The debugger complains that `self` is not a `MTLJSONAdapter` instance (but a `__NSDictionaryM`).

![untitled](https://cloud.githubusercontent.com/assets/1234944/9986786/4c542f16-6073-11e5-8810-6bcd7fb07263.png)

However, when checking `-[MTLJSONAdapter dictionaryTransformerWithModelClass:]` in the stack trace, that `adapter` is indeed a valid `MTLJSONAdapter`.

![qq20150921-1 2x](https://cloud.githubusercontent.com/assets/1234944/9986733/c97ea756-6072-11e5-8779-55dcba65ccc1.png)

I'm not sure what causes this problem. 

I think it may be related to multithreading: In the screenshot, `Thread 12` is entering `-[MTLJSONAdapter dictionaryTransformerWithModelClass:]` as well.

I also noticed that the `adapter` is created with  `__block MTLJSONAdapter *adapter;`. Is there a possibility that the `__block` keyword makes the `adapter` to be thread-unsafe.

**Comment by carsonperrotti** [comment]
Experiencing the same issue. My stack trace also seems to show a similar pattern.

**Comment by erduoniba** [comment]
the same to me, so i pod mantle to 2.0

**Comment by tuzcsaba** [comment]
Hi. We are experiencing the same crashes. 

I've written a test, which executes 100 mappings in parallel, and it reproduces the crash 99% of the time. 

By removing the `__block` variable and instead making the transformer instantiate a new adapter each time it transforms (highly inefficient), the crashes are gone, still I don't believe that is a proper solution.

After that gave a try to instantiating `MTLJSONAdapter` outside the transformer blocks (dropping lazy instantiation this way). Better than the first approach, and this also made the issue go away (according to my test).

I can't say I understand what causes the phenomena. A non-invasive workaround we found was to Synchronise usages of MTLJSONAdapter on `[MTLJSONAdapter class]`, but this has a hit on the throughput, though not major.
