### ISSUE TITLE
Conforming to MTLModel protocol in Swift

### ISSUE THREAD

**Issue by startupthekid** [Mantle/Mantle#616]
Instead of using Core Data, I've decided to give [Realm](http://realm.io) a shot. Due to Mantle 2.0, it was now possible to do that; model subclasses could simply conform to the `MTLModel` protocol or `MTLModelProtocol` as it gets renamed in Swift.

However doing this lead to a whole host of issues. 
First and foremost, the Objective-C implementation of `MTLModel` does some extreme heavy lifting, using the objc-runtime and whatnot, something Swift doesn't have natively. You can get around this by importing the runtime and doing the same things in Swift as are done previously but that will stop working once Objective-C leaves our lives (which granted, isn't for a couple of years at least).

Secondly, even if I do conform to `MTLModel` and just have stub implementations of every required method, compilation always errors out. Specifically on the `validate` method in the protocol, I get these two errors:

`Protocol requires function 'validate()' with type '() throws -> ()'`
and 
` Objective-C method 'validateAndReturnError:' provided by method 'validate()' does not match the requirement's selector ('validate:')`

where my function looks like: 
```
@objc func validate() throws {

}
```

and the Swift generated interface of `MTLModel` looks like:
```
public protocol MTLModelProtocol : NSObjectProtocol, NSCopying {
    @available(iOS 2.0, *)
    public static func modelWithDictionary(dictionaryValue: [NSObject : AnyObject]!) throws -> Self
    @available(iOS 2.0, *)
    public var dictionaryValue: [NSObject : AnyObject]! { get }
    @available(iOS 2.0, *)
    public init(dictionary dictionaryValue: [NSObject : AnyObject]!) throws
    public func mergeValueForKey(key: String!, fromModel model: MTLModelProtocol!)
    @available(iOS 2.0, *)
    public static func propertyKeys() -> Set<NSObject>!
    public func validate() throws
}
```

Am I going about this all wrong? Is there a proper way to conform to this protocol in Swift or is that out of the question?

**Comment by robb** [comment]
Hmm, seems like the interplay of `throws` with `objc` protocol error pointers is acting up. Does `validate(out error: NSError)` happen to please the compiler?

**Comment by startupthekid** [comment]
Actually what ended up working was

```
@objc(validate:) func validate() throws {
        
}
```

**Comment by robb** [comment]
The more you know
