### ISSUE TITLE
Crash on Enum transformer, can we use "Default" case ?

### ISSUE THREAD

**Issue by KanybekMomukeyev** [Mantle/Mantle#619]
```
typedef enum : NSUInteger {
    GHIssueStateOpen,
    GHIssueStateClosed
} GHIssueState;

+ (NSValueTransformer *)stateJSONTransformer {
    return [NSValueTransformer mtl_valueMappingTransformerWithDictionary:@{
        @"open": @(GHIssueStateOpen),
        @"closed": @(GHIssueStateClosed)
    }];
}
```
if we have extra case on "state", for example @"in_review", application crashes if we not declared GHIssueStateInReview before, is there "Default" case ?

**Comment by dcaunt** [comment]
You're probably looking for [`+[NSValueTransformer mtl_valueMappingTransformerWithDictionary:defaultValue:reverseDefaultValue:]`](https://github.com/Mantle/Mantle/blob/66af2bf3450b4a782023695ced9363c5ecb26009/Mantle/NSValueTransformer%2BMTLPredefinedTransformerAdditions.h#L38-L59) which allows you to specify a default value in both transformation directions.

**Comment by KanybekMomukeyev** [comment]
@dcaunt thanks, it solved problem!
