### ISSUE TITLE
Signature of mergeValueForKey:fromModel: defined in MTLModel protocol is confusing

### ISSUE THREAD

**Issue by zintus** [Mantle/Mantle#620]
Name of method implies usage of key on supplied model by means of KVO. Strictly speaking it's impossible, because valueForKey: defined in category on NSObject class, and signature declares (id <MTLModel>)

It's a minor issue, but still valid one from my point of view :)

**Comment by robb** [comment]
Sorry, I don't follow

**Comment by zintus** [comment]
- (void)mergeValueForKey:(NSString *)key fromModel:(NSObject<MTLModel> *)model; // Class
- (void)mergeValueForKey:(NSString *)key fromModel:(id<MTLModel>)model; // Protocol

Definitions from protocol and concrete class are different. Only NSObjects can respond to valueForKey: message, thus it's unclear how to implement protocol strictly following type signature.
