### ISSUE TITLE
MTLJSONAdapter.m about transformer

### ISSUE THREAD

**Issue by hilen** [Mantle/Mantle#622]
There has a function named ```+ (NSValueTransformer *)NSURLJSONTransformer``` in MTLJSONAdapter.m line 641.

If server response data NSString , I want convert it to NSNumber. I should write the transformer code like these
```
+ (NSValueTransformer *)JSONTransformerForKey:(NSString *)key
{
    //string to number
    if ([key isEqualToString:@"imagesCount"])  {
        return [MTLValueTransformer transformerUsingForwardBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
            if ([value isKindOfClass:[NSNumber class]]) {
                return value;
            }
            NSNumberFormatter *f = [[NSNumberFormatter alloc] init];
            f.numberStyle = NSNumberFormatterDecimalStyle;
            return [f numberFromString:value];
        }];
    } else {
        return nil;
    }
}
```
but by the way ,I can also write a category, add this two functions.

So why this file desn't have the these two functions?
```
+ (NSValueTransformer *)NSStringJSONTransformer;
+ (NSValueTransformer *)NSNumberJSONTransformer;
```

**Comment by robb** [comment]
Converting a string containing a valid `URL` to an `NSURL` instance and back is a lossless process. However, converting a string to a number and back may lead to a loss of precision and contains inherent ambiguity. Instead of adding magic, we decided to leave it to the users of Mantle to make the right call fit for their domain. :v:

**Comment by hilen** [comment]
tks

**Comment by robb** [comment]
> So if my model contains a NSArray, how to omit the transformer function?

The information that `listData` is an array of `SmallModels` is not available at runtime, so unfortunately, you have to keep implementing `-listDataJSONTransformer`, sorry.
