### ISSUE TITLE
Crash with "setValue:forUndefinedKey:]: this class is not key value coding-compliant"

### ISSUE THREAD

**Issue by akring** [Mantle/Mantle#624]
It worked well for me before,and today I just add an enum for status:

```
typedef enum : NSUInteger{

    LikeStatuNone,
    LikeStatuLiked,
    LikeStatuUnLiked,

}LikeStatu;
```

The property is:

```
@property (nonatomic, assign) LikeStatu *likeStatus;
```

And the transfer code is:

```
+ (NSValueTransformer *)likeStatusJSONTransformer{

    NSDictionary *transDic = @{
                               @"-1": @(LikeStatuNone),
                               @"0": @(LikeStatuLiked),
                               @"1":@(LikeStatuUnLiked)
                               };

    return [NSValueTransformer mtl_valueMappingTransformerWithDictionary:transDic];
}
```

And finally I got a crash with log:

> **\* Caught exception setting key "likeStatus" : [<HomeModel 0x7f83e516bc80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key likeStatus.
> 2015-10-16 10:43:39.292 VoiceOfCustom[8188:173173] **\* Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<HomeModel 0x7f83e516bc80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key likeStatus.'

this happend in MTLModel.m line:51

```
@try {
        if (![obj validateValue:&validatedValue forKey:key error:error]) return NO;

        if (forceUpdate || value != validatedValue) {
            [obj setValue:validatedValue forKey:key];
                //the validatedValue is long(0) when this crash happen
        }

        return YES;
    }
```

**Comment by foulkesjohn** [comment]
Can you provide the code for your entire model object?

**Comment by skartys** [comment]
I think it's because you have declared an enum property as a pointer 

```objectivec
@property (nonatomic, assign) LikeStatu *likeStatus;
```
should be
```objectivec
@property (nonatomic, assign) LikeStatu likeStatus;
```
