### ISSUE TITLE
Xcode 7.1 compilation issue for Pods that depend on Mantle

### ISSUE THREAD

**Issue by priteshshah1983** [Mantle/Mantle#626]
`Mantle.h` uses angular imports which leads to this error: `Mantle.h:19:9: Include of non-modular header inside framework module 'Mantle.Mantle'` in Pods that use `Mantle` as a dependency.

I'm not sure if the suggested fix is to **NOT** use angular imports in `Mantle.h`. More information here: https://github.com/CocoaPods/CocoaPods/issues/4420

**Comment by priteshshah1983** [comment]
It would be really appreciated if one of the collaborators can comment on this issue.

Thanks in advance!

**Comment by jasonfergz** [comment]
Would love to know if any has been able to look into this issue at all. Any info would be greatly appreciated.

**Comment by souzainf3** [comment]
Hey @priteshshah1983 you could send a "pull request" to this official repository?

Thanks.

**Comment by priteshshah1983** [comment]
I already created a PR: https://github.com/Mantle/Mantle/pull/627

**Comment by souzainf3** [comment]
This issue can be closed. Thanks @priteshshah1983

**Comment by priteshshah1983** [comment]
@dcaunt Any chance you can review this one?

**Comment by kylehorn** [comment]
+1

**Comment by priteshshah1983** [comment]
@dcaunt @robb It's been a while since this PR is open. It would be great if you can review it. I will be happy to make any changes if required.

Looking forward to hearing back from you!

**Comment by robb** [comment]
Can you merge master to re-trigger the CI?

**Comment by priteshshah1983** [comment]
Done. And, the build passed.

**Comment by robb** [comment]
Closed through #627
