### ISSUE TITLE
Official podspec?

### ISSUE THREAD

**Issue by priteshshah1983** [Mantle/Mantle#628]
Where can I find the official podspec? It would be great if someone can point me to the one that is used is published on Cocoapods website.

**Comment by dcaunt** [comment]
There is no 'official' podspec, but all of the podspecs used by CocoaPods are on GitHub. The latest Mantle podspec is [here](https://github.com/CocoaPods/Specs/blob/master/Specs/Mantle/2.0.5/Mantle.podspec.json).

**Comment by priteshshah1983** [comment]
@dcaunt I should have been more specific. I was looking for the `ruby` version. I was planning to patch it in my local distribution repo to fix this issue: https://github.com/Mantle/Mantle/issues/626 by adding a `prepare_command` script.

```ruby
spec.prepare_command = <<-CMD
                        find Pods -regex 'Pods\\/Mantle\\/Mantle\\/Mantle\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)Mantle\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'
                   CMD
```

**Comment by priteshshah1983** [comment]
@dcaunt, does the `ruby` version of the podspec exist somewhere?

Thanks!

**Comment by dcaunt** [comment]
Sorry, I haven't had a ruby version since they were all converted to JSON. You could probably recreate it quite easily if you must have the ruby version.

**Comment by priteshshah1983** [comment]
Thanks! The json version will work.
