### ISSUE TITLE
class cluster different JSON dictionary representation

### ISSUE THREAD

**Issue by opfeffer** [Mantle/Mantle#630]
Been using Mantle for a while now and am really liking it so far!

I have a question that I wasn't able to find a direct answer for:

I have a class cluster `XYAddress` consisting of `XYMyAddress` and `XYThirdPartyAddress`.

```
@interface XYAddress

@property (nonatomic, copy) NSString *address1;
@property (nonatomic, copy) NSString *zip;

@end
```

The properties are the same the only real difference is the API mapping as represented with `+JSONKeyPathsByPropertyKey` of each subclass.

```
@implementation XYMyAddress

+ (NSDictionary *)JSONKeyPathsByPropertyKey
{
    return @{
        @"address1": "myAddress1",
        @"zip": @"myZip"
    }
}
```

vs.

```
@implementation XYThirdPartyAddress

+ (NSDictionary *)JSONKeyPathsByPropertyKey
{
    return @{
        @"address1": "thirdPartyAddressLine1",
        @"zip": @"thirdPartyAddressPostalCode"
    }
}
```

Now, as part of the application I'm actually receiving an instance of `XYMyAddress` from my APIs but have to serialize it into JSON of `XYThirdPartyAddress` to hand it back to the third party API endpoints.

What would be the easiest way of "transforming" my `XYMyAdress` subclass to an instance of `XYThirdPartyAdress`? Or am I not approaching this problem the _right way_?

Thanks for your help!

**Comment by hytzxd** [comment]
Why not use a property differentiates them?
Like this ?
typedef NS_ENUM(NSInteger ,XYAddressType) {
    
    XYAddressTypeNone,
    XYAddressTypeMine,
    XYAddressTypeThirdParty,
    
};

@interface XYAddress :MTLModel

@property (nonatomic ,assign)XYAddressType addressType;
@property (nonatomic, copy) NSString *address1;
@property (nonatomic, copy) NSString *zip;

@end

**Comment by robb** [comment]
You can use [`+classForParsingJSONDictionary`](https://github.com/mantle/mantle#classforparsingjsondictionary) for handling class clusters.
