### ISSUE TITLE
Object Immutability with Mantle

### ISSUE THREAD

**Issue by JustinDSN** [Mantle/Mantle#632]
I think I found a problem with object immutability and I'm creating the issue here for people who run across the same thing and maybe someone can explain why this happens.

I'm attempting to create an immutable model class with the .h file that looks like:

```
#import <Mantle/Mantle.h>

@interface XMEEntitlementType : MTLModel <MTLJSONSerializing>

@property (nonatomic, readonly) NSNumber *currentBalance;
@property (nonatomic, readonly) NSString *currentBalanceFriendlyName;
@property (nonatomic, readonly, copy) NSString *defaultTypeOfUnits;
@property (nonatomic, readonly) NSNumber *entitlementTypeId;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly, copy) NSString *typeOfUnits;

@end
```

And the .m file looks like:

```
#import "XMEEntitlementType.h"

@implementation XMEEntitlementType

#pragma  mark - MTLJSONSerializing

+ (NSDictionary *)JSONKeyPathsByPropertyKey
{
    return @{
             @"currentBalance" : @"currentBalance",
             @"defaultTypeOfUnits": @"defaultTypeOfUnits",
             @"entitlementTypeId": @"id",
             @"name": @"name",
             @"typeOfUnits": @"typeOfUnits"
             };
}

#pragma mark - Instance Methods

- (NSString *)currentBalanceFriendlyName
{
    NSString *currentBalanceString = @"0";
    if (self.currentBalance) {
        currentBalanceString = [NSString stringWithFormat:@"%.02f", self.currentBalance.doubleValue];
    }
    
    return [NSString stringWithFormat:@"%@ %@ remaining", currentBalanceString, self.typeOfUnits];
}

@end
```

I am testing the immutability of properties with the following XCTest case:

```
- (void)testImmutablilty {
    
    NSMutableString *defaultTypeOfUnits = [NSMutableString stringWithString:@"defaultTypeOfUnits"];
    NSMutableString *name = [NSMutableString stringWithString:@"name"];
    NSMutableString *typeOfUnits = [NSMutableString stringWithString:@"typeOfUnits"];
    
    NSDictionary *dictionary = @{
                                 @"defaultTypeOfUnits": defaultTypeOfUnits,
                                 @"name": name,
                                 @"typeOfUnits": typeOfUnits
                                 };
    
    NSError *entitlementError;
//either method fails to copy
//    XMEEntitlementType *entitlement = [[XMEEntitlementType alloc] initWithDictionary:dictionary error:&entitlementError]; 
    XMEEntitlementType *entitlement = [MTLJSONAdapter modelOfClass:XMEEntitlementType.class fromJSONDictionary:dictionary error:&entitlementError];
    XCTAssertNil(entitlementError);
    
    
    [defaultTypeOfUnits appendString:@"Updated"];
    [name appendString:@"Updated"];
    [typeOfUnits appendString:@"Updated"];
    
    XCTAssertNotEqualObjects(entitlement.defaultTypeOfUnits, defaultTypeOfUnits);
    XCTAssertNotEqualObjects(entitlement.name, name);
    XCTAssertNotEqualObjects(entitlement.typeOfUnits, typeOfUnits);
}
```

The above assertions fail because the entitlement object's properties are in-fact updated.  

The only way I was able to get it to pass is to redefine the properties in the class continuation as:

```
@interface XMEEntitlementType ()

@property (nonatomic, readwrite, copy) NSString *defaultTypeOfUnits;
@property (nonatomic, readwrite, copy) NSString *name;
@property (nonatomic, readwrite, copy) NSString *typeOfUnits;

@end
```

Can some one explain if this is a bug with Apple's key value coding or something that's happening down in Mantle?

Thanks!!

**Comment by hytzxd** [comment]
The keyword "copy"  is based  on the Setter method.The  keyword "readonly" The keyword "readonly" Let the compiler not generated setter method . Mantle is  based  on the  key value coding. The  key value coding default implementation of this method does the following:
1. Searches the class of the receiver for an accessor method whose name matches the pattern -set<Key>:. If such a method is found the type of its parameter is checked. If the parameter type is not an object pointer type but the value is nil -setNilValueForKey: is invoked. The default implementation of -setNilValueForKey: raises an NSInvalidArgumentException, but you can override it in your application. Otherwise, if the type of the method's parameter is an object pointer type the method is simply invoked with the value as the argument. If the type of the method's parameter is some other type the inverse of the NSNumber/NSValue conversion done by -valueForKey: is performed before the method is invoked.
    2. Otherwise (no accessor method is found), if the receiver's class' +accessInstanceVariablesDirectly method returns YES, searches the class of the receiver for an instance variable whose name matches the pattern _<key>, _is<Key>, <key>, or is<Key>, in that order. If such an instance variable is found and its type is an object pointer type the value is retained and the result is set in the instance variable, after the instance variable's old value is first released. If the instance variable's type is some other type its value is set after the same sort of conversion from NSNumber or NSValue as in step 1.
    3. Otherwise (no accessor method or instance variable is found), invokes -setValue:forUndefinedKey:. The default implementation of -setValue:forUndefinedKey: raises an NSUndefinedKeyException, but you can override it in your application.

Because the instance "entitlement" have not setter method for "defaultTypeOfUnits", copy behavior Invalidation.
My english is poor. Sorry!

**Comment by JustinDSN** [comment]
Wow great explanation thank you for the information!
