### ISSUE TITLE
How to parse json without custom JSONKeyPathsByPropertyKey

### ISSUE THREAD

**Issue by foobra** [Mantle/Mantle#633]
I have Class Person
@interface Person : MTLModel<MTLJSONSerializing>
@property (nonatomic) NSString *name;
@property (nonatomic) NSString *password;
@property (nonatomic) NSString *hometown;
@end

@implement Person
++  (NSDictionary *)JSONKeyPathsByPropertyKey
{
    return @{
                   @"name": @"name", 
                   @"password": @"password",
                   @"hometown": @"city"};
}
@end

My question is if the propertyName equals the json key, how can I omit JSONKeyPathsByPropertyKey, just indicate the city -> hometown, omit the name and password ?

**Comment by dcaunt** [comment]
You can use [`+[NSDictionary mtl_identityPropertyMapWithModel:Person.class]`](https://github.com/Mantle/Mantle/blob/66af2bf3450b4a782023695ced9363c5ecb26009/Mantle/NSDictionary%2BMTLMappingAdditions.h#L19) to generate an identify mapping using the `propertyKeys`.

**Comment by foobra** [comment]
@dcaunt You save my day, thx!
