### ISSUE TITLE
To retain the dictionary used to create the model in a property within the same model object

### ISSUE THREAD

**Issue by smarkars** [Mantle/Mantle#634]
I have a dictionary using which the MTLModel is created. Can I have that same dictionary (need the raw dictionary there) assigned to a property of that same model?

Idea is the dictionary will have dynamic keys except for the name key. When using the model I will query the dictionary with keys received from another service.

``` json
{
   "strategyname" : "KKR_MARK",
   "dynamic_key0" : "value",
   "dynamic_key1" : "value"
}
```

Model would be something like this

``` objectivec
@interface DAMStrategy : MTLModel <MTLJSONSerializing>
@property(nonatomic,strong) NSString * damName;
@property(nonatomic,strong) NSDictionary * damRawDictionary;
@end

@implementation Strategy
+ (NSDictionary *) JSONKeyPathsByPropertyKey {
    return @{@"damName":@"strategyname"};
}
@end
```

I would like to have the JSON shown above which will be used to populate model and also to be assigned to the <code>damRawDictionary</code> property

**Comment by dcaunt** [comment]
You could probably subclass `MTLJSONAdapter` to achieve this quite easily.
