### ISSUE TITLE
Model  array  copy  not right 

### ISSUE THREAD

**Issue by zktc5418** [Mantle/Mantle#637]
周远远  11:19:34
(lldb) po note 
<BNNote: 0x7feccb82b4f0> {
    album = "<null>";
    baby = "<BNBaby: 0x7feccb82b820> {\n    avatarURLString = \"<null>\";\n    backgroudURLString = \"<null>\";\n    birthday = \"2014-10-06 02:45:16 +0000\";\n    creationDate = \"<null>\";\n    gender = 1;\n    identifier = \"7B6BA3D6-108A-401F-917F-4E0171092B85-1799-0000007713E23331\";\n    name = zhoujinjin;\n    nickName = zhoujinjin;\n}";
    createDate = "2015-11-02 02:45:46 +0000";
    fontName = "Heiti SC";
    fontSize = 20;
    identifier = "98A72F1B-F8B3-41C0-82FB-A24A11093AF7-1799-0000007904CD3756";
    isChecked = 0;
    lineSpacing = 15;
    noteItems =     (
        "<BNNoteItem: 0x7feccb82afa0> {\n    collageInfo = \"<null>\";\n    contentUrl = \"<null>\";\n    identifier = \"0BFD0768-D2D0-4688-B64C-ACF43C56D123-1799-0000007904CD7853\";\n    imageHeight = 0;\n    imageWidth = 0;\n    isEditing = 0;\n    minHeight = 0;\n    previewUrl = \"<null>\";\n    text = \"HELLO BABY\";\n    type = 0;\n}"
    );
    resouceId = 6;
    state = 1;
    synchronized = 0;
    textAlignment = 1;
    type = 0;
    updateDate = "2015-11-02 02:46:13 +0000";
    user = "<null>";
}

(lldb) po [composeVC editNote]
<BNNote: 0x7fecc97703f0> {
    album = "<null>";
    baby = "<BNBaby: 0x7fecc9770850> {\n    avatarURLString = \"<null>\";\n    backgroudURLString = \"<null>\";\n    birthday = \"2014-10-06 02:45:16 +0000\";\n    creationDate = \"<null>\";\n    gender = 1;\n    identifier = \"7B6BA3D6-108A-401F-917F-4E0171092B85-1799-0000007713E23331\";\n    name = zhoujinjin;\n    nickName = zhoujinjin;\n}";
    createDate = "2015-11-02 02:45:46 +0000";
    fontName = "Heiti SC";
    fontSize = 20;
    identifier = "98A72F1B-F8B3-41C0-82FB-A24A11093AF7-1799-0000007904CD3756";
    isChecked = 0;
    lineSpacing = 15;
    noteItems =     (
        "<BNNoteItem: 0x7feccb82afa0> {\n    collageInfo = \"<null>\";\n    contentUrl = \"<null>\";\n    identifier = \"0BFD0768-D2D0-4688-B64C-ACF43C56D123-1799-0000007904CD7853\";\n    imageHeight = 0;\n    imageWidth = 0;\n    isEditing = 0;\n    minHeight = 0;\n    previewUrl = \"<null>\";\n    text = \"HELLO BABY\";\n    type = 0;\n}"
    );
    resouceId = 6;
    state = 4;
    synchronized = 0;
    textAlignment = 1;
    type = 0;
    updateDate = "2015-11-02 02:46:13 +0000";
    user = "<null>";
}
As you can see  there to BNNote Model  
the second model '[composeVC editNote]' is copy from first  'note'
BNNote address is different,But in noteitems  BNNoteItem adress is same. means noteItems is note copy 
How could I get copied noteItems ????

**Comment by dcaunt** [comment]
Mantle's implementation of `copyWithZone:` provides a shallow copy which means that both instances have a reference to the same instance of `noteItems`. You will need to override this method yourself to make a deep copy.

**Comment by zktc5418** [comment]
thank you for your reply. i will try to override copyWithZone
