### ISSUE TITLE
Customize copy immutability via a MTLModel class method

### ISSUE THREAD

**Issue by erichoracek** [Mantle/Mantle#638]
It would be helpful if immutability (whether `copyWithZone:` should return `self`) could be customized via a class method. While it's pretty easy to override this behavior, this would be most useful as a way for consumers to query whether the properties of a `MTLModel` subclass will change over its lifecycle.

There's some discussion on this pattern here https://www.objc.io/issues/7-foundation/value-objects/#nscopying

If you think this is a reasonable idea, I'd be more than happy to take a stab at it.

**Comment by robb** [comment]
Such a method would require `-mergeValuesForKeysFromModel:` to throw an exception if the model is "immutable" and it's generally very hard to enforce this in Objective-C, so I'm :-1: for having this in Mantle proper. (A nice idea for `AUTModel` though)
