### ISSUE TITLE
I don't know how to convert string to NSArray

### ISSUE THREAD

**Issue by kimi0421** [Mantle/Mantle#643]
I  have the following json string:

    {"suit_id": 2427;
     "suits": "http://img.prettyyes.com/1137-4930-1446175512.jpeg;http://img.prettyyes.com/1137-7665-1446175512.jpeg;http://img.prettyyes.com/1137-4783-1446175512.jpeg"}

So when I use mantle to parse the json string with following file

testModel.h

```objective-c
@interface testModel : MTLModel <MTLJSONSerializing>
@property (nonatomic, strong) NSString *suit_id;
@property (nonatomic, strong) NSString *suits;
@end
```

testModel.m

```objective-c
@implementation testModel
+ (NSDictionary *) JSONKeyPathsByPropertyKey {
    return @{
            "suit_id":   "suit_id",
            "suits":     "suits"
            };
}
@end
```

However I would like to convert suits from string to a NSArray with multiple urls so I did following:

testModel.h

```objective-c
@interface testModel : MTLModel <MTLJSONSerializing>
@property (nonatomic, strong) NSString *suit_id;
@property (nonatomic, strong) NSArray *suits;
@end
```

testModel.m

```objective-c
@implementation testModel
+ (NSDictionary *) JSONKeyPathsByPropertyKey {
    return @{
            "suit_id":   "suit_id",
            "suits":     "suits"
            };
}

+ (NSValueTransformer *) suitsJSONTransform {
    return [MTLValueTransformer transformerUsingForwardBlock:^(NSString *str, BOOL *success, NSError **error){
        return [[str componentsSeparatedByString:@";"] mutableCopy];
    }];
}
@end
```

But it's not working, what it returns is nil. The result is nil. When I override the wrong function?

**Comment by dcaunt** [comment]
The method returning the NSValueTransformer for `suits` should be called `suitsJSONTransformer`, not `suitsJSONTransform`.

**Comment by kimi0421** [comment]
It is really a silly mistake
