### ISSUE TITLE
Can Mantle add detail keypath info to  the transform error?

### ISSUE THREAD

**Issue by CodeLife2012** [Mantle/Mantle#644]
When a transform error occur, current error can't figure out where did  this error exactly occur.

When debug we need to add breakpoint to find where failed.

 And for a release build, it's more harder to find  the root cause？

**Comment by robb** [comment]
Sounds like a good idea. We'd gladly review a PR to this effect :sparkling_heart:

**Comment by CodeLife2012** [comment]
May be can append the class and property  info  to the origin error in these places:

**Comment by kirpa** [comment]
@robb Looks like this one is already addressed in https://github.com/Mantle/Mantle/commit/afa50afc30617b630a687dcf2ad0e72c2c1664f2

**Comment by dcaunt** [comment]
Fixed in #661
