### ISSUE TITLE
Nested JSON returns <null> for object keys

### ISSUE THREAD

**Issue by duribreux** [Mantle/Mantle#645]
Hello,

Since I updated from `1.x` to `2.0.5` I've some trouble to figure out how to deal with nested objects. It used to work perfectly fine before. Basically, this is what I've got:

```
// myObject.h
@interface MyObject : MTLModel <MTLJSONSerializing>
@property (nonatomic, strong) NSString* name;
@property (nonatomic, strong) NSString* owner;
...
@property (nonatomic, strong) MyStatistics* statistics;
@end
```

```
// MyObject.m
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return [NSDictionary mtl_identityPropertyMapWithModel:[MyObject class]];
}

+ (NSValueTransformer *)statisticsJSONTransformer{
    return [MTLValueTransformer transformerUsingForwardBlock:^(NSDictionary *statistics, BOOL *success, NSError **error){
        return [MTLJSONAdapter modelOfClass: [MyStatistics class]
                         fromJSONDictionary: statistics
                                      error: nil];
    } reverseBlock:^(MyStatistics *statistics, BOOL *success, NSError **error) {
        return [MTLJSONAdapter JSONDictionaryFromModel: statistics error:nil];
    }];
}
```
I've tried to add `optional` methods like `+ (NSValueTransformer *)JSONTransformerForKey:(NSString *)key` inside `MyObject.m`file to specify which class to use for `statistics` key but nothing worked.

```
// MyStatistics.h
@interface MyStatistics : MTLModel <MTLJSONSerializing>
@property (nonatomic, strong) NSNumber* numberOfSubscribers;
...
@end
```

```
// MyStatistics.m
@implementation MyStatistics
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return [NSDictionary mtl_identityPropertyMapWithModel:[MyStatistics class]];
}
```

I receive a JSON array of MyObject which I transform using:
```
[MTLJSONAdapter modelsOfClass:[MyObject class] fromJSONArray:data error:&error];
```

And I get back an array of MyObject with all properties set successfully but `statistics` which is `<null>`. I've already tried a tremendous quantity of code variations and read about it but nothing seems to work.

My printed object:
````
<MyObject: 0x14c6f8d90> {
    name = value1;
    owner = value2;
   ...
    statistics = "<null>";
    arrayStuff =     (
        v1,
        v2,
        v3
    );
}
```

Can someone help me with that ? Do you see any obvious mistake ?

Regards,

**Comment by robb** [comment]
Can you verify that the transformer is being invoked?

If you pass on the `error` pointer to the adapter, e.g.:

```objc
+ (NSValueTransformer *)statisticsJSONTransformer{
    return [MTLValueTransformer transformerUsingForwardBlock:^(NSDictionary *statistics, BOOL *success, NSError **error){
        return [MTLJSONAdapter modelOfClass: [MyStatistics class]
                         fromJSONDictionary: statistics
                                      error: error];
    } reverseBlock:^(MyStatistics *statistics, BOOL *success, NSError **error) {
        return [MTLJSONAdapter JSONDictionaryFromModel: statistics error:nil];
    }];
}
```

does the error get set to anything?

My hunch is that the transformation of the `statistic` objects fails in a way that Mantle 1.x let slip by (usually a type mismatch of `NSNumber` and JSON strings).

**Comment by duribreux** [comment]
Damn..

Your hunch was right. I had a `NSNumber` type remaining after some changes to parse a formatted date (ISO8601) in my statistics object and Mantle 2.x won't slip by ^^ Wasted so much time for that, shame on me...

Thanks a lot, everything works fine now :)
