### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by manonthemoon42** [Mantle/Mantle#646]
Hi ! 

I see that the podspec says platform : `5.0`, but in the readme, it says supports `iOS +8.0`.
Does that means Mantle doesn't work well before iOS 8.0 ?
If it's the case, shouldn't we upgrade to `8.0` the platform target in the podspec ?

Thanks

**Comment by jkyin** [comment]
The podspec is maintained by unofficial people.

Mantle said it just supports iOS 8.0+ means that they have tested for iOS 8.0+. But if you want use for iOS 7 or lower, you can test it by yourself.

That's it.

**Comment by manonthemoon42** [comment]
Okay, will do.

Thanks
