### ISSUE TITLE
tvOS 9.0 support in missing on Mantle (2.0.5) pod

### ISSUE THREAD

**Issue by cm-hugog** [Mantle/Mantle#648]
[!] The platform of the target (tvOS 9.0) is not compatible with `Mantle (2.0.5)`, which does not support `tvos`.

**Comment by JanGorman** [comment]
I can confirm that Mantle does work on the tvOS target without any changes at all: https://github.com/JanGorman/Mantle

And I saw that @dcaunt who's part of the github Mantle organisation is listed as one of the maintainers on https://cocoapods.org/pods/Mantle – any chance to push an updated pod spec or any way I could contribute?

**Comment by robb** [comment]
@JanGorman I've made you owner of the podspec, fire at will ✌

**Comment by JanGorman** [comment]
@robb Much appreciated  👍. I pushed the updated podspec and verified that it works with my project.

**Comment by dcaunt** [comment]
Thanks @robb and @JanGorman.
