### ISSUE TITLE
A property corresponding to two different types of value

### ISSUE THREAD

**Issue by WCrazyStone** [Mantle/Mantle#649]
Suppose we have an entity, the named by cardModel , it has a property called userID, type NSInteger. The question is , userID may be in another string type in an API response , without directly modifying the source code of premise Mantle how do ?

**Comment by robb** [comment]
I personally strongly recommend against using `NSInteger` for user IDs. It's pretty easy to accidentally truncate the number and you probably won't do any math with it anyway.

Regardless, you would have to implement `+[XYUser userIDJSONTransformer]` and [return a value transformer that parses the string](https://github.com/mantle/mantle#jsontransformerforkey).
