### ISSUE TITLE
2.0.5 Update: MTLJSONAdapter suddenly failing on custom valueTransformers which previously never failed

### ISSUE THREAD

**Issue by opfeffer** [Mantle/Mantle#650]
I updated Mantle from 2.0 to 2.0.5 because we were seeing compilation problems with Xcode7.1 (with 2.0.3 Xcode was complaining about [MTLJSONAdapter.h:212](https://github.com/Mantle/Mantle/blob/2.0/Mantle/MTLJSONAdapter.h#L212)

Suddenly many of our unit tests are failing and upon digging in, I noticed that many of my custom property `*JSONValueTransformers` are failing with the following NSError

```
 Error Domain=MTLTransformerErrorHandlingErrorDomain Code=1 "Value did not match expected type" UserInfo=0x791952b0 {NSLocalizedFailureReason=Expected {
     v1 =     {
     };
 } to be of class NSMutableDictionary but got __NSDictionaryI, MTLTransformerErrorHandlingInputValueErrorKey={
     v1 =     {
     };
 }, NSLocalizedDescription=Value did not match expected type}
```

My model object is pretty basic:

```
 // Model.h
 @property (nonatomic, strong) NSMutableDictionary *device;

 // Model.m
 + (NSDictionary *)JSONKeyPathsByPropertyKey
 {
     return @{
              @"device":@"device",
              };
 }

 + (NSValueTransformer *)deviceJSONTransformer
 {
     return [MTLValueTransformer transformerUsingForwardBlock:^(NSMutableDictionary *contents, BOOL *success, NSError *__autoreleasing *error) {
         return [[NSMutableDictionary alloc] initWithDictionary:contents[@"v1"] copyItems:YES];
     } reverseBlock:^(NSMutableDictionary *contents, BOOL *success, NSError *__autoreleasing *error) {
         return @{ @"v1": contents };
     }];
 }
```

Possibly related to https://github.com/Mantle/Mantle/issues/614 .

**Comment by betzerra** [comment]
Yup, having a similar issue with this transformer:

```ObjC
+ (NSValueTransformer *)dateOfBirthJSONTransformer {
    return [MTLValueTransformer transformerUsingForwardBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
        return [[NSDate ISODateFormatter] dateFromString:value];
    } reverseBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
        return [[NSDate ISODateFormatter] stringFromDate:value];
    }];
}
```

My colleague changed Mantle version to 2.0.2 and seems stable.

I don't know if it helps but I debugged for a while and I noticed that after this point, the value returns nil.
https://github.com/Mantle/Mantle/blob/master/Mantle/MTLValueTransformer.m#L70-L80

**Comment by betzerra** [comment]
Any updates with this?

**Comment by robb** [comment]
@betzerra please create a separate issue, if possible :bow:

@opfeffer Have you verified with a breakpoint that the transformer is being invoked? I'm a little at loss here why `[[NSMutableDictionary alloc] initWithDictionary:contents[@"v1"] copyItems:YES];` wouldn't return an `NSMutableDictionary` instance. (That being said, I _strongly_ suggest against exposing a mutable dictionary as a property on your model objects)

**Comment by dcaunt** [comment]
I can't reproduce this in Mantle 2.0.5 using your `Model`, @opfeffer. The JSON transformer is invoked correctly and the property is a mutable dictionary. Can you provide a sample project which reproduces the issue?
