### ISSUE TITLE
YYModel is said to be faster than Mantle !?

### ISSUE THREAD

**Issue by onmyway133** [Mantle/Mantle#651]
Hi, most of us use Mantle and are happy with it. I just stumble [YYModel](https://github.com/ibireme/YYModel) which is said to be faster than Mantle. 

![](https://camo.githubusercontent.com/73e6774154cfe8652b61f62e8ea32cac48969033/68747470733a2f2f7261772e6769746875622e636f6d2f69626972656d652f59594d6f64656c2f6d61737465722f42656e63686d61726b2f526573756c742e706e67)

I know that most Objective C model framework under the hood uses `Runtime` to inspect properties and then KVC. I see that YYModel makes heavy use of `objc_msgSend`. See https://github.com/ibireme/YYModel/blob/master/YYModel/NSObject%2BYYModel.m

Any thoughts about this? Thanks

**Comment by CavalcanteLeo** [comment]
+1

**Comment by CavalcanteLeo** [comment]
what are the pro and cons of them ?

**Comment by JanGorman** [comment]
Pick the one who's API suits the most and you can get the most community support (StackOverflow, Github) for?

**Comment by revolter** [comment]
The con is that the `YYModel`'s community is mostly Chinese and so most of the issues and PRs are in Chinese so no so helpful if you don't know the language.

**Comment by CavalcanteLeo** [comment]
I've changed all my models to https://github.com/pinterest/plank

by far, the best I've used, even more because it's immutable
