### ISSUE TITLE
How can Mantle convert JSONString to JSONDictionary? 

### ISSUE THREAD

**Issue by xwgit2971** [Mantle/Mantle#652]
for example NSString  "{"weatherinfo":{"city":"北京","cityid":"101010100","temp1":"15℃","temp2":"5℃","weather":"多云","img1":"d1.gif","img2":"n1.gif","ptime":"08:00"}}"

**Comment by robb** [comment]
You'll want to have a look at [NSJSONSerializing](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSJSONSerialization_Class/index.html).
