### ISSUE TITLE
BOOL value and some cases JSON have nil value

### ISSUE THREAD

**Issue by tquocit** [Mantle/Mantle#654]
Example I had: 
@property (nonatomic, assign, readonly) BOOL is_provider;
- (NSValueTransformer *)is_providerJSONTransformer {
  return [NSValueTransformer valueTransformerForName:MTLBooleanValueTransformerName];
  }

some case my json is return nil value with is_provider. So when i parse I got nil Model?
I used v 2.0.6

**Comment by sergey-sportsetter** [comment]
Technically, JSON boolean should only return `true` or `false`. If you want to accommodate nil values, you should probably wrap the response in 'NSNumber'
