### ISSUE TITLE
Nested Array MTLModel is parsed out as NSDictionary and not MTLModel

### ISSUE THREAD

**Issue by wilferrel** [Mantle/Mantle#655]
```
@implementation Message

+ (NSDictionary *)JSONKeyPathsByPropertyKey
{
    return @{
        @"member_id" : @"member_id",
        @"content_type" : @"content_type",
        @"guid" : @"id",
        @"text" : @"text",
        @"created_at" : @"created_at",
        @"updated_at" : @"updated_at",
        @"message_contents" : @"contents"
    };
}

+ (NSValueTransformer *)message_contentsTransformer
{
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[MyContent class]];
}
```
When I look inside of Message.message_contents I get a NSDictionary with the key and values from MyContent MTLModel class and not and actual MTLModel object. Am I doing something wrong?

**Comment by wilferrel** [comment]
This is another example with screenshots from code : 

```
 NSArray *contentsMantle = [MTLJSONAdapter modelsOfClass:MyContent.class fromJSONArray:contentsArray error:&arrayError];
                NSLog(@"Array => %@",contentsMantle);
```

![Array of MTLModel](http://i.imgsafe.org/afcab59.png)

**Comment by robb** [comment]
I recommend setting breakpoints in your value transformer methods to verify they are beging invoked. :smile:  In this case, you're missing a `JSON` in:

```
+ (NSValueTransformer *)message_contentsJSONTransformer
```

**Comment by wilferrel** [comment]
@robb YOU ARE THE MAN!! thanks I guess these sleepless nights are getting to me. I appreciate the help

**Comment by wzbozon** [comment]
NSValueTransformer is deprectated in case of Arrays. Use `arrayTransformerWithModelClass`:
`+ (NSValueTransformer *)binsJSONTransformer
{
    return [MTLJSONAdapter arrayTransformerWithModelClass:[EONBankBin class]];
}`
