### ISSUE TITLE
How To Use A Mantle Model In Swift?

### ISSUE THREAD

**Issue by ZhuCanle** [Mantle/Mantle#659]
I want to use MTLValueTransformer,
The effective implement in Objective-C :
```Objective-C
+(NSValueTransformer *)errNumJSONTransformer {...}
```

I try the following  replacment in Swift,but didnt work.
```swift
 func errNumJSONTransformer() -> NSValueTransformer {...}
 static func errNumJSONTransformer() -> NSValueTransformer {...}
static func errNumJSONTransformer() -> NSValueTransformer! {...}
```

**Comment by JanGorman** [comment]
What specifically didn't work?

```swift
static func fooJSONTransformer() -> NSValueTransformer {
  // Or custom implementation
  return NSValueTransformer(forName: MTLURLValueTransformerName)!
}
``` 
is the form that works.

Make sure that your class inherits from `MTLModel` and implements `MTLJSONSerializing` as in `class Model: MTLModel, MTLJSONSerializing { … }`

**Comment by ZhuCanle** [comment]
Yes,I found it works,but a new problem.
This is the print of a JSON dictionary
`
[errMsg: success, querySign: 1699796238,2926092911, retData: (
        {
        rect =         {
            height = 36;
            left = 83;
            top = 295;
            width = 193;
        };
        word = "\U59d3\U540d\U6731\U707f\U4e50";
    },
    {
        rect =         {
            height = 33;
            left = 78;
            top = 467;
            width = 398;
        };
        word = "\U4f4f\U5740\U5e7f\U4e1c\U7701\U4f5b\U5c71\U5e02\U7985\U57ce\U533a\U540c\U798f";
    }), 
errNum: 0]
`
Use MTLJSONAdapter to parse it into model class.
But didn't get in the function `static func errNumJSONTransformer() -> NSValueTransformer {...}`
Others key paths works well.And it works well if I use MTLModel in ObjectiveC.
Sorry for my english.

**Comment by JanGorman** [comment]
If the function isn't called at all, maybe then it's missing from `JSONKeyPathsByPropertyKey`? Remember that since 2.0 Mantle won't infer property mappings automatically anymore.

```swift
static func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject]! {
  return [
    "errNum": "errNum"
  ]
}
```

And of you name it something else from `errNum` (e.g. `error`) in your model class, then the transformer name needs to match the name of the property, not the key in the JSON.

**Comment by ZhuCanle** [comment]
The property errNum can't be UInt.I use NSNumber instead.
