### ISSUE TITLE
Custom adapters to get raw JSONDictionary

### ISSUE THREAD

**Issue by richsage** [Mantle/Mantle#660]
This is using Mantle 2.0.6 currently.

I have a slim model which maps to a more verbose JSON representation. Let's say I map 3 properties out of a possible 10 available. I'd like to store the full JSON for that model on a separate property in the model itself. For example:

```
@interface User : MTLModel <MTLJSONSerializing>

@property (copy, nonatomic, readonly) NSString *firstName;
@property (copy, nonatomic, readonly) NSString *lastName;
@property (copy, nonatomic, readonly) NSString *emailAddress;

@property (strong, nonatomic) NSString *rawJSON;

@end
```

so that I can then peek at it later on. Writing a custom protocol eg `RequiresRawJSON`, along with a custom adapter based on `MTLJsonAdapter` that checks for this protocol seemed like the logical way to go as the `JSONDictionary` object has this data. However I can't see how to use this adapter explicitly anywhere. Is there a better/more accepted way to do this?

**Comment by revolter** [comment]
I did exactly this the past days, and I achieved it by subclassing `MTLJSONAdapter`, copy+pasting the `+ (NSValueTransformer<MTLTransformerErrorHandling> *)JSONStringTransformerWithModelClass:(Class)modelClass` method, and adding a `NSDictionary` from `NSString` conversion in the forward block, and a `NSString` from `NSDictionary` conversation in the reverse block.
