### ISSUE TITLE
[MTLReversibleValueTransformer encodeWithCoder:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by engmsaleh** [Mantle/Mantle#662]
I have a property named `content` that is sent in JSON and it some times it is a custom object in my case `FeatureContent` and other times it is just a `string`

I have implemented the below `contentJSONTransformer`

```
+ (NSValueTransformer *)contentJSONTransformer {
    return [MTLValueTransformer transformerUsingForwardBlock:^id(id object, BOOL *success, NSError *__autoreleasing *error) {
        if ([object isKindOfClass:[NSDictionary class]]) {
            return [MTLJSONAdapter dictionaryTransformerWithModelClass:[FeatureContent class]];
        }else{
            return (NSString*)object;
        }
    } reverseBlock:^id(id object, BOOL *success, NSError *__autoreleasing *error) {
        if ([object isKindOfClass:[FeatureContent class]]) {
            return [MTLJSONAdapter JSONDictionaryFromModel:object error:nil];
        }else{
            return (NSString*)object;
        }
    }];
}
```

It works with custom objects and crashes with the string and gives the following error
`[MTLReversibleValueTransformer encodeWithCoder:]: unrecognized selector sent to instance`

I don't know what I'm making wrong? are this the appropriate way to handle such case?

**Comment by istx25** [comment]
@engmsaleh: Did you ever find a solution for this problem?
