### ISSUE TITLE
How to ignore objects with -arrayTransformerWithModelClass:

### ISSUE THREAD

**Issue by js** [Mantle/Mantle#668]
Given json like `{things: [{"type": "post",..}, {"type": "news",..}]}` I've used  `classForParsingJSONDictionary:` to parse the different content types using subclasses. However, should a new content type appear from the backend I want to ignore it, since the app doesn't support yet so that I can gracefully update the API with new types without worrying about breaking old clients.

Before Mantle 2.x I could return nil from `classForParsingJSONDictionary:` to ignore a type, however as of 2.x returning nil aborts parsing and returns an error.

How can i implement the previous functionality nicely? I don't want to replicate all the of the `+[MTLJSONAdapter arrayTransformerWithModelClass:]` with the only difference to ignore the unsupported types and it doesn't seem like I can compose different transformers?

**Comment by js** [comment]
I guess one way is something like this, but that feels a bit dirty?
```objc
- (instancetype)initWithDictionary:(NSDictionary *)dictionaryValue error:(NSError *__autoreleasing *)error {
    if ((self = [super initWithDictionary:dictionaryValue error:error])) {
        NSMutableArray *widgets = [_widgets mutableCopy];
        [_widgets enumerateObjectsUsingBlock:^(Widget *obj, NSUInteger idx, BOOL *stop) {
            if (![[Widget knownWidgetTypes] containsObject:obj.identifier]) {
                [widgets removeObject:obj];
            }
        }];
        _widgets = widgets;
    }
    return self;
}
```

**Comment by robb** [comment]
I'd suggest creating a transformer similar to `+arrayTransformerWithModelClass:` that ignores errors with a `MTLJSONAdapterErrorNoClassFound` code and a `MTLJSONAdapterErrorDomain` domain
