### ISSUE TITLE
MTLJSONAdapter not found

### ISSUE THREAD

**Issue by serhatsezer** [Mantle/Mantle#670]
When I embed Mantle folder into the my project without pod XCode said "#import <Mantle/MTLJSONAdapter.h>" file not found. I added screenshot below.

![screen shot 2016-01-12 at 17 32 31](https://cloud.githubusercontent.com/assets/1409961/12267886/ea7a77b2-b952-11e5-82b4-175b13bc3c1f.png)

**Comment by robb** [comment]
Did you follow the [setup instructions](https://github.com/Mantle/Mantle#importing-mantle)?

**Comment by serhatsezer** [comment]
Why ? Why did I have to do this? @robb

**Comment by robb** [comment]
Mantle is not written in a way that allows direct embedding into a project by copying the files over, so I strongly suggest using the approach described in the setup instructions (embedding the project). Alternatively, Carthage or CocoaPods can make that easier for you :sparkles:

**Comment by serhatsezer** [comment]
@robb Thank you for explanation.
