### ISSUE TITLE
I find it hard to convert items of an array into different properties

### ISSUE THREAD

**Issue by billdavid** [Mantle/Mantle#673]
For the following json (which is part of the json response of a google api):
industryIdentifiers =                 (
                                        {
                        identifier = 7542637975;
                        type = "ISBN_10";
                    },
                                        {
                        identifier = 9787542637970;
                        type = "ISBN_13";
                    }
                );
I have two properties as isbn10 and isbn13. How can I fill the two properties with mantle?

**Comment by billdavid** [comment]
I finally solved it by overriding the setter of an extra and temp industryIdentifiers property which is defined as an array, and then set isbn10 and isbn13 by iterate contents of array.
Is there any better solution?

**Comment by dcaunt** [comment]
Can you post your model header? Then it will be easier to understand what your desired result is, and how to get there.
