### ISSUE TITLE
Mantle add double quotes when finding an underscore caracter in json key

### ISSUE THREAD

**Issue by MBagory** [Mantle/Mantle#674]
It seems that Mantle add double quotes to json keys when finding an underscore caracter.

For instance

```objective-c
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"addressCountry_id":@"addressCountry_id"
             };
}
```

Will produce

```json
{ 
        "addressCountry_id" = 2;
}
```

Whereas 

```objective-c
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"addressCountryId":@"addressCountryId"
             };
}
```

Will produce 

```json
{ 
        addressCountry_id = 2;
}
```

Is it expected ?

**Comment by robb** [comment]
Those snippets look like `NSLog` output, are you sure that those quotes aren't just part of how `NSLog` or `-[NSString description]` work for strings with underscores?

**Comment by MBagory** [comment]
You're right it's copy paste from NSLog. It's still causing an api error, I'll investigate and let you know. Thanks for your reactivity

**Comment by robb** [comment]
Tentatively closing this one, feel free to reopen if the problem persists. :v:

**Comment by MBagory** [comment]
Problem solved elsewhere. Output was only a log formatting as you suggested.

Thanks for your support!
