### ISSUE TITLE
[1.5.x] "Ambiguous expansion of macro 'weakify' "

### ISSUE THREAD

**Issue by fabiomassimo** [Mantle/Mantle#675]
Hi,
I'd like to fix an issue that occurs when trying to include Mantle (1.5.x) via CocoaPods by using `use_frameworks!` (see: https://github.com/Mantle/Mantle/issues/488).

Since [new PR policy for CocoaPods Specs](https://github.com/CocoaPods/Specs/pull/12199), I think we need to create a patch version bump to actually push a fixed podspec to CocoaPods master.

Would it be a solution or is it there a better way to apply a fix for current version? We could use `pod trunk` but not sure it is the right thing to do.

Should I create a PR with new tag for version `1.5.7`?

Thanks.

**Comment by robb** [comment]
Thanks for looking into this :sparkling_heart: 

Not sure what the PR would include, but can you target the [`1.x-maintenance`](https://github.com/Mantle/Mantle/tree/1.x-maintenance) branch?

**Comment by fabiomassimo** [comment]
Sorry @robb for the late reply.

So basically the Podspec has to change in this:

```ruby 
Pod::Spec.new do |s|

  s.name         = 'Mantle'
  s.version      = '1.5.8'
  s.summary      = 'Model framework for Cocoa and Cocoa Touch.'
  s.homepage     = 'https://github.com/Mantle/Mantle'
  s.license      = 'MIT'
  s.author       = { 'GitHub' => 'support@github.com' }
  s.platform     = :ios, '5.0'
  s.source       = { :git => 'https://gitlab.touchwonders.com/components/mantle.git',
                     :tag => s.version}
  s.requires_arc = true

  s.subspec 'extobjc' do |cs|
    cs.source_files = "Mantle/extobjc"
    cs.private_header_files = 'Mantle/extobjc/*.h'
  end

  s.source_files = 'Mantle/*.{h,m}'
  
end```

This is the important bit which has to be replace in current 1.5.7 Podspec.

```ruby
[..]

  s.subspec 'extobjc' do |cs|
    cs.source_files = "Mantle/extobjc"
    cs.private_header_files = 'Mantle/extobjc/*.h'
  end
```

**Comment by dcaunt** [comment]
I see. If I understand correctly, the subspec for [1.5.7](https://github.com/CocoaPods/Specs/blob/master/Specs/Mantle/1.5.7/Mantle.podspec.json) needs updating to match that of [2.0.7](https://github.com/CocoaPods/Specs/blob/master/Specs/Mantle/2.0.7/Mantle.podspec.json).

I can create a new tag for 1.5.8 and push a new spec, if you confirm, @fabiomassimo.

**Comment by fabiomassimo** [comment]
Yes I confirm.

Thank you @dcaunt.

**Comment by dcaunt** [comment]
@fabiomassimo A spec for 1.5.8 has been pushed, let me know if it works.

**Comment by Thomvis** [comment]
Co-worker of @fabiomassimo here. He asked me to try it out 1.5.8. Everything seems to be working great! Thanks!

**Comment by dcaunt** [comment]
Closing this one then, thanks.
