### ISSUE TITLE
why are most of the properties copy

### ISSUE THREAD

**Issue by puneetgoyal08** [Mantle/Mantle#677]
I have seen in the examples that most of the properties are defines as copy. Can you please tell me if that is required? If yes then why?

Thanks!

**Comment by JanGorman** [comment]
It is not required but good practice for properties with classes that have mutable subclasses (think `NSArray` and `NSMutableArray, `NSString` and `NSMutableString`, etc.). With those classes, you could pass in a mutable counter part and mutate them from the outside, the copy prevents this.

**Comment by robb** [comment]
Yup, there's some examples for that [on Apple's Developer site](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/EncapsulatingData/EncapsulatingData.html#//apple_ref/doc/uid/TP40011210-CH5-SW35), too. :v:
