### ISSUE TITLE
Deciding class for deserializing of a class cluster

### ISSUE THREAD

**Issue by revolter** [Mantle/Mantle#678]
So, I have these models:
- `User : MTLModel`, which has a property named `progress` of type `Progress : MTLModel`
- `CompletedProgress : Progress`
- `LogProgress : Progress`

And I want to decide based on the JSON, how to deserialize it.

I added in the `Progress.m` this overridden method:

	+ (Class)classForParsingJSONDictionary:(NSDictionary *)JSONDictionary {

		if (JSONDictionary[@"learning_unit_logs"]) {
			return [LogProgress class];
		} else {
			return [CompletedProgress class];
		}
	}

but I would also need to know this in the `User` class when serializing.

Something along the lines of using `+ (NSValueTransformer *)progressJSONTransformer;`, but this is a class method.

Isn't there an instance method like the one above, in which I could decide which class to use for serializing?

**Comment by robb** [comment]
I don't fully understand why you need an instance method, how is the `User` affected by the progress class?

**Comment by revolter** [comment]
Well, I'm sorry, I don't fully understand how Mantle works so I can properly explain, but I'll try to rephrase is as necessary.

I tried using this:

	+ (NSValueTransformer *)progressJSONTransformer {

		return [MTLJSONAdapter dictionaryTransformerWithModelClass:[Progress class]];
	}

but it tries to call the `JSONKeyPathsByPropertyKey` method on the `Progress` class, instead of `CompletedProgress` or `LogProgress`.

**Comment by revolter** [comment]
Otherwise, it doesn't know how to serialize the `progress` property. So I'm thinking of something along the lines of:

	+ (NSValueTransformer *)progressJSONTransformer {

		return [MTLJSONAdapter dictionaryTransformerWithModelClass:[self.progress class]];
	}

**Comment by revolter** [comment]
I got it to work by replacing [this line](https://github.com/Mantle/Mantle/blob/master/Mantle/MTLJSONAdapter.m#L527) with `adapter = [[self alloc] initWithModelClass:[model class]];`. Shouldn't it be this way already? If not, could I subclass `MTLJSONAdapter` and override it? Or is there any method that is automatically called by `Mantle` in which to implement this logic?

**Comment by revolter** [comment]
@robb, Any updates on this? Should I provide more information?

**Comment by robb** [comment]
@revolter that change is going to create some problems when the `class` of the model changes, as the `__block MTLJSONAdapter *adapter` variable is going to capture an adapter for the first class that get's deserialized.

**Comment by revolter** [comment]
@robb But did you understand my use case?

**Comment by robb** [comment]
Yeah

**Comment by JanGorman** [comment]
I haven't had issues with `classForParsingJSONDictionary` so far. I put together a quick demo over here: https://github.com/JanGorman/MantleDemo which creates two user objects. When I log the classes I get 

```
2016-02-11 17:25:10.093 Mantle[71119:1653421] LOG USER <User: 0x7fd60b814fe0> {
    id = abc;
    progress = "<LogProgress: 0x7fd609d03210> {\n}";
}
2016-02-11 17:25:10.094 Mantle[71119:1653421] COMPLETED USER <User: 0x7fd60bb03180> {
    id = def;
    progress = "<CompletedProgress: 0x7fd60bb08d70> {\n}";
}
```

@revolter See `ViewController.m` for the sample dictionaries I used. Does your data look similar to this?

**Comment by revolter** [comment]
Hmm, it seems to be working now. It's not clear in my mind why it wasn't, and why is not. Sorry for taking your time.

**Comment by robb** [comment]
No worries ✌
