### ISSUE TITLE
Help: Model for an edit page?

### ISSUE THREAD

**Issue by kylerobson** [Mantle/Mantle#688]
So I understand that immutable objects are good, but what if I want a mutable copy of the immutable object? Can Mantle do that? If so how? Basically I want to know how you recommend to handle this use case:

* User is on list page
* User taps list item, navigates to detail page
* Detail page has a label for every property on that item (strings, dates, etc)
* User taps edit, now every label changes to a text field, date picker, etc

Since mantle models are immutable, what does the edit page mutate? I'm hoping the answer isn't a mutable dictionary... model objects are so much nicer to work with than dictionaries...

**Comment by conradev** [comment]
@kylerobson, you can make a subclass of your model that is mutable, and make your model conform to `NSMutableCopying`, where it returns an instance of this subclass. This is how all of the foundation classes operate.

```objc

@interface Foo : MTLObject <NSMutableCopying>

@property (nonatomic, readonly, copy) NSString *name;

@end

@interface MutableFoo : Foo

@property (nonatomic, copy) NSString *name;

@end

@implementation Foo

- (id)mutableCopyWithZone:(nullable NSZone *)zone {
	MutableFoo *copy = [[MutableFoo allocWithZone:zone] init];
	[copy setValuesForKeysWithDictionary:self.dictionaryValue];
	return copy;
}

@end
```

**Comment by kylerobson** [comment]
Thanks for the quick response. I'll probably go with the mutable copy route. Super nice once the work is done, but having 1x model for CD, 1x model for immutable, and 1x model for mutable sounds like some would find that hard to swallow. I suppose it'll depend a bit on the needs of this hypothetical app.

**Comment by dcaunt** [comment]
You may also find this article on [lightweight immutability](http://www.jonmsterling.com/posts/2012-12-27-a-pattern-for-immutability.html) useful.
