### ISSUE TITLE
NSInteger Mapping, NSValue but got NSTaggedPointerString

### ISSUE THREAD

**Issue by accfews** [Mantle/Mantle#691]
I have a big JSON and all the mapping works fine until the inner part. 

`Error =       {
            code = 1;
            message = "An error occurred. Please try again later.";
        };
`

`@property (copy, nonatomic) NSString *message;
@property (assign, nonatomic) NSInteger code;`

when I try to map it everything works fine but not the 'code' field 

`
- (id)transformedValue:(id)value success:(BOOL *)outerSuccess error:(NSError **)outerError {
	NSError *error = nil;
	BOOL success = YES;
	id transformedValue = self.forwardBlock(value, &success, &error);
	if (outerSuccess != NULL) *outerSuccess = success;
	if (outerError != NULL) *outerError = error;

	return transformedValue;
}`

This method generates an error of 

@"Expected 1 to be of class NSValue but got NSTaggedPointerString"

How to fix this issue

**Comment by dcaunt** [comment]
Can you post the code for the relevant model classes and the JSON please?

**Comment by accfews** [comment]
`{
    meta =     {
        error =         {
            code = 1;
            message = "An error occurred. Please try again later.";
            title = "";
        };
        success = 0;
    };
}`

```
@property (assign, nonatomic) NSInteger code;
@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSString *message;

+ (NSDictionary *)JSONKeyPathsByPropertyKey
{
    NSDictionary *baseKeyPathDictionary = [super JSONKeyPathsByPropertyKey];
    NSDictionary *jsonKeyPathDictionary = @{
                                            @"title"    : @"title",
                                            @"code"     : @"code",
                                            @"message"  : @"message",
                                            };;
    
    return [baseKeyPathDictionary mtl_dictionaryByAddingEntriesFromDictionary:jsonKeyPathDictionary];
}
```

```
@property (assign, nonatomic) BOOL success;
@property (strong, nonatomic) ErrorResponse *error;

+ (NSDictionary *)JSONKeyPathsByPropertyKey
{
    NSDictionary *baseKeyPathDictionary = [super JSONKeyPathsByPropertyKey];
    NSDictionary *jsonKeyPathDictionary = @{
                                            @"success" : @"success",
                                            @"error"   : @"error",
                                            };
    
    return [baseKeyPathDictionary mtl_dictionaryByAddingEntriesFromDictionary:jsonKeyPathDictionary];
}

+ (NSValueTransformer *)errorJSONTransformer
{
    return [MTLJSONAdapter dictionaryTransformerWithModelClass:[ErrorResponse class]];
}
```
It seems like issue here is type of code is NSTaggedPointerString

[http://i.hizliresim.com/VaWrMr.png](url)

**Comment by dcaunt** [comment]
It looks like the 'JSON' you provided is `NSLog` output, but my guess is that the `code` field in your JSON is a string, i.e. `code: "1"` rather than a number, i.e. `code: 1`. You can either change the `code` property to be of type `NSString` or use a transformer to attempt to convert the string to a number.

**Comment by accfews** [comment]
Yes you are right I checked it again server sends `String`, idiotic `NSLog` directed me wrong, its very confusing. I fixed it by changing type of `code` to `NSString`. 

Thanks for your time and effort
