### ISSUE TITLE
Swift enum can't cast

### ISSUE THREAD

**Issue by codwam** [Mantle/Mantle#692]
```
enum RequestGender: String {
    case None = ""
    case Male = "MALE"
    case Female = "FEMALE"
    
    func chineseName() -> String {
        switch self {
        case .None:
            return ""
        case .Male:
            return "男"
        case .Female: 
            return "女"
        }
    }
}

final class TestModel: MTLModel, MTLJSONSerializing {
    var career = ""

    var gender: RequestGender = .None
    
    static func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject]! {
        // This will be crash
//        return [
//            "career": "career",
//            "gender": "gender",
//        ]
        let jsonKey = NSDictionary.mtl_identityPropertyMapWithModel(self.classForCoder())
        // Print:  [career: career]
        debugPrint(jsonKey)
        return jsonKey
    }
}

        let dic = [
            "career": "test career",
            "gender": "MALE",
        ]
        let model = try? MTLJSONAdapter.modelOfClass(TestModel.self, fromJSONDictionary: dic)
        debugPrint(model)
```

**Comment by JanGorman** [comment]
Objective-C can only see Swift enums with an `Int` raw type, since your's is marked as `:String` this will not work.

**Comment by codwam** [comment]
OK, I want to ask another question.

Why [String] can auto cast, but custom class can't ?

`class TestCustomModel {
    
    var abc = ""
    
}

final class TestModel: MTLModel, MTLJSONSerializing {
    var career = ""
    
    var customModel = [String]()
    // This can't be work, only with implement 'JSONTransformerForKey'
//    var customModel = [TestCustomModel]()
    
    static func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject]! {
        let jsonKey = NSDictionary.mtl_identityPropertyMapWithModel(self.classForCoder())
        // Print:  [career: career]
        debugPrint(jsonKey)
        return jsonKey
    }
    
    class func customModelJSONTransformer() -> NSValueTransformer {
        
        return MTLJSONAdapter.arrayTransformerWithModelClass(HomeCasesModel_Content.classForCoder())
    }
    
    static func JSONTransformerForKey(key: String!) -> NSValueTransformer! {
        if key == "customModel" {
            return self.customModelJSONTransformer()
        }
        return nil
    }
}`

**Comment by JanGorman** [comment]
If I understand your question correctly, you're asking why you need to create a `customModelJSONTransformer` but not for a String?
Look at it from the framework's perspective: how could it know about your custom class and what to do with it? 
Take another look at the [README](https://github.com/Mantle/Mantle/blob/master/README.md) – the example with the `assigneeJSONTransformer` (corresponding [JSON](https://developer.github.com/v3/issues/#get-a-single-issue) shows that this is another complex object and you'll need to tell Mantle how to transform this. You can spin this further and nest your objects however deep you want.

**Comment by codwam** [comment]
Thanks
