### ISSUE TITLE
NSKeyedArchiver MTLModel with nested NSArray of MTLModel

### ISSUE THREAD

**Issue by crsantos** [Mantle/Mantle#695]
This is more a doubt than an issue, I guess.
I would like to know how to serialise/desirialize from NSKeyedArchiver a MTLModel with another nested MTLModel.

Imagine that I have a `User` model that contains a property that is an array of `Dog` like the following:

```obj-c
@interface Dog : MTLModel <MTLJSONSerializing>
@property (nonatomic, copy) NSString *dogName;
@end

@interface User : MTLModel <MTLJSONSerializing>
@property (nonatomic, copy) NSString *userId;
@property (nonatomic, strong) NSArray<Dog *> *dogs;
@end
```

Right now I'm serialising a `User` like this `[NSKeyedArchiver archiveRootObject:movie toFile:filename];` but when I deserialise it, the array of dogs is empty...

Am I missing something?
Should I store only the JSON model instead of trying to serialise the whole object?

Note: I have all the `MTLJSONSerializing` methods implemented, including:

```obj-c
+ (NSValueTransformer *)dogsJSONTransformer {

    return [MTLJSONAdapter dictionaryTransformerWithModelClass:Dog.class];
}
``` 
Is that maybe this method that is expecting to map a single `Dog` instead of an array of them?
Thanks in advance

**Comment by conradev** [comment]
1. When you *serialize* the `User` object using `NSKeyedArchiver`, does it have any `dogs` on it?

2. You definitely want `[MTLJSONAdapter arrayTransformerWithModelClass:Dog.class]` as your JSON transformer, so that it handles multiple objects.

**Comment by crsantos** [comment]
> You definitely want `[MTLJSONAdapter arrayTransformerWithModelClass:Dog.class]`

So I spotted that typo earlier and replaced `dictionaryTransformerWithModelClass ` with `arrayTransformerWithModelClass:`. I'm sorry, forgot to update my post 😞 

> does it have any dogs on it

Yes, it have, plenty of them.

Apart from that, there's something really strange here...
I made a quick test to check if I don't have a typo on the transformer:

When I call `[userInstance dictionaryValue]` I get an `NSDictionary` with `userId` key/value but on the dogs array.. It doesn't contain an array of `NSDictionary` with all `Dog` serialized.. but instead... an array of `Dog`..
It looks like it fails to transform the array of `Dog` to `NSDIctionary` and inserts the full object instead of its dict representation.

**Comment by crsantos** [comment]
Ok, it's not `[userInstance dictionaryValue]` that I'm looking for... My bad.
Switched to `MTLJSONAdapter JSONDictionaryFromModel:error:` instead.

I can convert everything to JSON a persist like that but that's not the solution I want.
For some reason.. `NSKeyedArchiver archiveRootObject:toFile:` is not persisting the array of `Dog`

**Comment by JanGorman** [comment]
@crsantos Could you post some more code? I did something similar in the past and just tried your dog example:

```objective-c
@interface Dog : MTLModel
@property(copy, nonatomic) NSString *dogName;
- (instancetype)initWithName:(NSString *)name;
@end

@implementation Dog
- (instancetype)initWithName:(NSString *)name {
    self = [super init];
    if (self) {
        _dogName = name;
    }
    return self;
}
@end

@interface User : MTLModel
@property(copy, nonatomic) NSString *userId;
@property(copy, nonatomic) NSArray<Dog *> *dogs;
@end

@implementation User
@end
```

And then archiving/unarchiving:

```objective-c
    Dog *pluto = [[Dog alloc] initWithName: @"pluto"];
    Dog *snoopy = [[Dog alloc] initWithName: @"snoopy"];
    
    NSArray *dogs = @[pluto, snoopy];
    
    User *user = [[User alloc] init];
    user.userId = @"abc";
    user.dogs = dogs;
    
    NSData *data = [NSKeyedArchiver archivedDataWithRootObject:user];
    
    User *unarchivedUser = [NSKeyedUnarchiver unarchiveObjectWithData:data];
    NSLog(@"Unarchived: %@", unarchivedUser);
```

which prints out

```
Unarchived: <User: 0x7f83634afa40> {
    dogs =     (
        "<Dog: 0x7f836480d5a0> {\n    dogName = pluto;\n}",
        "<Dog: 0x7f8364813860> {\n    dogName = snoopy;\n}"
    );
    userId = abc;
}
```

as you'd expect.

**Comment by crsantos** [comment]
@conradev @JanGorman thanks for trying to help me out on this one.

@JanGorman Your snippet works fine for the User/dog model... however my real code doesn't and I can't find the issue, not even a difference from the User/Dog models.
I have a `NSMutableArray` for one of the subproperties, but that's not the issue, ofc. (tested the same approach on `dogs` and everything works).

I have a more complex model. Any chance I can show you the code outside from Github?

**Comment by JanGorman** [comment]
@crsantos DM me on Twitter, same username

**Comment by crsantos** [comment]
I'm not a twitter power user, but doesn't twitter require both users to follow each other to be able to trade  DMs?

**Comment by crsantos** [comment]
Please, forgive me.
I was using an `-init` and `initWithDictionary:` one was initiliazing the arrays, the other one was reseting the arrays... Honest mistake 😢 
Thanks @JanGorman for spotting that out.
🎉
