### ISSUE TITLE
2.0.7 can supports iOS 7.0+.

### ISSUE THREAD

**Issue by xiongcaixing1986** [Mantle/Mantle#708]
If the source code or Static library to join 2.0.7, Can support iOS 7.0+

**Comment by dcaunt** [comment]
Not sure if this is a question, but there's is some discussion of iOS 7 support in #666

**Comment by xiongcaixing1986** [comment]
thanks

**Comment by dcaunt** [comment]
Closing this for now, please reopen or create a new issue if you have more questions.
