### ISSUE TITLE
IOS unit test crash in Mantle, when the complex dictionary turn model.

### ISSUE THREAD

**Issue by ny8080** [Mantle/Mantle#714]
When I am ready to use the unit test to evoke a view controller, view controlle has a dictionary switch model. Unit testing does not collapse when there are no other references to the dictionary model. But when I'm going to switch the model in a reference to the other objects, the unit test will crash.
<img width="928" alt="42eeb614-39b6-416c-9bc9-bb2137db71f6" src="https://cloud.githubusercontent.com/assets/12273689/16110320/c1a5ae62-33df-11e6-8c33-c475645dc718.png">

<img width="741" alt="ab9ca702-b1a0-4cce-aba8-d10908ddcbae" src="https://cloud.githubusercontent.com/assets/12273689/16110321/c2289dc2-33df-11e6-863f-7a403f1e3588.png">

My mailbox czwny8800@163.com。I hope you can take a look at what is the problem. And give me a feedback. Thank you very much

**Comment by ny8080** [comment]
Why to use Mantle to crash in iOS unit test？ When a subclass of MTLModel attributes to merge with another MTLModel's child class attribute, it will crash. This situation is the 100% crash！

**Comment by dcaunt** [comment]
I'm finding it hard to understand your question here. Please could you post your model code and test code which demonstrates the problem in full?

**Comment by ny8080** [comment]
Please look at the following code screenshot 
<img width="891" alt="codetest" src="https://cloud.githubusercontent.com/assets/12273689/16438551/70a56f62-3de3-11e6-89e8-f046a37d664a.png">
<img width="868" alt="request" src="https://cloud.githubusercontent.com/assets/12273689/16438557/7b18a7ac-3de3-11e6-9155-21838fed1e5a.png">
<img width="811" alt="request1" src="https://cloud.githubusercontent.com/assets/12273689/16438564/87a1438a-3de3-11e6-97dd-40bcf9c6fe32.png">
![b2beec9c-d325-4e5c-8bff-ecb7f7e0ed29](https://cloud.githubusercontent.com/assets/12273689/16438788/289e8f1c-3de5-11e6-9415-731a577d4133.png)

This is my unit test, evoke a controller. Controller inside a network request, need to use Mantle.Like the last picture, the mode will cause a crash in the unit test.But the other way is right.
 Is it Ok that I have to revise it in this way？Or I have to check it in the unit test？Pls help advise it
 Thank you

**Comment by JanGorman** [comment]
Same issue was #724
