### ISSUE TITLE
Using pointer-based equality checking?

### ISSUE THREAD

**Issue by archagon** [Mantle/Mantle#718]
`MTLModel` implements hash and equality checking in terms of property keys, whereas in my project it makes more sense to compare objects by pointer (as is the default `NSObject` behavior). Is it enough to subclass `MTLModel` and replace `hash` and `isEqual:`, or are there other issues to watch out for?

**Comment by conradev** [comment]
Yes, that approach makes total sense. You can override `hash` and `isEqual:` to do as you describe.

If your object is immutable, you can also override the `NSCopying` implementation to just return `self`:
``` objc
- (id)copyWithZone:(nullable NSZone *)zone {
    return self;
}
```
instead of doing a deep copy, which can be expensive.

**Comment by archagon** [comment]
Nice! Thank you.
