### ISSUE TITLE
NSNumber *boolean coming in as NSTaggedPointerString @"True"

### ISSUE THREAD

**Issue by brandtdaniels** [Mantle/Mantle#737]
In NSValueTransformer+MTLPredefinedTransformerAdditions

```
MTLValueTransformer *booleanValueTransformer = [MTLValueTransformer
			transformerUsingReversibleBlock:^ id (NSNumber *boolean, BOOL *success, NSError **error) {
				if (boolean == nil) return nil;
```

boolean is listed as an NSTaggedPointerString @"True" in the debugger.

for this value I am using 

```
[NSValueTransformer valueTransformerForName:MTLBooleanValueTransformerName];
```

**Comment by dcaunt** [comment]
Can you post your model code and sample JSON please?

**Comment by brandtdaniels** [comment]
Thanks for the response....turns out the API I was consuming, the documentation (contract) didn't match what the API was actually returning ;-(
