### ISSUE TITLE
Crash while transforming value

### ISSUE THREAD

**Issue by shiios** [Mantle/Mantle#738]
crash:
         reason:-[__NSCFString stringValue]: unrecognized selector sent to instance 0x13de1bd90
         place:
![snip20160721_3](https://cloud.githubusercontent.com/assets/14368983/17012244/7b463174-4f48-11e6-865e-65502e357645.png)

        hope your  answer!!

**Comment by dcaunt** [comment]
Please post your model code and JSON here (as code blocks, not Xcode screenshots) and we'll try to help.

From the error message it looks something is calling `stringValue` on an object expected to be an `NSNumber` which is actually an `NSString`, but would need to see your code to confirm.

**Comment by dcaunt** [comment]
Closing in favour of #740 which has more detail.
