### ISSUE TITLE
Lazy initialization of model objects

### ISSUE THREAD

**Issue by mrtj** [Mantle/Mantle#739]
I am working on a REST client that supports the lazy initialization of model objects. All objects in the system have an `identifier` and the model classes know how to fetch their data from the remote service. Thus if one knows the `identifier` of a particular object, it is possible to create that object locally and ask it to fetch its data only when it is needed:

```
Person* lazyPerson = [Person personWithIdentifier:@"1234"];
// pass lazyPerson around and call fetchData when the data is actually needed:
[lazyPerson fetchData:^(Person* fetchedPerson) { 
    // use fetchedPerson 
}];
```

Due to the design of Mantle in the implementation of `fetchData` I am constrained to create a new `Person` object (`fetchedPerson`) by calling `+[MTLJSONAdapter modelOfClass: fromJSONDictionary: error:]` and return the new object in the callback block. 

```
-(void)fetchData:(void (^)(Person* fetchedPerson))callback {
  NSURL* url = [Person URLFromIdentifier:self.identifier];
  [MyRestClient GET:url callback:^(NSDictionary* JSONDictionary) {
    Person* fetchedPerson = 
      [MTLJSONAdapter modelOfClass:[Person.class] 
                fromJSONDictionary:JSONDictionary 
                             error:nil]; // error handling in real code
      callback(fetchedPerson);
  }];
}
```

It would be very convenient if I could inject the newly fetched data directly in the original object (`lazyPerson`). 

I propose a new Mantle method that allows "patching" an already existing object with a JSON dictionary to allow the implementation of the lazy initialization pattern outlined above. The new method could have a similar signature: 
```
+(void)patchObject:(id<MTLJSONSerializing>)object
withJSONDictionary:(NSDictionary*)JSONDictionary
             error:(NSError **)error];
```

And the possible usage for lazy initialization:
```
-(void)fetchData:(void (^)(BOOL success))callback {
  NSURL* url = [Person URLFromIdentifier:self.identifier];
  [MyRestClient GET:url callback:^(NSDictionary* JSONDictionary) {
      [MTLJSONAdapter patchObject:self
               fromJSONDictionary:JSONDictionary 
                            error:nil];
      callback(YES);
  }];
}
```

Please note that in this description for illustration purpose only I showed a concrete example but supporting the lazy pattern would have benefit for many different use cases.

**Comment by dcaunt** [comment]
Apologies if I've misunderstood your use-case, but can you achieve this with [`-[MTLModel mergeValuesForKeysFromModel:]`](https://github.com/Mantle/Mantle/blob/b1606ead5fb50b2758802ccc63879d1a29b6f557/Mantle/MTLModel.h#L132)? 

You would instantiate a model from the JSONDictionary and then merge it into the existing one.

**Comment by conradev** [comment]
We do exactly this to achieve progressive fetching.

**Comment by mrtj** [comment]
So I need to create a model object from the new JSON dictionary and then use `mergeValuesForKeysFromModel:`? Maybe it would be convenient to have a method that directly merges the values from the JSON dictionary to an existing model object?

**Comment by dcaunt** [comment]
I don't think this convenience belongs in Mantle itself, but you could easily write a category method which deserialises the JSON and merges the result model into the existing one.

**Comment by mrtj** [comment]
Ok thank you very much for all this information. This ticket can be closed.
