### ISSUE TITLE
Crash when invoking -[MTLModel description]

### ISSUE THREAD

**Issue by PhilCai1993** [Mantle/Mantle#744]
```
@interface Restaurant: MTLModel
@property(copy) NSString *name;
@property (strong) Food *food; 
@end

@interface Food: MTLModel
@property(copy) NSString *name;
@property(weak) Restaurant *restaurant;
@end


// Restaurant JSON
{
"name":"KFC",
"food": {"name" : "tea"}
}

Restaurant *restaurant; // from JSON
Food *food = restaurant.food;
food.restaurant = restaurant; // Under certain circumstance, I have to assign this property by myself


NSLog(@"%@", restaurant);
```

This will crash because when invoking ```-[Restaurant description]```, ``` -[Food description]``` will be invoked, and then Restaurant and Food will recursively invoke description.

**Comment by dcaunt** [comment]
I think you should override `+[Food storageBehaviorForPropertyWithKey:]` and return `MTLPropertyStorageNone` for `key` `restaurant`. This will cause the default implementation of `-description` in `MTLModel` to omit the restaurant property altogether, but you could write your own implementation to include the pointer (not the description!).

**Comment by PhilCai1993** [comment]
It helps, thank you.
