### ISSUE TITLE
2.0.7 Mantle.framework doesn't contain Swift unavailable attributes

### ISSUE THREAD

**Issue by msanders** [Mantle/Mantle#753]
The framework given [here](https://github.com/Mantle/Mantle/releases/tag/2.0.7) doesn't seem to match what's on the 2.0.7 tag (in particular, the [`NS_SWIFT_UNAVAILABLE`](https://github.com/Mantle/Mantle/blob/cdb82df5dd3a7e4cfab6dfbc48df20dcc80b4e13/Mantle/MTLJSONAdapter.h#L281) attributes are missing). This is resolved by using `carthage bootstrap Mantle --no-use-binaries`. Is the right version uploaded?

**Comment by dcaunt** [comment]
Can you try with the freshly released [2.1.0](../releases/tag/2.1.0)?

**Comment by msanders** [comment]
That worked. Thanks!

**Comment by dcaunt** [comment]
Good stuff! Not sure what happened with 2.0.7 but glad to hear it's fine now.
