### ISSUE TITLE
How to convert "a json with nesting nsarray" to bean by using mantle?

### ISSUE THREAD

**Issue by lsqswl** [Mantle/Mantle#756]
``` json
{
    "result":[
        [
            {
                "a":"1"
            },
            {
                "a":"2"
            }
        ],
        [
            {
                "a":"3"
            },
            {
                "a":"4"
            }
        ]
    ]
}
```

**Comment by dcaunt** [comment]
Can you describe the resulting object(s) you'd like to create?

**Comment by sunwell** [comment]
Yeah, I have the same problem.
The json data looks like this: 
[](http://m.spider.com.cn/app20/getGiftList.action?key=spidersubscriber&sign=9B41B7A2C97B2E300B927AE6183F0712&fileType=json&platformId=1&itemId=100032,100046,100047,100131,100037,100029&count=10&page=1)

**Comment by dcaunt** [comment]
@sunwell Please create a separate issue and post the code for your models.

**Comment by sunwell** [comment]
@dcaunt  OK.
