### ISSUE TITLE
 How to combine coredata and mantle

### ISSUE THREAD

**Issue by forestfsl** [Mantle/Mantle#762]
In the old version of the time can be combined with the use of coredata, but the upgrade to coredata, found that 2.0.1's call method is not, the program is wrong, how to deal with it

wrong data
    for (NSManagedObject *object in mutableFetchResult) {
        NSError *err;
   

-      id message = [MTLManagedObjectAdapter modelOfClass:clazz fromManagedObject:object error:&err];

        if (!err) {
            [result addObject:message];

**Comment by dcaunt** [comment]
I'm not sure what the problem is here, but if you figure it out we would accept a pull request to fix it :)
