### ISSUE TITLE
How can I cause a JSON `null` to be generated for a field?

### ISSUE THREAD

**Issue by toby5box** [Mantle/Mantle#764]
I've searched the other issues, google, the README, etc and haven't been able to find the answer.

Example: I have an `NSNumber` field, say. And it is a null pointer. When I serialise it, I don't want its key omitted, but I want a `null` value in the JSON. How can I achieve this?

**Comment by CodeLife2012** [comment]
You need a custom transformer.

**Comment by toby5box** [comment]
Can you link me to the documentation for that, or an example?

**Comment by dcaunt** [comment]
@toby5box You need to return `NSNull.null` rather than nil, which you can do via a custom transformer.

You can do something like this, where `property` is the name of your nullable property:

```
+ (NSValueTransformer *)propertyJSONTransformer {
    return [MTLValueTransformer transformerUsingForwardBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
        // Return the value from JSON without applying a transformation
        return value;
    } reverseBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
        if (value == nil) {
            // Serialize the field as a null in JSON
            return NSNull.null;
        }

        return value;
    }];
}
```

Please feel free to reopen this issue if you need more help.

**Comment by toby5box** [comment]
Interesting. That did cross my mind, but the only code examples I had with `NSNull.null` were used to suppress the key entirely. The confusion could certainly be mine.
