### ISSUE TITLE
Lots of Memory leaks showing up doesn't ARC in build settings need to be on?

### ISSUE THREAD

**Issue by marcvanolmen** [Mantle/Mantle#765]
hi,

I see a lot of memory leaks in the Mantle library, doesn't ARC in build settings need to be on?

```
+ (id)modelOfClass:(Class)modelClass fromJSONDictionary:(NSDictionary *)JSONDictionary error:(NSError **)error {
	MTLJSONAdapter *adapter = [[self alloc] initWithJSONDictionary:JSONDictionary modelClass:modelClass error:error];
	return adapter.model;
}
```
The adapter object is leaking for example in the MTLJSONAdapter file.

Marc

**Comment by gupengno1** [comment]
I met the same problem,have you solved that?

**Comment by marcvanolmen** [comment]
Turn arc on in the target settings

**Comment by MarsLeo** [comment]
I met the same problem,have you solved that?

**Comment by marcvanolmen** [comment]
in Xcode Turn arc on in the target Building settings

**Comment by MarsLeo** [comment]
Xcode is arc

**Comment by marcvanolmen** [comment]
Ok let give this on more attempt, here a more detailed explanation:

https://stackoverflow.com/questions/9018366/how-to-enable-disable-arc-in-an-xcode-project
