### ISSUE TITLE
JSONKeyPath with . returns nil

### ISSUE THREAD

**Issue by tedgonzalez** [Mantle/Mantle#769]
in NSDictionary+MTLJSONKeyPath.m

      - (id)mtl_valueForJSONKeyPath:(NSString *)JSONKeyPath success:(BOOL *)success error:(NSError **)error {
	NSArray *components = [JSONKeyPath componentsSeparatedByString:@"."];

	id result = self;
	for (NSString *component in components) {
		// Check the result before resolving the key path component to not
		// affect the last value of the path.
		if (result == nil || result == NSNull.null) break;

		if (![result isKindOfClass:NSDictionary.class]) {
			if (error != NULL) {
				NSDictionary *userInfo = @{
					NSLocalizedDescriptionKey: NSLocalizedString(@"Invalid JSON dictionary", @""),
					NSLocalizedFailureReasonErrorKey: [NSString stringWithFormat:NSLocalizedString(@"JSON key path %1$@ could not resolved because an incompatible JSON dictionary was supplied: \"%2$@\"", @""), JSONKeyPath, self]
				};

				*error = [NSError errorWithDomain:MTLJSONAdapterErrorDomain code:MTLJSONAdapterErrorInvalidJSONDictionary userInfo:userInfo];
			}

			if (success != NULL) *success = NO;

			return nil;
		}

		result = result[component];
	}

	if (success != NULL) *success = YES;

	return result;
    }

all JSONKeyPath with <.> will be separated.
my problem is, i have keys from the json like
`
"sticker.name" : "sample name"
`
 and result[component] will always return nil

How do i work with this case? Thanks!

**Comment by JanGorman** [comment]
Your best bet in this case will probably be to recursively go through your response dictionary and replace all those `.` with something else (e.g. `__`). Keep in mind to adjust your `JSONKeyPathsByPropertyKey` methods to use the keys with the replacement (e.g. `@"stickerName": @"sticker__name"`)

**Comment by useeless37** [comment]
thanks @JanGorman !

**Comment by dcaunt** [comment]
See also #508
