### ISSUE TITLE
Would you consider rewriting Mantle in swift?

### ISSUE THREAD

**Issue by EvilNOP** [Mantle/Mantle#771]

**Comment by robb** [comment]
I don't believe this will provide any benefit.

That being said, there may be an opportunity for a better overlay.

**Comment by fabb** [comment]
This is a pretty similar Swift lib:
https://github.com/hkellaway/Gloss

Apart from that, now with Swift 4 we have `Codable` which could replace the need for Mantle alltogether. Do you think it would be possible to write an extension to Mantle to make all Mantle models `Codable` by default?

**Comment by fabb** [comment]
> Do you think it would be possible to write an extension to Mantle to make all Mantle models `Codable` by default?

Nope, as `Decodable` has a required initializer, which is not allowed to be defined in an extension in Swift 4.
