### ISSUE TITLE
Different between v1.5.8 and 2.0(later)

### ISSUE THREAD

**Issue by keyjacky** [Mantle/Mantle#773]
About the method `+ (NSDictionary *)JSONKeyPathsByPropertyKey` in `MTLJSONAdapter`

In V1.5.8(earlier) Any property keys not present in the dictionary are assumed to match the JSON
 key that should be used

But in V2.0(later), that convenient feature can not be found ! Can anyone tell me why?
or there is some other solution in V2.0(later)?

thx

**Comment by ikesyo** [comment]
You should see: https://github.com/Mantle/Mantle/blob/2.1.0/CHANGELOG.md#explicit-json-key-paths.

> For convenience, you can use `+[NSDictionary mtl_identityPropertyMapWithModel:]` to automatically create a one-to-one mapping that matches the previous default behavior.

**Comment by keyjacky** [comment]
thx
