### ISSUE TITLE
How to avoid Non JSON properties of class using Mantle Lib

### ISSUE THREAD

**Issue by AmolServiceHeroes** [Mantle/Mantle#776]
Hi Devs,

I'm trying to update Mantle version 1.3 to 2.0 in my application.

I'm following changes guideline while updating it. Now, I'm facing issue with nonJSON properties which are part of my business objects like "nativeObject" which type of UIView.

As per my requirement, I have created getter method of "nativeObject" with return type UIView. 
"nativeObject" is not a JSON response object property, now the issue is a - while preparing business object with the help of Mantle library and JSON response, "nativeObject" getter methods get called and which don't want, because objects get created before time and without some values. 

And that's the issue, I'm expecting from Mantle lib and lib should avoid nonJSON properties and go to JSON properties.

Also, added required JSON properties name in the following method.
+ (NSDictionary *)JSONKeyPathsByPropertyKey

Please check the following JSON, there is no "nativeObject" property and still, mantle calling getter method of "nativeObject" property.
{
	"label": "How are you",
        "type": "button",
	"styleRules": {
		"backgroundColor": "#FFFF00",
		"height": "20%",
		"textColor": "#FF0000",
		"width": "100%"
	}
}

Please help on this issue or you can correct me if anything wrong which I'm doing here.

**Comment by dcaunt** [comment]
Can you post the header and implementation of your model class please?

**Comment by AmolServiceHeroes** [comment]
JSON which is to parsed with mantle is as follows.

{"components":[**{"type":"Button","styleRules":{"textColor":"#FF0000","backgroundColor":"#FFFF00","width":"100%","height":"20%"},"label":"How are you"}**,{"type":"Text","styleRules":{},"text":"Text Component"}],"orientation":"portrait","scrollable":true,"type":"View","styleRules":{"width":"100%","backgroundColor":"#FF0000","height":"100%"},"layout":"vertical"}

Header implementation of base class is as follows

#import <UIKit/UIKit.h>
#import <Mantle/Mantle.h>

@interface SHNOMComponent : MTLModel <MTLJSONSerializing>

@property (nonatomic, strong) NSString *identifier;

@property (nonatomic, strong) NSArray *actions;

@property (nonatomic, strong) NSString *type;
@property (nonatomic, strong) NSString *style;

@property (nonatomic, strong) NSString *height __deprecated;
@property (nonatomic, strong) NSString *width __deprecated;

@property (nonatomic, strong) SHNOMStyle *styleRules;
@property (nonatomic, strong) SHNOMStyle *resolvedStyle;

@property (nonatomic, strong) UIView *nativeObject;


@end


@implementation SHNOMComponent

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
  return @{@"identifier" : @"id",@"type":@"type",@"style":@"style",@"height":@"height",@"width":@"width"};
}
@end


Derived class from from above class is Button class

#import <UIKit/UIKit.h>
#import <Mantle/Mantle.h>

@interface SHNOMButton : SHNOMComponent <MTLJSONSerializing>

@property (nonatomic, strong) NSString *label;
@property (nonatomic, strong) NSString *name;
@property (nonatomic, strong) NSString *value;

@end


@implementation SHNOMButton

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{@"label": @"label", @"name": @"name", @"value": @"value"};
}

@end

Please let me know if you want more information from my side.

**Comment by AmolServiceHeroes** [comment]
Hi dcaunt,

Is any update on the above-reported issue? or I'm doing something wrong at my end, your inputs will be helpful for me.

**Comment by Abreu0101** [comment]
@AmolServiceHeroes It's a little late, but just for reference you can mark that property as `readonly` (on your interface) and declare as readwrite on an private extension (in case you need it).

From code doc:
```
/// Returns the keys for all @property declarations, except for `readonly`
/// properties without ivars, or properties on MTLModel itself.
+ (NSSet *)propertyKeys;
```

Note: From your example, `SHNOMButton` will overwrite the `JSONKeyPathsByPropertyKey` method of `SHNOMComponent`. You rather should do something like:
```
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    NSDictionary *JSONMapping = @{ @"name"  : @"name",
                                   @"label" : @"label",
                                   @"value" : @"value"
                                  };
    return [[super JSONKeyPathsByPropertyKey] mtl_dictionaryByAddingEntriesFromDictionary:JSONMapping];
}
```
