### ISSUE TITLE
Can I suppress output of nil value?

### ISSUE THREAD

**Issue by soranoba** [Mantle/Mantle#777]
model

```objc
@property (nullable, copy) NSString* firstName; // @"Alice"
@proerpty (nullable, copy) NSString* lastName; // nil
```

model -> json

```objc
{"firstName":"Alice", "lastName":null}
```

In many cases, what becomes null are optional elements, and I think that unnecessary to insert null.
That is...

```objc
{"firstName":"Alice"}
```

Is there a reason to remain "null"?

By inserting the following processing [here](https://github.com/Mantle/Mantle/blob/fd46656f86e112c30383f46a06cdfc713bab660b/Mantle/MTLJSONAdapter.m#L219), nil disappears.

```objc
if ([value isEqual:NSNull.null]) return;
```

Is there any other formal way?

**Comment by davroux** [comment]
+1, I am confront to the same problem.

**Comment by honeyeeb** [comment]
+1, I am confronted to the same problem.

**Comment by Abreu0101** [comment]
+1, same for me.

**Comment by Ashton-W** [comment]
I think it is too late to change this behaviour. You can wrap your transformers to return nil instead of NSNull to fix it on a per property basis. We need NSNull to represent null in JSON vs nil (absence of value)
