### ISSUE TITLE
json model Mantle

### ISSUE THREAD

**Issue by domy18** [Mantle/Mantle#779]
Json
`[
  {
    "term_id": 2,
    "name": "Cat1",
    "slug": "cat1",
    "term_group": 0,
    "term_taxonomy_id": 2,
    "taxonomy": "category",
    "description": "",
    "parent": 0,
    "count": 2,
    "filter": "raw",
    "cat_ID": 2,
    "category_count": 2,
    "category_description": "",
    "cat_name": "Cat1",
    "category_nicename": "cat1",
    "category_parent": 0
  },
  {
    "term_id": 3,
    "name": "Cat2",
    "slug": "cat2",
    "term_group": 0,
    "term_taxonomy_id": 3,
    "taxonomy": "category",
    "description": "",
    "parent": 0,
    "count": 2,
    "filter": "raw",
    "cat_ID": 3,
    "category_count": 2,
    "category_description": "",
    "cat_name": "Cat2",
    "category_nicename": "cat2",
    "category_parent": 0
  }
]`

Model:
`#import "HotelModelMapper.h"

@implementation HotelModelMapper

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
             @"name": @"name",
             @"hotelLocation": @"name",
             @"hotelDescription": @"name",
             
             
             };
}

- (instancetype)initWithDictionary:(NSDictionary *)dictionaryValue
                             error:(NSError **)error {
    self = [super initWithDictionary:dictionaryValue error:error];
    if (self == nil) return nil;
    return self;
}

@end
`

**Comment by dcaunt** [comment]
Can you explain further what your issue is?
