### ISSUE TITLE
Assign default value

### ISSUE THREAD

**Issue by jaumevn** [Mantle/Mantle#781]
Hi there,

Is there any way to assign a default value for a property to be parsed? The property may not be sent in the JSON file. Thanks.

**Comment by ozzotto** [comment]
Use the `- (void)setNilValueForKey:(NSString *)key` method

**Comment by dcaunt** [comment]
If the property is omitted from JSON, I don't think `setNilValueForKey` will be called. Does [this approach](http://stackoverflow.com/a/23245115/80425) work?

**Comment by jaumevn** [comment]
@dcaunt Yes, you are right! `setNilValueForKey` isn't called so isn't a solution. Implementing the `initWithDictionary` method does the trick. Thanks
