### ISSUE TITLE
Invalid pointer dequeued from free list

### ISSUE THREAD

**Issue by MonkYU** [Mantle/Mantle#789]
```objectivec
+ (NSValueTransformer *)ListJSONTransformer {
        return [MTLValueTransformer transformerUsingForwardBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
        NSArray *jsonArray = value;
        NSMutableArray *dataArray = [NSMutableArray arrayWithCapacity:1];
        [jsonArray enumerateObjectsWithOptions:NSEnumerationConcurrent usingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            SubModel *childrenModel = [MTLJSONAdapter modelOfClass:[SubModel class] fromJSONDictionary:obj error:nil];
            [dataArray childrenModel];
        }];
        return dataArray;
    }];
}
```
### If I use the enumerationOptions:NSEnumerationConcurrent, the parse will break down
output info: `malloc: *** error for object 0x600000446d50: Invalid pointer dequeued from free list`

### The break position below:

```objectivec
+ (instancetype)transformerUsingForwardBlock:(MTLValueTransformerBlock)forwardBlock {
	return [[self alloc] initWithForwardBlock:forwardBlock reverseBlock:nil];
}
```

`Thread1: EXC_BAD_ACCESS (code=1, address=0xc100000a)`

# Can not use the concurrent option? 
Thanks

**Comment by JanGorman** [comment]
What is the line `[dataArray childrenModel];` supposed to do?

**Comment by MonkYU** [comment]
[dataArray addchildrenModel]
this line is append model to the dataArray.
so you mean , in any way , it's better to do not use the enumeration options concurrent cause it's not safe?

**Comment by dcaunt** [comment]
Yes, `NSMutableArray` isn't thread safe so you will experience crashes. It's simpler to enumerate serially.

**Comment by MonkYU** [comment]
So thanks.
