### ISSUE TITLE
'@endcode' command does not terminate a verbatim text block

### ISSUE THREAD

**Issue by jozefVrana** [Mantle/Mantle#795]
It's just the documentation warning, but it's there.
Xcode version 8.3.2 gives this warning in MTLJSONAdapter.h

**Comment by dcaunt** [comment]
Please follow #785.

**Comment by acalism** [comment]
\@encode is OK.

**Comment by acalism** [comment]
\\@encode is OK.

**Comment by acalism** [comment]
@@encode is OK
