### ISSUE TITLE
How can I deserialize a JSON by flattening it

### ISSUE THREAD

**Issue by anuj83tripathi** [Mantle/Mantle#796]
I have a JSON object of following structure
UserInfo
{
serverId: (String)
userDetailFor: (UserDetail)
userDetailFrom: (UserDetail)
: 
: 
}

where UserDetail is
{
userId: (String)
name: (String)
}

I need to have the abilities to query coredata to get all the UserInfo objects where userDetailFor.userId = <string>. Coredata doesn't allow multiple relationships between two tables (For/From) as the inverse cannot be set properly. For this reason I need to flatten the DB and store it as
userInfo
{
serverId
userDetailForUserId
userDetailForName
userDetailFromUserId
userDetailFromName
: 
: 
}

Can this be done using Mantle transformers or I need to do it manually?

**Comment by JanGorman** [comment]
The README shows just that https://github.com/Mantle/Mantle#mtlmodel

In your `JSONKeyPathsByPropertyKey` you can:

```objective-c
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
  return @{
    @"userId": @"userDetail.userId",
    …
  };
}
```

**Comment by dcaunt** [comment]
Closing, please follow up if you're still stuck on this.
