### ISSUE TITLE
MTLJSONAdapter.m line 284 crash

### ISSUE THREAD

**Issue by kilolumen** [Mantle/Mantle#798]
MTLJSONAdapter.m line: 284
-[NSNull count]: unrecognized selector sent to instance 0x1aa167ef8

**Comment by dcaunt** [comment]
Please provide the code for your models and related JSON.

**Comment by kilolumen** [comment]
I think there is a lack of "class" judgment

**Comment by dcaunt** [comment]
I'm not sure what you mean, but I'm unable to help without a way to reproduce the issue.
