### ISSUE TITLE
JSON array containing objects of different subclasses of a superclass

### ISSUE THREAD

**Issue by SamAlbuga** [Mantle/Mantle#800]
I've been trying to model a JSON array that contains objects of different subclasses of a superclass.

The superclass has a property `type` which exists in all objects. In the superclass I've placed the `typeJSONTransformer` & I've implemented `classForParsingJSONDictionary:` to decide which subclass should an item should be.

The problem is, `type` in the subclasses is getting the default value of the field & `typeJSONTransformer` isn't getting called.

```objectivec
typedef enum : NSUInteger {
    Type1,
    Type2,
    Type3
} ContentType;

@interface BaseType : MTLModel <MTLJSONSerializing>
@property (nonatomic, assign) ContentType type;
@end

```
```objectivec
@implementation BaseType

+(NSDictionary*)JSONKeyPathsByPropertyKey{
    return @{
             @"type":@"type"
             };
}

+(NSValueTransformer *)typeJSONTransformer {
    NSDictionary *types =@{
                            @"typeOne": @(Type1),
                            @"typeTwo": @(Type2),
                            @"TypeThree":@(Type3)
                            };
    
    return [MTLValueTransformer transformerUsingForwardBlock:^id(id value, BOOL *success, NSError *__autoreleasing *error) {
        return types[value];
    }];
    
}

+(Class)classForParsingJSONDictionary:(NSDictionary *)JSONDictionary{
    NSString *type = JSONDictionary[@"type"];
    
    if ([type isEqualToString:@"typeOne"] 
        return [TypeOneClass class];
    else if ([type isEqualToString:@"typeOne"] 
        return [TypeOneClass class];
    else if ([type isEqualToString:@"typeOne"] 
        return [TypeOneClass class];
    else
        return [BaseType class];
}
```

**Comment by JanGorman** [comment]
What does `+(NSDictionary*)JSONKeyPathsByPropertyKey` look like in the subclasses – they are in charge now of transforming the JSON. Do they include they `type` key as well? (And isn't the class type sufficient in this case, do you really need the additional `ContentType`)

**Comment by SamAlbuga** [comment]
`JSONKeyPathsByPropertyKey` in the subclasses maps the properties that are specific to them, I didn't include type there. (Should I?)
Isn't `JSONKeyPathsByPropertyKey` supposed to merge properties mapped & transformed in the superclass?

```
+(NSDictionary*)JSONKeyPathsByPropertyKey
{
    return @{
             @"height": @"height",
             @"target": @"target"
             };
}
```

**Comment by JanGorman** [comment]
You'll need to merge them explicitly. There's a helper method to let you easily merge mappings:

```objectivec
+(NSDictionary*)JSONKeyPathsByPropertyKey {
  NSDictionary *mapping = @{
    @"height": @"height",
    @"target": @"target"
  };
  return [[super JSONKeyPathsByPropertyKey] mtl_dictionaryByAddingEntriesFromDictionary:mapping];
}
```
