### ISSUE TITLE
Duplicate declaration issue in MTLJSONAdapter.h

### ISSUE THREAD

**Issue by VineetAmipara** [Mantle/Mantle#805]
I am getting an error : Duplicate definition of category 'Deprecated' on interface 'MTLJSONAdapter'.I am also sharing a screenshot for better understanding.

![screen shot 2017-08-03 at 4 24 42 pm](https://user-images.githubusercontent.com/20870534/28919142-d2f71fc8-7869-11e7-9108-2d9f9456e8bd.png)

**Comment by dcaunt** [comment]
Do the two grey information entries under the error provide additional context? They're clipped in the left sidebar in your screenshot, so I can't see.

**Comment by VineetAmipara** [comment]
![screen shot 2017-08-03 at 6 24 07 pm](https://user-images.githubusercontent.com/20870534/28922882-7b03cfcc-7879-11e7-9804-de33a9b7784a.png)

**Comment by dcaunt** [comment]
How are you importing the Mantle framework in your code?

**Comment by VineetAmipara** [comment]
#import <Mantle/Mantle.h>

**Comment by dcaunt** [comment]
Have you tried with `#import <Mantle/Mantle.h>` or `@import Mantle`?

**Comment by VineetAmipara** [comment]
Yes i have tried with both then also not working....

**Comment by JanGorman** [comment]
When we look at the error, it seems to me though that indeed Mantle is added to the project twice? Once via CocoaPods and then once again under a custom path. Was it maybe added manually as well or is there some custom header search path in your project?

**Comment by VineetAmipara** [comment]
I have integrated via CocoaPods and i have not added any custom path. 
How to search for the custom path that weather its added via any custom path or not...?

**Comment by VineetAmipara** [comment]
@JanGorman  and @dcaunt 

This error is coming in Xcode Version 8.3.3 and its not coming in Xcode Version 8.0.
When i open my existing project in Xcode 8.3.3 at the time of building project it shows this error.


I have integrated via cocoaPods and not any custom header path.
I have also tried checking with #import <Mantle/Mantle.h> or @import Mantle statement.

Then also its not working. Please help me get rid of issue....

**Comment by soranoba** [comment]
Hi, @VineetAmipara 

I think that the easiest way to fix is to write include guard in your files.
The name of the file to do is display "In module 'Mantle' imported from ${FILE_PATH}" in the capture file.

```
#ifndef YOUR_FILE_NAME_H
#define YOUR_FILE_NAME_H

@import Mantle;

// your code (your class)

#endif
```

The cause of this phenomenon is probably that the #import (or @import) considered the same file as a different file.

**Comment by VineetAmipara** [comment]
Thanks for your answer @soranaba

Can you please explain it with detail or with a example type or demo type using filename or anything.

Or any reference to apply the above logic.

I am not getting exactly how to apply the above logic in my project.

**Comment by soranoba** [comment]
Sorry, the way to search for files that you should write `include guard` was wrong.
And I made demo.

![2017-10-06 1 05 32](https://user-images.githubusercontent.com/4954289/31238340-a1c18270-aa34-11e7-9f6f-6be41ad75c17.png)


before: https://github.com/soranoba/Mantle/commit/78cfa2e3677ef9a6fdca3e4b789da4ff850e3a5b
after: https://github.com/soranoba/Mantle/commit/22374bba6ffc2ea539db610934c128d08acc2a88

The true cause is that the header is read more than once.
`include guard` is a primitive way to prevent this.

https://en.wikipedia.org/wiki/Include_guard

**Comment by nickbit** [comment]
If cleaning up the project or deleting the derived data folder does not resolve the problem, look at these potential causes:
1) Importing `.m` file instead of `.h`  - Check all your imports
2) Using `#import "Mantle.h"` in some files and `#import <Mantle/Mantel.h>` or similar in others. Safer way is to convert all of them to `@import Mantle`
