### ISSUE TITLE
when I git clone this repo and xc the workspace, build failed cause 

### ISSUE THREAD

**Issue by momo462** [Mantle/Mantle#807]
The file “Debug.xcconfig” couldn’t be opened because there is no such file. (/Users/123/xuexi/Mantle/Carthage/Checkouts/xcconfigs/Base/Configurations/Debug.xcconfig)
The file “iOS-Framework.xcconfig” couldn’t be opened because there is no such file. (/Users/123/xuexi/Mantle/Carthage/Checkouts/xcconfigs/iOS/iOS-Framework.xcconfig)
Build setting PRODUCT_NAME undefined

why  I clone this whole repo and  find Carthage/Checkouts/xcconfigs is empty??

**Comment by dcaunt** [comment]
Did you `init` the submodules (`git submodule update --init --recursive`)? 

There are some instructions [here](https://github.com/Mantle/Mantle#importing-mantle).

**Comment by momo462** [comment]
thanks for your help !!@dcaunt
