### ISSUE TITLE
Swift 4.0 issue

### ISSUE THREAD

**Issue by MohamedElzohirey** [Mantle/Mantle#811]
When using with Swift 4 project 
it failed to get the keys and keys array is empty

 Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'key_1 is not a property of MyClass'

**Comment by dcaunt** [comment]
Can you post the relevant code for your model's header/implementation and the JSON you're decoding please?

**Comment by dcaunt** [comment]
@wilzog Please post the code for your models so that I can reproduce the issue.

**Comment by gogoswift** [comment]
i have le the same problem, when i use mantle in swift4

1 Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'key_1 is not a property of MyClass'

Solve：add “@objc” in front of property 

2  when model class has Array：NSArray element failed to match the Swift Array Element type
This i can not solve，need help

**Comment by gogoswift** [comment]
WeatherModel Class

import UIKit

class WeatherModel:MTLModel, MTLJSONSerializing {
    var latitude : Double = 0.0
    var longitude : Double = 0.0
    var timezone : String?
    var offset : Int = 0
    class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any]!
    {
        return ["latitude":"latitude"]
    }

====================== ViewController=================

import UIKit

class ViewController: UIViewController {
    let api = "https://web.itu.edu.tr/ozdile/weather-model.json"

    override func viewDidLoad() {
        super.viewDidLoad()
        fetchData()
        // Do any additional setup after loading the view, typically from a nib.
    }
    func fetchData() {
        Alamofire.request(api).responseJSON(completionHandler: { (response) in
            if let jsonDictionary = response.result.value as? [AnyHashable: Any] {
                let model: WeatherModel = try! MTLJSONAdapter.model(of: WeatherModel.self, fromJSONDictionary: jsonDictionary) as! WeatherModel
                print(model.latitude)
            }
        })
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}


}


i use alamo fire

**Comment by gogoswift** [comment]
Solve：add “@objc” in front of JSONTransformer()  fun
ex:
@objc class func dataJSONTransformer() -> ValueTransformer {
        return MTLJSONAdapter.arrayTransformer(withModelClass: DataModel.self)
    }
