### ISSUE TITLE
[suggestion] make the JSONKeyPathsByPropertyKey merging data from parent

### ISSUE THREAD

**Issue by maxpaynebupt** [Mantle/Mantle#814]
I am using mantle to set up my model layer, but, it seems that the mantle only use the child class's JSONKeyPathsByPropertyKey method to get the mapping definition, it's better to merge the parent and the child's JSONKeyPathsByPropertyKey 's return dictionary, so the definition can be inherited too.

I set up a sub class of MTLJSONAdapter and overwrote  initWithModelClass, in which I replaced the [modelClass JSONKeyPathsByPropertyKey] with a new method to recurvely get the parent's JSONKeyPathsByPropertyKey dict and merged them with the modelClass's. 

With this , in my child class's JSONKeyPathsByPropertyKey  function, I dont need to rewrite the property in the parent class's JSONKeyPathsByPropertyKey.

**Comment by dcaunt** [comment]
The problem with this (breaking change) is that some users of Mantle may not want this behaviour by default, and then there would need to be a way to opt out. Given that it's reasonably simple to merge in the parent keys I think it's best that it requires explicit merging. 

I think your approach of subclassing `MTLJSONAdapter` is the best way. Mantle is designed to support these use-case specific customisations in this way.

Alternatively you can use the the `mtl_dictionaryByAddingEntriesFromDictionary` on `NSDictionary` to merge your keys with the keys returned by `[super JSONKeyPathsByPropertyKey]` in your `MTLModel` subclasses.
