### ISSUE TITLE
I get `Too many symbol files - These symbols have no corresponding slice in any binary`

### ISSUE THREAD

**Issue by haemi** [Mantle/Mantle#816]
I included Mantle as submodule and now when I submit to iTunes Connect I get `Too many symbol files - These symbols have no corresponding slice in any binary`. What irritates me: in my dSYMs-folder I do have `Mantle.framework 1.dSYM`  and `Mantle.framework.dSYM`. The latter has the UUID mentioned in the mail.

What am I doing wrong here?

**Comment by dcaunt** [comment]
How are you integrating Mantle? Are you using CocoaPods or Carthage?

**Comment by haemi** [comment]
according to this:
```

    Add the Mantle repository as a submodule of your application's repository.
    Run git submodule update --init --recursive from within the Mantle folder.
    Drag and drop Mantle.xcodeproj into your application's Xcode project.
    On the "General" tab of your application target, add Mantle.framework to the "Embedded Binaries".
```

**Comment by robb** [comment]
`Mantle.framework 1.dSYM` seems suspicious, could it be that it's getting linked or embedded twice?

**Comment by haemi** [comment]
i think I solved the problem but I don't know why it's necessary (and if it's only me who is affected): i changed the `Debug Information Format` for the Mantle Targets from `DWARF with dSYM file` to `DWARF`, now the warning is gone.

**Comment by robb** [comment]
Cool, feel free to reopen this if need be.
