### ISSUE TITLE
How to import Mantle in my framework?

### ISSUE THREAD

**Issue by leomyth330** [Mantle/Mantle#820]
I created cocoa touch framework target to share codes between main app and today extension.
In my custom framework, I want to import `Mantle` framework but I'm not sure how I can do that.

Please let me know any suggestions.

**Comment by soranoba** [comment]
Have you read this?
https://github.com/Mantle/Mantle#importing-mantle

**Comment by leomyth330** [comment]
Yeah, solved by downloading .framework.
