### ISSUE TITLE
Cocoapods & Continued Viability of Unofficial Support?

### ISSUE THREAD

**Issue by abotkin-cpi** [Mantle/Mantle#831]
**Problem Description**

As noted in the README, Cocoapods has been unofficially supported via spec submissions from community members.  However as Cocoapods has moved towards the [Trunk service](http://blog.cocoapods.org/CocoaPods-Trunk/) where there is a list of owners who are the only ones with access control to push new spec updates, it seems like this unofficial support has pretty much been unable to continue as the only folks who are able to update the specs are:

```
    - Owners:
      - Robert Böhnke <REDACTED>
      - Jan Gorman <REDACTED>
      - David Caunt <REDACTED>
```

The last Cocoapods spec that was submitted was tied to Mantle 2.1.0 & so several changes that have been pushed since to fix warnings & such since Oct 2016 have not been made available to folks using the unofficial Cocoapods support.  With many other third-party library documentation pushing folks toward Cocoapods (like Google's [Firebase](https://firebase.google.com/docs/ios/setup)), it doesn't seem unlikely folks may be utilizing this out-of-sync Cocoapods spec.

**Path Forward?**

Given the way Cocoapods' Trunk service works with ownership, unofficial support without the intervention of at least one of the listed owners in the Cocoapods Trunk service is no longer possible.  It seems like the only way the unofficial support could continue would be if the podspec gets added into repository & some individual is designated in the Cocoapods' Trunk ACL who'll push the podspecs that get accepted from community-submitted pull requests (maybe adding something into the README stating that Cocoapods support is only updated by <designee> based off of submitted & accepted pull requests, marking that designee as the code owner for the podspec file, etc.).

I'm more than happy to submit a pull request adding a podspec that works with the latest changes, but it seems like given the challenges of Cocoapods' Trunk service's ACL requirements that a policy decision needs to be made by the maintainers on what they're comfortable doing.

**Comment by abotkin-cpi** [comment]
@robb Any thoughts on Cocoapods support going forward?

**Comment by robb** [comment]
I'm pretty out of touch with CocoaPods but I'm definitely for supporting it. I sent you an invite, feel free to submit whatever specs are necessary.

**Comment by abotkin-cpi** [comment]
Got the invite & accepted.  I'll get a spec up for review by Monday at the latest (have an internal project I have to complete by EOD Thursday).

**Comment by robb** [comment]
Given the last year or so of activity, there's really no way to rush ;-)

**Comment by abotkin-cpi** [comment]
@robb One question I do have for you is your thoughts on automating submission to Cocoapods using a free cloud CI going forward?

I could set up GitHub Actions (it's free for open source projects) in order to automate the Cocoapods submission when a tag/release is created.  An example of how that might work can be seen in this [GitHub Action](https://github.com/marketplace/actions/deploy-to-cocoapod-action).  We'd still need to manually update the [Cocoapods Trunk secret](http://guides.cocoapods.org/making/getting-setup-with-trunk.html) in the GitHub Actions setup every 5 months.

Otherwise, we'll have to put it as a release task to update the tag in the Podspec & ask someone in the Mantle org (like myself now) to submit on every release/tag.

**Comment by robb** [comment]
👌 Automation with GitHub Action seems like the way to go and I defer to your best judgement.
