### ISSUE TITLE
memory leak about not freeing malloc pointer in mtl_copyPropertyAttributes method

### ISSUE THREAD

**Issue by jianpx** [Mantle/Mantle#832]
I use Xcode's Analyze to find out a memory leak in this method
`mtl_propertyAttributes *mtl_copyPropertyAttributes (objc_property_t property)`

**Comment by adrian-niculescu** [comment]
Easily fixed with `goto errorOut;` instead of `return NULL;` there.

**Comment by robb** [comment]
Fixed in #844.
