### ISSUE TITLE
No known class method for selector 'arrayTransformerWithModelClass:'

### ISSUE THREAD

**Issue by Nagarjun123** [Mantle/Mantle#835]
Hi,

I am using Mantle version 1.5 and getting error 
**"No known class method for selector 'arrayTransformerWithModelClass:'"**

My JSONTransformer code is 

![Screen Shot 2019-05-13 at 12 44 49 pm](https://user-images.githubusercontent.com/13017830/57593022-ef23b500-757c-11e9-970f-cc16cfe3e03a.png)

I can see arrayTransformerWithModelClass method in version 2.1 but I am searching alternate method in OLD Mantle version. Any help please?

**Comment by ikesyo** [comment]
Why not check v1.5 source codes? 

https://github.com/Mantle/Mantle/blob/1.5.8/Mantle/NSValueTransformer+MTLPredefinedTransformerAdditions.h#L36-L45

**Comment by Nagarjun123** [comment]
@ikesyo Thanks.

That was method from NSValueTransformer and it worked.

```
+ (NSValueTransformer *)tasksJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[TasksModel class]];
}
```
