### ISSUE TITLE
Value did not match expected type, NSLocalizedFailureReason=Expected 144.960302320699 to be of class NSValue but got __NSCFString}

### ISSUE THREAD

**Issue by Nagarjun123** [Mantle/Mantle#836]
Hi,

I have a model as below:

![Screen Shot 2019-05-13 at 12 58 09 pm](https://user-images.githubusercontent.com/13017830/57593455-d2887c80-757e-11e9-9cfb-a4d921ada6e5.png)

While parsing JSON I am getting:

**Error Domain=MTLTransformerErrorHandlingErrorDomain Code=1 "Value did not match expected type" UserInfo={MTLTransformerErrorHandlingInputValueErrorKey=144.960302320699, NSLocalizedDescription=Value did not match expected type, NSLocalizedFailureReason=Expected 144.960302320699 to be of class NSValue but got __NSCFString}**

Earlier I was using Mantle version 1.5 it was working fine. But recently I have updated POD and getting this error:

![Screen Shot 2019-05-13 at 12 55 25 pm](https://user-images.githubusercontent.com/13017830/57593362-6d348b80-757e-11e9-90aa-8b1e52ff57a1.png)

My question is why is Mantle changed type difference in both versions. How to solve this issue and is there any JSONTransfomer need to write for CLLocationDegrees?

**Comment by ikesyo** [comment]
I think that's due to https://github.com/Mantle/Mantle/blob/2.0/CHANGELOG.md#type-checking-during-json-parsing.
