### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by luismmejiasb** [Mantle/Mantle#847]
Please add support for adding dependencies with Swift Package Manager 🙏

**Comment by abotkin-cpi** [comment]
Unless someone else would like to take this on, I can probably take a look this weekend.  My understanding is an ObjC Target is supported (so long as it doesn’t mix any Swift in the same Target) and it seems [some folks have done this with AFNetworking](https://forums.swift.org/t/swift-package-manager-for-objc-targets/25968/4).
