### ISSUE TITLE
Null sub-models are now considered as errors

### ISSUE THREAD

**Issue by WirecardMobileServices** [Mantle/Mantle#852]
Hi,

the following fix "Error added for passing nil JSON dictionary to -[MTLJSONAdapter modelFromJSONDictionary:error:]" has complications of its own.

In Mantle, the following is done:
value with null => it is set to nil,
value with nil is then send to transformedValue,
value it set again as null.

The problem arises when you have a model with models within: 
If one submodel value comes as null, Mantle will interpret is as nil for transformedValue. But the new "fix" will consider that we are trying to create a model with a nil JSON, and the whole model generation fails.

Is the new "fix" really needed? It is incompatible with any recursive use and null values. Any suggestion for an improvement or workaround?

**Comment by robb** [comment]
Hi, you're talking about #751? If so, can you share an example case that fails now and didn't in 2.1.0?

**Comment by WirecardMobileServices** [comment]
[MantleBug.zip](https://github.com/Mantle/Mantle/files/4148595/MantleBug.zip)

Hi Robb, 
I attached a quick project with all needed to repro the issue. The high level concept of the problem is, having defined:

Class A { .. }
Class B { var something : A, ... }

is that, when you have _null_ as value of the variable "something", the construction of model B fails, even though _null_ is no reason for it to fail and the rest of the model has correct data.

Before the introduction of the ""Missing JSON dictionary" nil check, this was working fine. It simply avoid the construction of models with models within if any value comes as null.

**Comment by WirecardMobileServices** [comment]
We'll provide an example shortly

**Comment by WirecardMobileServices** [comment]
Hi, 
attached a short project for reproducing the problem.
Issue: _modelFromJSONDictionary_ may end up creating a model correctly, but it will return an error anyways if some value within was null. Just run the project and see the loadJSON result.
[MantleBug.zip](https://github.com/Mantle/Mantle/files/4152778/MantleBug.zip)

**Comment by robb** [comment]
Hmm, not sure I understand what the problem is.

The encoded JSON payload in your example contains an extra `@` character before the `"name"` value:

```objc
@"{\"name\": @\"name\", \"dummy\": null}"
```

which makes `NSJSONSerialization` return `nil` when parsing the data. Attempting to deserialize a `ClassB` instance from that errors.

However, if I fix the literal, the following runs just fine:

```objc
NSString *jsonText = @"{\"name\": \"name\", \"dummy\": null}";
NSData *data = [jsonText dataUsingEncoding:NSUTF8StringEncoding];
NSError *error = nil;
NSDictionary *jsonDict = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];
MTLJSONAdapter *adapter = [[MTLJSONAdapter alloc] initWithModelClass:ClassB.class];
id model = [adapter modelFromJSONDictionary:jsonDict error:&error];

if (error && model)
{
	NSLog(@"Why do we get an error if the model ClassB is properly generated? The error doesn't even tell what model actually failed.");
}
```

```lldb
(lldb) po model
<ClassB: 0x100b10c20> {
    dummy = "<null>";
    name = name;
}
```

**Comment by robb** [comment]
@WirecardMobileServices any news on this?

**Comment by WirecardMobileServices** [comment]
> @WirecardMobileServices any news on this?

We were propagating the error improperly in our side. You can close the issue (and thanks).

**Comment by robb** [comment]
Sure thing, thanks for taking the time to send an example project over. ✌️
