### ISSUE TITLE
Warning: 'os_unfair_lock' is only available on iOS 10.0 or newer

### ISSUE THREAD

**Issue by abotkin-cpi** [Mantle/Mantle#853]
As part of #844, extobjc was updated & one of the methods, `mtl_globalMethodSignatureForSelector` added calls to `os_unfair_lock` API which only became available in iOS 10, tvOS 10, & watchOS 3.  Mantle still claims a requirement of iOS 8, tvOS 9, & watchOS 2 which lack this API.

It doesn't seem like `mtl_globalMethodSignatureForSelector` is critical for Mantle to work - we could just annotate the method with `API_AVAILABLE(macos(10.12), ios(10.0), tvos(10.0), watchos(3.0))` and if there is demand for it in iOS 9 or below, add it later.

If we were to add iOS 9 or below support to it, it seems [other folks have used `pthread_mutex` for iOS 9 and below & used an `@available(iOS 10, *)` check to use the API](https://gist.github.com/steipete/36350a8a60693d440954b95ea6cbbafc#gistcomment-1889251).

**Comment by robb** [comment]
Ah, my bad, didn't catch that warning. Considering that the method doesn't seem to be used, the annotation, I guess we might as well remove it? Keeping a complete copy of libextobjc was just laziness on my part.

**Comment by abotkin-cpi** [comment]
Yeah, removing or just annotating the method both seem fine to me.  Let me know if you'd like me to put up a PR for removal.

**Comment by robb** [comment]
i'm leaning towards removal.

**Comment by abotkin-cpi** [comment]
Removal PR has been put up.
