### ISSUE TITLE
I got this error [modelClass isSubclassOfClass:MTLModel.class]

### ISSUE THREAD

**Issue by Mjbanker** [Mantle/Mantle#863]
I got this error  [modelClass isSubclassOfClass:MTLModel.class] after updating AFnetworking pod in my project, with previous AFnetworking version Mantle library works proper.

Thanks In Advance,
Mittal

**Comment by robb** [comment]
Can you help us and share what kind of `modelClass` is?

**Comment by Mjbanker** [comment]
Hi,
This UserModel is a subclass of Class say X and this class X is subclass of MTLModel.

Thanks In Advance,
Mittal

**Comment by robb** [comment]
`isSubclassOfClass` works transitively, so there's likely something else going on – It's a little hard to say without knowing more about your project though.

**Comment by Mjbanker** [comment]
Hi,
Mantle is added as cocoapods dependecy in project A and project A is added as explicit dependency in project B's workspace to project B .

**Comment by JanGorman** [comment]
@Mjbanker are you building with Xcode 12? I think what you're referring to here is the changed default value of `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` which is now set to yes by default

**Comment by Mjbanker** [comment]
Hi,
I am using Xcode 11.6.

Thanks,
Mittal.

**Comment by JanGorman** [comment]
I see there's a related bug fix on CocoaPods https://github.com/CocoaPods/CocoaPods/issues/9902

Anyway – it doesn't seem to be a problem (anymore), you updated your imports and it's working fine now?

**Comment by harshalbhattmob** [comment]
The issue was like mentioned in https://stackoverflow.com/questions/19883472/objc-nsobject-issubclassofclass-gives-incorrect-failure . The pod install was not removing mantle reference in other xcconfig file removing the reference resolved the issue.

**Comment by Mjbanker** [comment]
Hi,

Thanks @harshalbhattmob My Issue is solved. I am using Mantle library only in project A, but I add Mantle in all target in pod file so for solution I only add mantle in project A target, run pod deintergarate and install again solved the issue.
