### ISSUE TITLE
How to set NSInteger property in model

### ISSUE THREAD

**Issue by SayHelloToWorld** [Mantle/Mantle#864]
Hi, I have a problem using NSInteger, it seems that the support for int is limited.
My model here:
```objc
@interface Feed : MTLModel <MTLJSONSerializing>

@property (assign, nonatomic, readonly) NSInteger likes;    
@property (strong, nonatomic, readonly) NSString *imageURL;

@end
```
And the blocks in method transformerUsingForwardBlock is id input and id output, but NSInteger is a Primitive type, How should I transform this  NSInteger?

**Comment by robb** [comment]
Mantle uses Key Value Coding, using `NSNumber` for the `likes` property should do the trick.
