### ISSUE TITLE
Xcode 12 build compatibility

### ISSUE THREAD

**Issue by pyby** [Mantle/Mantle#865]
Xcode 12 is now released for all. We can found a buildable version on `master`, but not in the latest release.
When did you plan deliver a new release?

Thank you @yhkaplan for the PR #862, and @robb for approved it.

**Comment by robb** [comment]
I'll investigate cutting a release this weekend. That said, if you'd like to help out I'd gladly add you to the team.

**Comment by dcaunt** [comment]
Let me know if I can help with anything.

**Comment by robb** [comment]
I published 2.1.2, let me know if it does the trick.

**Comment by pyby** [comment]
Thank you. We use Carthage dependency and it works as expected. Perfect.

We planned to move to SPM dependency. I'll have a look on the existing branch soon.
