### ISSUE TITLE
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99.

### ISSUE THREAD

**Issue by mathaeus** [Mantle/Mantle#885]
Integrating `Mantle` in Xcode 12 via SPM:

<img width="674" alt="Screenshot 2021-06-11 at 14 37 04" src="https://user-images.githubusercontent.com/5389635/121687373-90fe8e80-cac2-11eb-971b-1e4cebd10462.png">

**Comment by robb** [comment]
Do you mind checking if setting the minimum deployment target to 9 is enough to resolve this issue? (I don't use SPM for ObjC dependencies and I wouldn't be surprised if it took more than that to make this work.)

**Comment by mathaeus** [comment]
@robb sorry for not mentioning this, deployment target is `iOS 12`.

From what I know the underlying problem is an Xcode problem and there have been equivalent issues in other SDKs, e.g. https://github.com/firebase/firebase-ios-sdk/issues/6533
But since we are not using cocoapods anymore, I can't use a pod-post-install script to solve it.

**Comment by robb** [comment]
Hmm, so there's nothing we can do? Would a precompiled XCFramework help? See #879.

**Comment by mathaeus** [comment]
> Hmm, so there's nothing we can do?

This could be increased to `.iOS(.v9),`.
https://github.com/Mantle/Mantle/blob/master/Package.swift#L9

I would say it's safe to assume that people using SPM are using Xcode 12 and therefore the minimum deployment target is `iOS 9`. But again, this is just an assumption :)

> Would a precompiled XCFramework help? See #879
I'm honestly not sure what #879 is asking for? 🤔

**Comment by robb** [comment]
Haha, I completely forgot that we have a `Package.swift` 😵‍💫.

> I would say it's safe to assume that people using SPM are using Xcode 12

That sounds like a reasonably assumption. However, for this to work, we would also have to raise the minimum deployment target in the Xcode project, right? That would technically be a breaking change that required a new major version. I have a feeling that Mantle skews towards older apps. Do you happen to know if Apple still lets you submit iOS 8.0 apps to the store?

> I'm honestly not sure what #879 is asking for? 🤔

I think they are asking for the ability to download a zipped XCFramework from GitHub's release page. My understanding is that could also be used by SPM to download a binary artifact.

**Comment by mathaeus** [comment]
> Do you happen to know if Apple still lets you submit iOS 8.0 apps to the store?

[Doesn't look like](https://developer.apple.com/news/?id=ib31uj1j): 
> Starting April 26, 2021, all iPhone and iPad apps submitted to the App Store must be built with Xcode 12 and the iOS 14 SDK or later

Xcode 12 has the minimum deployment target of iOS 9, hence also the warning.
<img width="296" alt="Screenshot 2021-06-15 at 10 13 53" src="https://user-images.githubusercontent.com/5389635/122017629-6febb580-cdc2-11eb-913f-4e60862b8700.png">


----
> My understanding is that could also be used by SPM to download a binary artifact.

👍 
Providing an xcframework would have the advantage that the target app wouldn't need to build the source code.

**Comment by robb** [comment]
I guess then there's little risk in bumping the minimum deployment target without a major version increase ¯\_(ツ)_/¯ Would you mind filing a PR to that effect?

> Providing an xcframework would have the advantage that the target app wouldn't need to build the source code.

Yeah, I kinda want to offer this but I haven't made particularly great experiences with GH actions to automate this.

**Comment by mathaeus** [comment]
@robb sure, there you go https://github.com/Mantle/Mantle/pull/886

**Comment by robb** [comment]
Closed in #886
