### ISSUE TITLE
Handling null values when mapping to a BOOL property

### ISSUE THREAD

**Issue by joaodforce** [Mantle/Mantle#892]
In my MTLModel class I have the following property:

`@property (assign) bool FuncionarioPodeLancar;`

Its a basic type boolean, when the back end sends `true` or `false` on the JSON object, it all works as expected, however Ive noticed that many times it returns `null` instead of actual `false`. IMO its bad practice from the back end team, but the issue is very widespread on my project, so I would expect to treat `null` as `false`.

Mantle however, when dealing with this just fails the JSON Decoding.

```
*** Caught exception setting key "FuncionarioPodeLancar" : [<MotivoAusencia 0x600000271a00> setNilValueForKey]: could not set nil as the value for the key FuncionarioPodeLancar.
```

It fails with an attempt to insert `nil` into the value.

Is it possible to treat this by modifying my model whilst keeping in boolean? I attempted to create a custom valueTransformer, however it seems like it is not possible to use a valueTransformer to return basic types, only pointers.

Maybe this should be fixed on the library itself?

**Comment by mkjhgfdsa123** [comment]
诚聘网络兼职工资日结!还不~错详情请登陆招聘网站http://brhlqvy.cn?9

**Comment by robb** [comment]
> I attempted to create a custom valueTransformer, however it seems like it is not possible to use a valueTransformer to return basic types, only pointers.

You can return an `NSNumber` and [Key-Value-Coding will do the right thing](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/KeyValueCoding/DataTypes.html#//apple_ref/doc/uid/20002171-BAJEAIEE).

**Comment by robb** [comment]
Feel free to reopen if the `NSNumber`-based approach doesn't work.

**Comment by robb** [comment]
I think a more idiomatic way would be to implement [a validation method](https://developer.apple.com/documentation/objectivec/nsobject/1416754-validatevalue?language=objc) and assign whatever value you see fit.

**Comment by joaodforce** [comment]
> Feel free to reopen if the `NSNumber`-based approach doesn't work.

I made a value transformer like this and it worked. Thanks a lot.

```
+ (NSValueTransformer *)nullableBooleanTransformer {
    return [MTLValueTransformer transformerUsingForwardBlock:^id(NSNumber *val, BOOL *success, NSError *__autoreleasing *error) {
        if (val == nil || [val isEqual:[NSNull null]]) {
            return @(NO);
        }
        return val;
    } reverseBlock:^id(NSNumber *val, BOOL *success, NSError *__autoreleasing *error) {
        return val;
    }];
}
```
