### ISSUE TITLE
strncpy  code security issue

### ISSUE THREAD

**Issue by KaisEbraheem** [Mantle/Mantle#894]
I am using Mantle in our iOS apps (Objective-C & Swift) for a many years now. Recently  I have scanned the code using the SonarQube sonar-scanner tool which revealed several HIGH priority security issues on one particular file : **MTLEXTRuntimeExtensions.m**,  all issues are related to the use of  _strncpy_  C-function.  Can you please update the code to address this security issue  in  _MTLEXTRuntimeExtensions.m_.
One possible alternative is  strlcpy.c  (although not part of the standard C-library, it's available on Apple macOS since 2011).
See: [https://www.usenix.org/legacy/events/usenix99/full_papers/millert/millert.pdf](https://www.usenix.org/legacy/events/usenix99/full_papers/millert/millert.pdf)

**Comment by KaisEbraheem** [comment]
See: https://www.usenix.org/legacy/events/usenix99/full_papers/millert/millert.pdf

**Comment by robb** [comment]
Thanks for flagging the issue 💖 

That said, it's been a while since I've written C, what's the security issue being flagged by the tool and how does `strlcpy` alleviate it?

Happy to look at any PR to the effect.
