### ISSUE TITLE
dSYM files of Mantle

### ISSUE THREAD

**Issue by yeyocp** [Mantle/Mantle#896]
Hello. I would like to know if there would be any way of getting the dSYM files of the Mantle library. I'm working with Instabug and I'm having some crashes that seem to be related with Mantle, and it would be great to see the Mantle traces (I would need the dSYM files for it) of those classes to be more clear about the origin of the crash.

Thank you.

Best regards.

**Comment by robb** [comment]
I don't think we offer prebuilt binaries so I would assume you are either building Mantle yourself or obtain it as part of a library somehow. I'm not sure how to help in either scenario (I don't believe dSYM files are necessarily stable across different builds?).

**Comment by robb** [comment]
My bad, we did actually offer binaries at some point – that said, the archiving action hasn't worked for a while and I'm not sure how we could produce matching dSYMs for these very old builds.

That said, if you wanted to fix the archiving action and add matching dSYM going forward, I'd be happy to review a PR to that effect.
